cmd/cnosdb/run/run.go, server/server.go
Closes #226 
This PR could test in this way.
first use `docker build -t . [imageName]` to build a image locally.
then use `docker run` to start the image.
finally use `docker stop` to stop it.
=> fix(bug): docker-stop takes a long time.

cmd/cnosdb-cli/cli/command_line.go
Closes #413 
fix(cmd): Timestamp with single quote or double quote returns an 'bad timestamp' error in INSERT statement.
=> fix(cmd): invalid timestamp returns an error

tskv/src/compaction/compact.rs, tskv/src/main.rs, tskv/src/tsm/index.rs, tskv/src/tsm/writer.rs
Closes #465 .
1. Fix bugs in #465 
2. The tsm-writer now write the input datablock directly.
No.
=> fix #465: tsm-writer now write the input datablock directly

tskv/src/compaction/compact.rs, tskv/src/kv_option.rs, tskv/src/summary.rs, tskv/src/tseries_family.rs, tskv/src/tsm/block.rs, tskv/src/tsm/index.rs, tskv/src/tsm/mod.rs, tskv/src/tsm/reader.rs, tskv/src/tsm/tombstone.rs, tskv/src/tsm/writer.rs
No.
Changed some logic in compact:
1. Store DataBlocks in merging_blocks, merged_blk_timerange set by the first BlockMeta
2. For each BlockMeta:
2.1. If it's timerange overlaps with merged_blk_timerange, read DataBlock and push to merging_blocks, and update merged_blk_timerange
2.2. Else:
2.2.1. If merging_blks's length is 1 and it's a Raw, put to self::merged_blocks.
2.2.2. Else merge merging_blks into Vec<DataBlock>, push to back of self::merged_blocks, and clean merging_blks.
The last one of the Vec<DataBlock> is special, if it's length is less than self::max_datablock_values, do not push it.
2.2.3. If it's length reaches self::max_datablock_values, put Raw to merging_blks, otherwise put DataBlock (2.2.1).
3. Read DataBLock for the remaining BlockMeta, push to self::merged_blks.
1. …
=> feat(compaction) #433: improves compaction:

tskv/src/compaction/compact.rs, tskv/src/kvcore.rs, tskv/src/main.rs, tskv/src/tseries_family.rs, tskv/src/tsm/block.rs, tskv/src/tsm/index.rs, tskv/src/tsm/reader.rs, tskv/src/tsm/tombstone.rs, tskv/src/tsm/writer.rs, utils/src/bloom_filter.rs
Nothing.
1. Change some `min_ts, max_ts` to `TimeRange`.
2. Some Clippy suggested refactors.
When I added some test cases, I find these bugs and fixed them.
```
cargo test --package tskv --lib -- compaction::compact::test::test_compaction_4
cargo test --package tskv --lib -- tsm::reader::test::test_tsm_reader_2
cargo test --package tskv --lib -- tsm::block
```
1. Add new argument `--tombstone` for task::main for debug.
1. TsmTombstone now use `open_for_read()` and `open_for_write()` to get an instance, instead of `with_tsm_file_id`.
2. Tombstone now have a TimeRange field, min_ts & max_ts are removed.
=> feat(compaction) #433: fixs bugs when compact tsm_files with tombstones

query/tests/datafusion.rs, tskv/benches/kvcore_bench.rs, tskv/src/kvcore.rs, tskv/src/memcache.rs, tskv/src/tseries_family.rs, tskv/src/wal.rs, tskv/tests/test_kvcore_interface.rs
1. implement `From<tseries_family::TimeRange>`
2. SupperVersion::new() has too many arguments
3. TseriesFamily::put_mutcache() has too many arguments
4. Reduce duplicated code in kvcore.rs
=> fix(clippy): tseries_family.rs

tskv/src/compaction/compact.rs, tskv/src/compaction/flush.rs, tskv/src/compaction/mod.rs, tskv/src/compaction/picker.rs, tskv/src/kvcore.rs, tskv/src/lib.rs, tskv/src/memcache.rs, tskv/src/summary.rs, tskv/src/tseries_family.rs, tskv/src/tsm/block.rs, tskv/src/tsm/mod.rs, tskv/src/tsm/reader.rs, tskv/src/tsm/writer.rs, tskv/src/version_set.rs, tskv/src/wal.rs, tskv/tests/test_kvcore_interface.rs
When a new file created by flush, we want to modify the `Version::levels_info`. When cache is needed in query, we read the `TsFamily::caches`. It's necessary to hold a  `RwLock` for `Version` or `VersionSet` now. #446 #519 
Since the `RwLock` is removed, `Version` and `SuperVersion` become readonly, a better way to modify them is by the **summary write job**. When a series of `VersionEdit` persisted by the **summary write job**,  a new `Version` is created by the old `Version` and `VersionEdit`s. Then replace olds with the news.
Now it's (max_ts, min_ts), different with rust slices(`&slice[min..max]`) and the number axis intervals(`[min, max)`), sometimes it makes puzzles.
1. Add min_seq_no in `MemCache`, if it's smaller than Version::last_seq, we can safely remove it.
2. When call …
=> feature(summary) #446: some refactor about summary.

config/Cargo.toml, config/config.toml, config/src/lib.rs, main/Cargo.toml, main/src/main.rs, tskv/benches/kvcore_bench.rs, tskv/src/compaction/compact.rs, tskv/src/compaction/flush.rs, tskv/src/compaction/picker.rs, tskv/src/index/forward_index.rs, tskv/src/kv_option.rs, tskv/src/kvcore.rs, tskv/src/summary.rs, tskv/src/tseries_family.rs, tskv/src/tsm/mod.rs, tskv/src/version_set.rs, tskv/src/wal.rs, tskv/tests/test_kvcore_interface.rs
Closes #482.
Closes #437.
There are a lot code change for for #482.
Changes in this PR make Options like `DBOptoins` can never be shared using `DBOptions::default()`, one alternative is `Arc<DBOptions>`, so #437 can be closed.
1. `GlobalConfig` use `OnceCell` to load the config-path parsed from the command line arguments lazily.
2. Options like `DBOptions` now have a `From<&GlobalConfig>` trait, remove their `Default` trait.
3. Merge `TseriesFamOpt` and `MemCacheOpt`, remove `MemCacheOpt`.4. 
4. Other changes to let their unit-tests run normally.
=> feat(cli) #482: GlobalConfig now use path to init.

tskv/src/compaction/compact.rs, tskv/src/compaction/picker.rs, tskv/src/kvcore.rs, tskv/src/tseries_family.rs
Closes #464 #433 .
Improved `LevelCompactionPicker` aims to pick `ColumnFiles` in Level-0 and Level-n(n>0) at the same time :
1. Selects a Level with the highest score.
2. Picks files in Level-n from lower timestamp to higher.
3. Picks files in Level-0 using the time range overlapped with file picked step-2.
1. Function `run_compaction_job()` now produces **one** VersionEdit.
2. Use `VersionEdit` generated by `run_compaction_job()` to check compacted files in unit tests.
=> feat(compaction) #464: Improves LevelCompactionPicker.

line_protocol/src/parser.rs, main/src/http/handler.rs, main/src/http/mod.rs, main/src/main.rs, query/src/catalog.rs, query/src/table.rs, tskv/src/kvcore.rs
Add handler for uri `/query/sql`.
An example: `curl -v -X POST http://127.0.0.1:31007/query/sql?database=dba --data "select * from ta"`
=> feat(server): add query handler

.gitignore, models/src/errors.rs, models/src/field_info.rs, query/src/helper/domain.rs, query/src/helper/mod.rs, query/src/predicate.rs, query/src/schema.rs, query/src/table.rs
Closes #.
- support 'and' expr TableScan pushdown
- partial support 'or' expr  TableScan pushdown
- support '=' '>' '<'  '<=' '>=' operators expr  TableScan pushdown
- support Neste supported expr
- not support 'not' 'in' 'is not null' 'not null' 'between and'
no
no
=> feat(query) #539: support convert filter expr to domains for TableScan

query/src/extension/datafusion/expr/func_manager.rs, tskv/src/compaction/compact.rs, tskv/src/compaction/flush.rs, tskv/src/compaction/picker.rs, tskv/src/summary.rs, tskv/src/tseries_family.rs, tskv/src/tsm/writer.rs
1. Fix: LevelInfo::init() does not set the max_size.
2. Fix: TsmWriter writes delta files to *.tsm, not *.delta.
3. Fix: Version::copy_apply_version_edits() does not apply del_files when there is also a add_files in VersionEdit.
4. Fix: tsm file starts from 2 but not 1.
=> Fix some bugs, and add some log printing codes

config/src/lib.rs, query_server/query/src/catalog.rs, tskv/src/compaction/picker.rs, tskv/src/database.rs, tskv/src/engine.rs, tskv/src/error.rs, tskv/src/kv_option.rs, tskv/src/kvcore.rs, tskv/src/memcache.rs, tskv/src/record_file/errors.rs, tskv/src/tseries_family.rs, tskv/src/tsm/reader.rs, tskv/src/tsm/tombstone.rs, tskv/src/version_set.rs
1. Call `Engine::drop_table()` when a schema provider deregisters table.
2. Cache may delete data by id.
3. File will be deleted when `ColumnFile` dropped.
`LevelInfo::push_compact_meta` didn't set a valid `ColumnFile::path` after flush.
1. Add drop_table() and drop_database() in trait `Engine`.
2. Add parameter field_ids in `MemCache::delete_data()`.3. 
3. Implements `Drop` trait for `ColumnFile`.
=> feat(drop) #567: Drop table and database, in tskv.

common/line_protocol/src/parser.rs, query_server/query/src/instance.rs, tskv/src/compaction/flush.rs, tskv/src/database.rs, tskv/src/index/db_index.rs, tskv/src/memcache.rs, tskv/src/summary.rs, tskv/src/tsm/reader.rs
For issue #590.
To simplify codes flushing cache to files.
1. Remove some iterators in flush.rs and memcache.rs.
2. Remove field `level` in `VersionEdit`.
3. Add a more simple way to calculate string width of num_cpu.
4. Add method `get_table_schema_by_series_id()` for `DataBase` and `DbIndex`.
=> Some refactors for flushing. 

tskv/src/compaction/compact.rs, tskv/src/compaction/flush.rs, tskv/src/tsm/reader.rs, tskv/src/tsm/writer.rs
Closes #440 .
- Added a temporary path generated from argument `path` in `TsmWriter::open()`, and a field `tmp_path` in `TsmWriter`.
- Rename field `path` in `TsmWriter` into `final_path`.
- Rename method `flush()` in `TsmWriter` into `finish()`, this method renames file from `tmp_path` into `final_path`.
- After `flush()` called, any other write actions to this `TsmWriter` willl make an error.
=> feat(tsm) #440: write to .tsm.tmp or .delta.tmp file first

common/protos/src/models_helper.rs, main/src/http/http_service.rs, tskv/tests/test_kvcore_interface.rs
Closes #.
I used to insert points without a timestamp for test, query `SELECT time, col from tbl` returns invalid time value now:
```
-- SQL
SELECT
DATE_BIN(INTERVAL '3 minutes', time, TIMESTAMP '1970-01-01T00:00:00Z') AS time,
tag_1 AS metric
avg(field_1) AS value
FROM ma 
GROUP BY 1, 2
-- RESULTS:
-- 1970-01-01T00:27:00.000000000,ALPHA,1.0
``` 
It's service HTTP creates line-protocol Parser using invalid default value:
```rust
let line_protocol_lines = 
line_protocol_to_lines(&lines, Local::now().timestamp_millis())
.context(ParseLineProtocolSnafu)?;
```
To fix it I changed to `timestamp_nanos()`
```rust
let line_protocol_lines = 
line_protocol_to_lines(&lines, Local::now().timestamp_nanos())
.context(ParseLineProtocolSnafu)?;
```
=> fix(write): change default time unit from mills to nanos

main/src/main.rs, main/src/signal.rs, tskv/src/error.rs, tskv/src/kvcore.rs, tskv/src/wal.rs
When we press Ctrl+c，CnosDB service will be closed with serial background services, but `WalManager::close()` is forgot, it made a truncated wal entry in the last wal file.
This PR aims to fix some bugs caused by the above situation.
1. fix: wal write not fsync-ed after received a sigint.
2. fix: ignore truncated entry in wal file, not panic.
3. fix: create `WalManager` twice in kvcore.
4. improve: print some tips after received a SIGINT.
=> Fixes some bugs among wal

.gitignore, Cargo.toml, client/Cargo.toml, common/datafusion_dep/Cargo.toml, common/datafusion_dep/src/lib.rs, common/http_protocol/Cargo.toml, common/line_protocol/Cargo.toml, common/mem_allocator/Cargo.toml, common/metrics/Cargo.toml, common/models/Cargo.toml, common/protos/Cargo.toml, common/trace/Cargo.toml, config/Cargo.toml, e2e_test/Cargo.toml, main/Cargo.toml, query_server/query/Cargo.toml, query_server/spi/Cargo.toml, query_server/test/Cargo.toml, rust-toolchain, tskv/Cargo.toml, tskv/src/compaction/picker.rs, tskv/src/engine.rs, tskv/src/index/db_index.rs, tskv/src/index/utils.rs, tskv/src/summary.rs
Closes #629.
All crates in workspace share the same versions of dependencies.
1. Remove crate `datafusion_dep`.
2. Move dependencies declarations from package level to workspace level.
3. To do that in step 2，upgrade rust toolchain version to `1.64`.
4. Reorder some `Cargo.toml`.
=> All crates in workspace share the same versions of dependencies.

tskv/src/index/db_index.rs, tskv/src/index/errors.rs
Closes #.
Error messages are not clear enough such as #735, so added detail message for IndexError::FieldType.
=> chore: add detail message fot IndexError::FieldType

.github/actions/setup-builder/action.yaml, .github/workflows/makefile.yml, Cargo.toml, common/models/src/field_info.rs, common/models/src/points.rs, common/models/src/series_info.rs, common/models/src/tag.rs, common/protos/build.rs, docs/quick-start-cn.md, docs/quick-start.md, tskv/src/database.rs, tskv/src/index/db_index.rs, tskv/src/kvcore.rs, tskv/src/memcache.rs
Closes #.
The old version of flatbuffers has some problems: **Generated code can read and write out of bounds in safe code**.
See this [rustsec link](https://rustsec.org/advisories/RUSTSEC-2021-0122.html) or [Github Issue](https://github.com/google/flatbuffers/issues/6627).
Note that flatbuffers now uses flatbuffers::Vector instead of slices in generated models.
=> Update flatbuffers to 22.9(resolved RUSTSEC-2021-0122)

Makefile, tskv/src/context.rs, tskv/src/database.rs, tskv/src/kvcore.rs, tskv/src/summary.rs, tskv/src/tseries_family.rs, tskv/src/version_set.rs, tskv/src/wal.rs
Closes #.
Field `seq_no` in TsFamily that means: "the last write request sequence number that flushed to disk".
Whenever some summary of a ts family wrote, a new version generated, I added a logic that get the minimum seq_no of ts families in a database, then get the minimal seq_no of databases in version set.
When roll wal file to write, compare the min_seq_no in version set with old wal files, delete wal files which file_id is less than min_seq_no in version set.
=> feat(wal): Automatic remove wal files

common/lru_cache/src/lib.rs, common/protos/src/models_helper.rs, meta/singleton.sh, tskv/src/compaction/check.rs, tskv/src/compaction/compact.rs, tskv/src/compaction/flush.rs, tskv/src/compaction/iterator.rs, tskv/src/compaction/job.rs, tskv/src/compaction/mod.rs, tskv/src/compaction/picker.rs, tskv/src/kvcore.rs, tskv/src/memcache.rs, tskv/src/tseries_family.rs, tskv/src/tsm/mod.rs, tskv/src/tsm/reader.rs, tskv/src/tsm/writer.rs, tskv/src/wal.rs
Closes #.
There is a bug in compaction when input data is like this:
```
File#1: { FieldId: 1, Ts: [1, 2, ..., 900] }, { FieldId: 2, ...}
File#2: { FieldId: 0, ... }, { FieldId: 1, Ts: [901, 902, ..., 1100], {FieldId: 2, ...} }
```
Unfortunately, when File#2 has a field FieldId(0) before FieldId(1) which is the next merging field id group (by current incorrect logic, the correct next merging field id should be FieldId(0) ), compaction logic generated unexpected result when group FieldIds from File#1 and File#2.
Now incorrectly generated data is like this:
```
...
============================================================
Offset: 824538 | Field | FieldId: 1, FieldType: Float, BlockCount: 4, MinTime: 1  MaxTime: 1100  PointsCount: 2200 …
```
=> fix(tskv): Query select count(1) return incorrect value.

config/Cargo.toml, config/config.toml, config/config_31001.toml, config/config_32001.toml, config/src/bytes_num.rs, config/src/duration.rs, config/src/lib.rs, main/src/main.rs, meta/src/meta_admin.rs, meta/src/meta_manager.rs
Closes #.
You can use "number + unit" instead of a number to specify a byte number item.
Units are case-insensitive, you can use '1KiB' or '1kib' to get a value that equal to 1024.
- `b` | Empty Unit: bytes
- `kb`: kilobytes (aka 1000 bytes)
- `mb`: megabytes
- `gb`: gigabytes
- `k` | `kib`: kibibytes (aka 1024 bytes)
- `m` | `mib`: mebibytes
- `g` | `gib`: gibibytes
In this pr, when starting with no arguments it prints:
```
----------
Start with cli arguments:
grpc_host = ''
http_host = ''
cpu = 6
memory = 16
config = ''
sub = Run
----------
Start with default configuration:
reporting_disabled = false
[query]
max_server_connections = 10240
query_sql_limit = 16777216
write_sql_limit = 167772160
auth_enabled = false
[storage]
path = 'data/db'
max_summary_size = 134217728
base_file_size = …
```
=> feat(config): Modify config items; Change starting prints 

config/config_31001.toml, config/config_32001.toml, config/src/lib.rs, tskv/src/kv_option.rs, tskv/src/kvcore.rs, tskv/src/wal.rs
1. Added a new config type: duration, such as `"1s"`, `"1000ms"`, etc.
2. Flush WAL files to disk periodically using that duration.
3. Script `wal.rs` has too many lines, so moved it as directory `wal/`, split into `mod.rs`, `reader.rs`, `writer.rs`, `job.rs`.
4. Close background tasks using `CancellationToken`, instead of a pair of broadcast channels.
5. Close background tasks concurrently. 
```toml
[wal]
enabled = true
path = 'data/wal'
sync = false
sync_interval = "0" # h, m, s
```
=> feature: periodically fsync wal files

query_server/test/src/case.rs, query_server/test/src/db_result.rs, query_server/test/src/main.rs
Closes #.
For example, if the 17th query in test case `timestamp` returned an error, it prints:
```
====================
Case: timestamp [17]
--------------------
explain select fa from test_timestamp_conv where time >= '1997-01-31 09:26:56';
--------------------
4   |    | -  Filter: test_timestamp_conv.time >= TimestampNanosecond(854702816000000000, None)
5   |    | -    TableScan: test_timestamp_conv projection=[time, fa], partial_filters=[test_timestamp_conv.time >= TimestampNanosecond(854702816000000000, None)]"
|4   | +  TableScan: test_timestamp_conv projection=[time, fa], full_filters=[test_timestamp_conv.time >= TimestampNanosecond(854702816000000000, None)]"
7   |    | -  CoalesceBatchesExec: target_batch_size=8192
8   |    | -    FilterExec: time@0 >= 854702816000000000
9   | …
```
=> feat(test): integration test prints more details.

Cargo.lock, Cargo.toml, common/trace/Cargo.toml, common/trace/src/lib.rs, config/config_31001.toml, config/src/lib.rs, main/src/main.rs, meta/config/config_21001.toml, meta/config/config_21002.toml, meta/config/config_21003.toml, meta/src/bin/main.rs, meta/src/store/config.rs
1. In order to collect task data from Tokio, the tokio_unstable cfg must be enabled. for example, you could build your project with
```shell
RUSTFLAGS="--cfg tokio_unstable" cargo build
```
or add the following to your `.cargo/config.toml` file:
```toml
[build]
rustflags = ["--cfg", "tokio_unstable"]
```
For more information on the appropriate location of your .cargo/config.toml file, especially when using workspaces, see the [console-subscriber readme](https://github.com/tokio-rs/console/blob/main/console-subscriber/README.md#enabling-tokio-instrumentation).
2. Under the configuration file log entry, add tokio_trace
```toml
[log]
level = 'info'
path = '/tmp/cnosdb/1001/log'
tokio_trace = { addr = "127.0.0.1:6669" }
```
3. Run tokio-console
```shell
cargo install --locked tokio-console …
```
=> improve: add tokio trace

common/models/src/predicate/domain.rs, coordinator/src/reader.rs, coordinator/src/service.rs, main/src/rpc/tskv.rs, query_server/query/src/extension/physical/plan_node/aggregate_filter_scan.rs, query_server/query/src/extension/physical/plan_node/tskv_exec.rs, tskv/src/engine.rs, tskv/src/engine_mock.rs, tskv/src/iterator.rs, tskv/src/kvcore.rs
The `struct TskvTableSchema` in `struct QueryOption` already holds the Tenant name, so the `tenant` field can be deleted
=> refactor: remove tenant of query option

common/models/src/predicate/transformation.rs, query_server/test/cases/dql/filter_push_down.result, query_server/test/cases/dql/filter_push_down.sql
Closes #1007 .
```shell
database0 ❯ CREATE TABLE m0(f0 DOUBLE , TAGS(t0, t1, t2));
Query took 0.013 seconds.
database0 ❯ INSERT m0(TIME, t0, f0) VALUES(CAST (2332186730629652317 AS TIMESTAMP), 'm>', -1321451580);
+------+
| rows |
+------+
| 1    |
+------+
database0 ❯  SELECT *
FROM m0
WHERE NOT (NOT (m0.t1 NOT IN (NULL, '''!ୋx85dc4')))
UNION ALL
SELECT ALL *
FROM m0
WHERE NOT (NOT (NOT (m0.t1 NOT IN (NULL, '''!ୋx85dc4'))))
UNION ALL
SELECT *
FROM m0
WHERE (NOT (NOT (m0.t1 NOT IN (NULL, '''!ୋx85dc4')))) IS NULL;
+-------------------------------+----+----+----+-------------+
| time                          | t0 | t1 | t2 | f0          |
+-------------------------------+----+----+----+-------------+
| 2043-11-26T21:38:50.629652317 | m> |    |    | -1321451580 | …
```
=> fix: prevent push down binary operator with null

query_server/test/cases/dml/copy_into/copy_into_table.result, tskv/src/compute/count.rs
Closes #.
If we have inserted data as below:
| time | ta | fa |
| - | - | - |
| 1 | a1 | 1 |
| 1 | a2 | 1 |
| 2 |  a1 | 1  |
Column `ta` is the Tag column that comes out with two series, 'a1' and 'a2'. 'a1' has two time(1, 2), 'a2' has one time(1).
Then use this sql statement:
```sql
select count(*) from tab.
```
`count(*)` means `count(time)`, in the past we calculate the count of distinct time over all series, so we got 2.
now we calculate the sum of the count of each series, so we got 3.
**Before**
=> feat(tskv): counting by sreies return sum of each count(series_id)

common/models/src/errors.rs, common/models/src/predicate/domain.rs
Closes #.
1. "422 Unprocessable Entity, details: {\"error_code\":\"050007\",\"error_message\":\"Error from models: Invalid query expr message: key must be a string\"}"
2. "grpc client request error: grpc status: status: Internal, message: \\\"Invalid query expr message: decode ==error invalid type: sequence, expected This Visitor expects to receive Marker
=> fix: Marker Deserialize & QueryExpr encode use bincode

tskv/src/compaction/check.rs, tskv/src/compaction/flush.rs, tskv/src/compaction/job.rs, tskv/src/context.rs, tskv/src/database.rs, tskv/src/kvcore.rs, tskv/src/memcache.rs, tskv/src/summary.rs, tskv/src/tseries_family.rs, tskv/src/version_set.rs
Closes #864 .
- Remove `flushed` state in cache.
- Make `flushing` state in cache an `AtomicBool`, use `compare_and_exchange` to change in current thread.
- Before TseriesFamily's replace version, drop flushed memory caches from new super version.
- `CacheGroup::read_field_data()` and `CacheGroup::read_series_timestamps()` do not check state.
- `run_flush_memtable_job()` built a `HashMap` maps`TseriesFamilytId` to `Vec<MemCache>`, now send that map by `SummaryTask`.
- `TseriesFamily::flush_req()` -> `TseriesFamily::build_flush_req()`
- `Summary::write_summary(version_edits, file_metas)` -> `Summary::write_summary(version_edits, file_metas, mem_caches)`
- `SummaryTask::new(version_edits, file_metas, call_back)` -> `SummaryTask::new(version_edits, file_metas, mem_caches, call_back)`
=> fix(#864): vnode drop flushed caches during the new super version installation

query_server/query/src/data_source/sink/mod.rs, query_server/query/src/data_source/sink/obj_store/mod.rs, query_server/query/src/data_source/sink/obj_store/serializer/csv.rs, query_server/query/src/data_source/sink/obj_store/serializer/json.rs, query_server/query/src/data_source/sink/obj_store/serializer/parquet.rs
Closes #1034 .
The current pr limits the size of the exported file
Premise: the batch_size of RecordBatch in the stream meets expectations @zipper-meng
=> fix: limit the size of exported files

tskv/src/context.rs, tskv/src/kvcore.rs, tskv/src/summary.rs, tskv/src/wal.rs
Closes #.
Now recovering WAL is from a **seq_no** `GlobalContext::last_seq()` which means the sequence number of the latest persisted write request to a Vnode records in summary file, in other words, the  maximum **seq_no** among all Vnodes of all databases, so all write requests to Vnodes flushed earlier with seq_no less than that  **seq_no** was losed.
Now we get the **seq_no** by `GlobalSequenceContext::min_seq()` which means the minimum sequence number of persisted write request of all Vnodes in all Databases.
Also, get the `HashMap` that maps vnode-id to vnode-`last_seq`s. When recovering WAL, get vnode-id and `seq` from each write requests, if `seq` is less than `last_seq`, ignore the write request.
=> fix(recover): Vnodes flushed earlier lose data in recovering

Cargo.lock, common/models/Cargo.toml, common/models/src/errors.rs, common/models/src/meta_data.rs, meta/src/model/meta_admin.rs
Closes #.
The crate `sys_info` only gives`disk_info()` which will return disk info about the current volume.
On windows version it does not give `GetDiskFreeSpace` the target path.
```c
// sys-inf-0.9.1 c::windows.c
DiskInfo get_disk_info(void) {
DWORD cluser, sector, free, total;
double tmp;
DiskInfo di;
v Here is the parameter.
if (GetDiskFreeSpace(NULL, &cluser, &sector, &free, &total)) {
tmp = cluser * sector;
di.total = tmp * total / 1024;
di.free = tmp * free / 1024;
} else {
di.total = 0;
di.free = 0;
}
return di;
}
```
=> feat(win32): add windows versoin for meta_data::get_disk_info

tskv/src/compaction/flush.rs, tskv/src/compaction/job.rs, tskv/src/summary.rs, tskv/src/tsm/block.rs, tskv/src/tsm/reader.rs, tskv/src/tsm/writer.rs
Closes #.
- feat(tskv): fix flush set the wrong `CompactMeta::level`.
- Decrease vector allocates in flushing.
There are two fields which means the level of files: `level` and `is_delta`，now it set the wrong level:
https://github.com/cnosdb/cnosdb/blob/e48dab9676fe65ac5347a9f269ac216f84a7de5b/tskv/src/compaction/flush.rs#L314-L337
After flush, files are written to the correct directory `$vnode_id/delta/`, but the summary saved the wrong `CompactMeta::level`, so CnosDB tries to load these files in the wrong directory `$vnode_id/tsm/`.
This PR may fix issue #1040 .
=> feat(tskv): fix flush set the wrong CompactMeta::level

Cargo.lock, client/Cargo.toml, client/src/ctx.rs, client/src/main.rs, common/http_protocol/src/header.rs, main/src/flight_sql/auth_middleware/basic_call_header_authenticator.rs, main/src/flight_sql/flight_sql_server.rs, main/src/flight_sql/utils.rs, main/src/http/header.rs, main/src/http/http_service.rs, query_server/spi/src/query/execution.rs, query_server/spi/src/server/dbms.rs
1. cli option
```
--private-key-path <PRIVATE_KEY_PATH>
Rsa private key path for key pair authentication used to connect to the CnosDB
```
2. http header
|  key   | value |
|  ----  | ----  |
| X-CnosDB-PrivateKey | 用于连接CnosDB的密钥对认证的rsa私钥内容（base64编码后） |
Closes #.
=> fix: add private key to request header and cli options

meta/src/store/state_machine.rs, query_server/sqllogicaltests/cases/ddl/user.slt
fix can not repeatedly modify existing user options
Closes #.
=> fix: alter non-null user options

tskv/src/compaction/flush.rs, tskv/src/compaction/job.rs, tskv/src/compaction/mod.rs, tskv/src/context.rs, tskv/src/database.rs, tskv/src/kvcore.rs, tskv/src/summary.rs, tskv/src/tseries_family.rs, tskv/src/version_set.rs, tskv/src/wal.rs
Fixes:
1. `GlobalSequenceContext` sometimes not properly set when recover.
2. `VersionEdit::seq_no` not set when creating `TseriesFamily` or rolling a summary file.
3. Check to delete wal files after `flush_trigger_total_file_size` triggered.
=> fix(tskv): old wal files may not be deleted

query_server/query/src/extension/analyse/transform_gapfill/mod.rs, query_server/query/src/extension/analyse/transform_time_window.rs, query_server/query/src/extension/expr/mod.rs, query_server/query/src/extension/expr/window/mod.rs, query_server/query/src/extension/expr/window/time_window.rs, query_server/query/src/extension/logical/plan_node/gapfill.rs, query_server/query/src/extension/physical/plan_node/gapfill/algo.rs, query_server/query/src/extension/physical/plan_node/gapfill/mod.rs, query_server/query/src/extension/physical/plan_node/gapfill/params.rs, query_server/query/src/extension/physical/transform_rule/gapfill.rs, query_server/sqllogicaltests/cases/function/gapfill.slt
gap filling function supports sliding window
reuse time window
```
time_window_gapfill(<time column>, <window interval>, <sliding interval>, <start time>): <time window struct>
```
**time column**: Columns of type timestamp 
**window interval**: The size of the window, interval type
**sliding interval**: The moving distance of the window, interval type. When the moving distance is equal to the window size, it is a tumbling window, otherwise it is a sliding window
**start time**: When the window starts to calculate, default to unix EPOCH
Supported interpolation methods are consistent with tumbling window
> Note: The number of overlapping windows cannot be greater than 100
link: https://github.com/cnosdb/cnosdb/pull/1149
Closes #.
=> feat: support sliding window gap filling

Cargo.lock, e2e_test/Cargo.toml, e2e_test/src/flight_sql.rs, e2e_test/src/lib.rs, main/src/flight_sql/flight_sql_server.rs, query_server/query/src/metadata/information_schema_provider/builder/tables.rs, query_server/sqllogicaltests/src/instance.rs, query_server/test/cases/ddl/create_stream_table.result, query_server/test/cases/dml/explain/explain_stream_query.result, query_server/test/cases/sys_table/information_schema/tables.result
implement `get_flight_info_catalogs/get_flight_info_schemas/get_flight_info_tables/get_flight_info_table_types`
Closes #1174 .
=> feat: support metadata api for flight sql

common/models/src/meta_data.rs, common/models/src/node_info.rs, coordinator/src/reader/query_executor.rs, coordinator/src/service.rs, coordinator/src/vnode_mgr.rs, coordinator/src/writer.rs, main/src/http/http_service.rs, main/src/http/response.rs, main/src/rpc/tskv.rs, meta/src/client.rs, meta/src/model/meta_client.rs, meta/src/model/meta_client_mock.rs, meta/src/model/mod.rs, meta/src/store/command.rs, meta/src/store/state_machine.rs, query_server/query/src/sql/parser.rs, tskv/src/compaction/check.rs, tskv/src/compaction/job.rs, tskv/src/database.rs, tskv/src/engine_mock.rs, tskv/src/file_utils.rs, tskv/src/kv_option.rs, tskv/src/kvcore.rs, tskv/src/lib.rs, tskv/src/summary.rs, tskv/src/tseries_family.rs
Closes #1151 #1160
Add `status: VnodeStatus` to `TseriesFamily`.
```rust
pub enum VnodeStatus {
Running,
Copying,
}
```
- `Running`: the default state.
- `Copying`: prevent vnode writing points and compaction.
Add `status: VnodeStatus` to `VnodeInfo` and `VnodeAllInfo`.
Add command `WriteCommand::UpdateVnode` in meta state machine, to change meta data `VnodeInfo::status`.
Add `Cordon` to `NodeStatus`, now it doesn't works, we can ignore it.
1. Generate new Vnode id.
2. Change vnode status in meta data `VnodeInfo` to `VnodeStatus::Copying`.
3. Transfer Vnode files to the destination node.
4. Fetch old Vnode summary.
5. Apply old Vnode summary to the destination node.
6. Change vnode status in meta data `VnodeInfo` to `VnodeStatus::Running`.
- For the **index** files, downlaod to …
=> fix move vnode

coordinator/src/hh_queue.rs, main/src/server.rs
Closes #.
Remove TLS support in gRPC server, because coordinator does not support that.
=> fix(server): remove tls support on grpc server

common/models/src/schema.rs, tskv/src/compaction/compact.rs, tskv/src/compaction/flush.rs, tskv/src/compaction/job.rs, tskv/src/compute/count.rs, tskv/src/kvcore.rs, tskv/src/summary.rs, tskv/src/wal.rs
Uncertainly, but lower probability: #1141
1. Fix some typos.
2. Fix logs print when file created or write finished in compaction and flushing.
3. Prevent too frequently flush job executions invoked from WAL total size checking.
4. Prevent too many old compact requests stack in the compact channel (the previous compaction sometimes costs more than 1 minute).
- When a new file created in flush/compaction:
```
Flush/Compaction: File: {} been created (level={}).
```
- When a file write finished in flush/compaction:
```
Flush/Compaction: File: {} write finished (level: {}, {} B).
```
A force flush job will be invoked when the total file size of WALs is too large (by default the max file size is 2G), if the flush job lasted over the check interval, it starts the second flush job unnecessarily. …
=> Feature: TSKV Optimizations to reduce the memory usage.

common/protos/proto/kv_service.proto, common/protos/src/generated/protobuf_generated/kv_service.rs, coordinator/src/errors.rs, coordinator/src/lib.rs, coordinator/src/service.rs, coordinator/src/service_mock.rs, main/src/rpc/tskv.rs, meta/src/model/meta_client.rs, meta/src/model/meta_client_mock.rs, meta/src/model/mod.rs, query_server/query/src/execution/ddl/alter_tenant.rs, query_server/query/src/execution/ddl/checksum_group.rs, tskv/src/compaction/check.rs, tskv/src/database.rs, tskv/src/engine_mock.rs, tskv/src/kvcore.rs, tskv/src/lib.rs, tskv/src/memcache.rs
This PR implements admin query statement `CHECKSUM GROUP <replication_set_id>`.
Feature group in #806 .
Add a command to print the root level check sum (formatted `[u8; 32]`) of Vnodes in  a replication set.
```
public ❯ create database dba with replica 2;
public ❯ \c dba
dba ❯ create table ma(fa double, tags(ta));
dba ❯ create table mb(fb double, tags(tb));
dba ❯ insert into ma(time,ta,fa) values('2023-05-01 00:00:00', 'a1', 1);
dba ❯ insert into ma(time,ta,fa) values('2024-05-01 00:00:00', 'a1', 1);
dba ❯ insert into mb(time,tb,fb) values('2023-05-01 00:00:00', 'a1', 1);
dba ❯ insert into mb(time,tb,fb) values('2024-05-01 00:00:00', 'a1', 1);
dba ❯ checksum group 9;
+----------+------------------------------------------------------------------+
| VNODE_ID | CHECK_SUM …
```
=> feat(query): implement CHECKSUM GROUP <replication_set_id>

common/models/src/auth/user.rs, meta/src/store/state_machine.rs, query_server/query/src/sql/planner.rs, query_server/spi/src/query/logical_planner.rs, query_server/sqllogicaltests/cases/ddl/user.slt, query_server/test/cases/dcl/alter_user.result, query_server/test/cases/dcl/alter_user.sql, query_server/test/cases/sys_table/cluster_schema/users.result
Closes #1210 .
1. admin权限分为两种
- 初始的admin权限（可在系统表cluster_schema.users中查看，
- 被授予的admin权限（可在系统表cluster_schema.users中查看，
2. 支持拥有admim权限的人将admin权限授予其他人
3. 系统表cluster_schema.users中is_admin字段标记是否拥有admin权限（包括初始的和被授予的）
4. 系统表cluster_schema.users中的user_options的granted_admin为true，表示被授予的admin权限
5. 拥有admin权限的人可以回收其他人被赋予的admin权限
6. 初始的admin权限不会被回收
**授予admin权限**
```sql
alter user <user_name> set granted_admin = true
```
**撤销admin权限**
```sql
alter user <user_name> set granted_admin = false
```
**查看admin权限**
```sql
select * from cluster_schema.users;
```
=> feat: support granting admin privilege

config/src/lib.rs
If we add a new TOML table in our configuration, then it will failed to parse the old version of config-file because it does not contains the TOML talbe key.
=> fix(config): failed to parse str with missing toml table key

Cargo.lock, client/src/ctx.rs, client/src/lib.rs, client/src/main.rs, common/http_protocol/Cargo.toml, common/http_protocol/src/http_client.rs, common/http_protocol/src/lib.rs, e2e_test/src/http_api_tests.rs, main/Cargo.toml
Related #.
Add HTTPS support for `cnosdb-cli` .
- `--ssl` - use `https://{host}:{port}` as request url.
- `--unsafe-ssl` - allow unsafe HTTPS connections.
- `--cacert <FILE>` - add root certificate from a file.
=> feat(client): add https support for cnosdb-cli

common/models/src/predicate/domain.rs, tskv/src/compaction/check.rs, tskv/src/compaction/compact.rs, tskv/src/compaction/picker.rs, tskv/src/compute/count.rs, tskv/src/error.rs, tskv/src/kv_option.rs, tskv/src/summary.rs, tskv/src/tseries_family.rs, tskv/src/tsm/block.rs, tskv/src/tsm/index.rs, tskv/src/tsm/writer.rs
Related #.
The past compaction costs too much RAM because it decodes all data blocks that going to merge together and then starts merge. Now compaction decodes them and merge one by one in a loop. 
The new style of compaction changed it's API so checksum statement won't work. I'm now working to re-enable checksum.
- Level-4 has less possibility to be picked.
- Stop picking if total size of picked files exceed configured `max_compact_size`.
- Keep the last file picked even if picked files exceed the configurated `max_compact_size` after picked the last file.
- Reset the weight to calculate a score.
- Delete some code that not used in `picker.rs`.
- Add `CompactingBlockMetaGroup` to group data block meta data that should be merged. It has method `merge` to load and merge data blocks from …
=> Fix: compaction may costs too much memory

common/lru_cache/src/cache.rs, tskv/src/database.rs
Related #.
And when insert an existing key to LRU cache, subtract old entry entry-charge and add the new charge
=> Fix: add-tsfamily uses config max_cached_readers

meta/src/model/meta_client.rs, meta/src/store/command.rs, meta/src/store/state_machine.rs, query_server/sqllogicaltests/cases/ddl/user.slt, tskv/src/database.rs
fixed #1218 
```
public ❯ drop table abc;
422 Unprocessable Entity, details: {"error_code":"030019","error_message":"Table not found: \"abc\""}
```
=> fixed issues 1218

common/models/src/meta_data.rs
Related #1266.
Fix build errors on linux.
use `statfs::f_bavail` instad of `statfs::f_bfree`.
=> fix(linux): libc::statfs use libc::c_char to fix compile error on linux

Cargo.lock, Cargo.toml, common/models/Cargo.toml, common/models/src/meta_data.rs, meta/src/model/meta_admin.rs, query_server/sqllogicaltests/src/main.rs, query_server/sqllogicaltests/src/os/mod.rs, query_server/sqllogicaltests/src/os/unix.rs, query_server/sqllogicaltests/src/os/windows.rs
Related #.
A lot of errors in crate `sqllogicaltest` when I run `make clippy_test` on windows11. 
Get disk_info by path returns `The system cannot find the path specified. (os error 3)`.
- Add module `os::unix` and `os::windows`.
- Add code for windows platform to avoid **unused** warnings.
- Use crate `windows` persented by microsoft to get disk_info;
=> fix(test): clippy warnings & get_disk_info on windows11

query_server/test/cases/ddl/cli_precision.result, query_server/test/cases/ddl/cli_precision.sql, tskv/src/query_iterator/iterator.rs
Related #1274 .
1. `RowIterator` set wrong parallel task number.
2. `RowIterator` finished too early, some data not loaded.
1. `series_group_num` is the minimum value of `cpu_num` and  `series_len`
2. Swap variable name of `series_group_num` and `series_group_size`.
3. When reset `FIeldFIleLocation::intersected_time_ranges`, also reset `FIeldFIleLocation::self.intersected_time_ranges_i`.
1. Add some comments.
4. Rename some variables.
=> fix(query): fix row_iterator finished too early

tskv/benches/snafu_bench.rs, tskv/src/compaction/check.rs, tskv/src/error.rs, tskv/src/file_system/file_manager.rs, tskv/src/index/binlog.rs, tskv/src/record_file/reader.rs, tskv/src/record_file/writer.rs, tskv/src/tseries_family.rs, tskv/src/tsm/tombstone.rs, tskv/src/wal.rs
Related #.
I thought methods in `FileManager` has something wrong.
- `open_file` also create the file if not exists.
- Some `Error` instanced too early.
1. Methods in file manager has it's own function:
- `open_file`: Open a file to read.
- `create_file`: Open or create a file to read & write, overwrite if exists.
- `open_create_file`: Open or create a file to read & write, append if exists.
2. Some unit test doesn't clean it's directory since last run.
- change `remote_dir()` to `remove_dir_all()`.
=> fix(fs): normalize file manager API: distinguishing read,write,create

common/models/src/arrow/stream.rs
Related #1303  .
this maybe fix `async fn` resumed after completion
=> fix: being polled after read stream exception

common/trace/src/lib.rs, main/src/flight_sql/flight_sql_server.rs
Because the `do_put_prepared_statement_update` of the `flight sql server` was not implemented before, the sql cannot be executed when using arrow-fligh-jdbc.
=> improve: implement flight sql do_put_prepared_statement_update

common/protos/src/models_helper.rs, common/trace/src/lib.rs, meta/src/bin/main.rs, tskv/benches/kvcore_bench.rs, tskv/src/database.rs, tskv/src/engine_mock.rs, tskv/src/error.rs, tskv/src/file_utils.rs, tskv/src/kvcore.rs, tskv/src/lib.rs, tskv/src/memcache.rs, tskv/src/record_file/mod.rs, tskv/src/schema/error.rs, tskv/src/schema/schemas.rs, tskv/src/wal/mod.rs, tskv/src/wal/reader.rs, tskv/src/wal/writer.rs, tskv/tests/test_kvcore_interface.rs
Related #1178, but has some differences.
- Simplify WAL write api in `kvcore.rs`
- Store `drop_table` and `remove_tsfamily` in WAL files.
- Recovering tskv from WAL `write` will not create database schemas, and if database&table&tsfamily of a WAL record does not exist in tskv, this WAL record will be ignored.
- Recovering tskv from WAL `drop_table` or `remove_tsfamily` will not do anything, because WAL `write` that schema not existed in tskv was ignored.
Here is the newest schema of the record data in WAL file:
```
+------------+------------+------------+------------+--------------+-----------------+-----------+
| 0: 1 byte  | 1: 8 bytes | 9: 4 bytes | 13: 1 byte | 14: 8 bytes  | 22: tenant_size |  n bytes  |
+------------+------------+------------+------------+--------------+------------- …
```
=> [Feature] Recovering WAL records will not add schema to tskv; stores `drop_table` & `remove_tsfamily` in WAL

query_server/query/benches/aggregate_function.rs, query_server/query/src/extension/expr/aggregate_function/mod.rs, query_server/query/src/extension/expr/aggregate_function/state_agg/mod.rs, query_server/query/src/extension/expr/aggregate_function/state_agg/state_agg_accumulator.rs, query_server/query/src/extension/expr/aggregate_function/state_agg/state_agg_data.rs, query_server/query/src/extension/expr/expr_utils.rs, query_server/query/src/extension/expr/scalar_function/duration_in.rs, query_server/spi/src/lib.rs, query_server/sqllogicaltests/cases/function/state_agg/duration_in.slt, query_server/sqllogicaltests/cases/function/state_agg/state_agg.slt
=> feat: support state_agg and duration_in for state_agg

Cargo.lock, tskv/Cargo.toml, tskv/src/error.rs, tskv/src/record_file/reader.rs, tskv/src/record_file/writer.rs, tskv/src/summary.rs, tskv/src/tsm/codec/boolean.rs, tskv/src/tsm/codec/float.rs, tskv/src/tsm/codec/integer.rs, tskv/src/tsm/codec/string.rs, tskv/src/tsm/codec/timestamp.rs, tskv/src/tsm/codec/unsigned.rs, tskv/src/tsm/tombstone.rs, tskv/src/wal/reader.rs, tskv/src/wal/writer.rs
Related #.
Encoders now do not clear the distant buffer.
- Remove async_recursion.
- When there is an error, return that error instead of continue trying to read the next record.
- Add two possible errors: `RecordFileInvalidDataSize` and `RecordFileHashCheckFailed`.
- `set_pos(pos)` - Return `Error::Eof` instead of `Error::InvalidParam` if pos > file length
- `find_record_header()` - Do not call `set_pos(header_pos)`.
- `load_buf()` - Do not truncate `Reader::buf` when read to end.
- `read_buf(size)` - When …
=> refactor(tskv): record_file & codec

common/models/src/gis/data_type.rs, common/models/src/gis/mod.rs, common/models/src/lib.rs, common/models/src/schema.rs, common/models/src/value_type.rs, common/protocol_parser/src/lines_convert.rs, query_server/query/src/prom/time_series/writer.rs, query_server/query/src/sql/parser.rs, query_server/query/src/sql/planner.rs, query_server/spi/src/lib.rs, query_server/spi/src/query/logical_planner.rs, query_server/test/cases/ddl/create_table.result, tskv/src/compaction/compact.rs, tskv/src/compaction/flush.rs, tskv/src/memcache.rs, tskv/src/reader/iterator.rs, tskv/src/reader/mod.rs, tskv/src/schema/schemas.rs, tskv/src/tsm/block.rs, tskv/src/tsm/index.rs, tskv/src/tsm/reader.rs
=> feat: support Geometry data type

common/models/src/predicate/domain.rs, common/models/src/predicate/transformation.rs, query_server/test/cases/data_type/type_conversion/timestamp.result
=> push_down_ne

Cargo.lock, Cargo.toml, common/models/src/gis/data_type.rs, common/models/src/schema.rs, query_server/query/Cargo.toml, query_server/query/src/data_source/mod.rs, query_server/query/src/data_source/sink/obj_store/mod.rs, query_server/query/src/data_source/sink/tskv.rs, query_server/query/src/data_source/write_exec_ext/external_table.rs, query_server/query/src/extension/expr/scalar_function/gis/mod.rs, query_server/query/src/extension/expr/scalar_function/gis/st_asbinary.rs, query_server/query/src/extension/expr/scalar_function/gis/st_distance.rs, query_server/query/src/extension/expr/scalar_function/gis/st_geomfromwkb.rs, query_server/query/src/extension/expr/scalar_function/mod.rs, query_server/query/src/extension/physical/optimizer_rule/add_assert.rs, query_server/query/src/extension/physical/optimizer_rule/mod.rs, query_server/query/src/extension/physical/plan_node/assert/geom_write.rs, query_server/query/src/extension/physical/plan_node/assert/mod.rs, query_server/query/src/extension/physical/plan_node/mod.rs, query_server/query/src/extension/physical/plan_node/table_writer.rs, query_server/query/src/prom/time_series/writer.rs, query_server/query/src/sql/physical/planner.rs, query_server/query/src/sql/planner.rs, query_server/spi/src/lib.rs, query_server/sqllogicaltests/cases/function/gis/check_write.slt, query_server/sqllogicaltests/cases/function/gis/setup.slt, query_server/sqllogicaltests/cases/function/gis/st_asbinary.slt, query_server/sqllogicaltests/cases/function/gis/st_distance.slt, query_server/sqllogicaltests/cases/function/gis/st_geomfromwkb.slt
=> support gis function

config/src/limiter_config.rs, coordinator/src/reader/mod.rs, coordinator/src/service.rs, meta/src/limiter/limiter_kind.rs, meta/src/limiter/local_request_limiter.rs, meta/src/limiter/mod.rs, meta/src/limiter/none_limiter.rs, meta/src/limiter/remote_request_limiter.rs, meta/src/model/meta_admin.rs, query_server/test/cases/sys_table/cluster_schema/tenants.result, query_server/test/cases/sys_table/cluster_schema/tenants.sql
Closed #1481 
Related #1480 
Yes, configuration file configuration item naming needs to be changed.
=> refactor: rename coordinator limiter

tskv/src/kvcore.rs, tskv/src/wal/mod.rs
=> fix : restart lose data

Cargo.lock, main/Cargo.toml
Related #.
To start CnosDB using cargo, now we should use command:
```sh
cargo run --bin cnosdb -- run -M singleton --config ./config/config_8902.toml
```
After add `project.default-run` for crate **main**, we can use command:
```sh
cargo run -- run -M singleton --config ./config/config_8902.toml
```
=> [Refactor(cargo)] Add default-run=cnosdb in Cargo.toml of crate main

query_server/query/src/dispatcher/manager.rs, query_server/query/src/execution/ddl/create_external_table.rs, query_server/query/src/execution/factory.rs, query_server/query/src/extension/mod.rs, query_server/query/src/extension/variable/mod.rs, query_server/query/src/extension/variable/server_version.rs, query_server/query/src/instance.rs, query_server/query/src/lib.rs, query_server/query/src/metadata/mod.rs, query_server/query/src/sql/analyzer.rs, query_server/query/src/sql/logical/optimizer.rs, query_server/query/src/sql/physical/planner.rs, query_server/query/src/sql/planner.rs, query_server/query/src/variable/mod.rs, query_server/query/src/variable/simple_sys_var_manager.rs, query_server/spi/src/query/execution.rs, query_server/spi/src/query/mod.rs, query_server/spi/src/query/session.rs, query_server/spi/src/query/variable.rs, query_server/sqllogicaltests/cases/variable/server_version.slt
Related #1660 .
- implement framework for adding system variables
- add built-in system variable @@server_version
[//]: # (There is no need to duplicate the description in the issue here, but it is sometimes worth providing a summary of the individual changes in …
=> feat: implement framework for adding system variables & add var @@server_version

tskv/src/file_system/file_manager.rs, tskv/src/wal/mod.rs, tskv/src/wal/writer.rs
Related #.
1. file_manager::open_create_file() now don't use append mode, because on Windows11 we can't call file.set_len() on a file which opened with append mode.
2. Now there can be multi opened but finished WAL files in WalManager do not have footer, to fix that, split WalWriter::write_footer() from WalWriter::close(), call wirte_footer() when a WAL file is finished.
[//]: # (There is no need to duplicate the description in the issue here, but it is sometimes worth providing a summary of the individual …
=> [Fix] tskv file system do not use append flag; call WalWriter::close() when a writer roll to old

tskv/src/compaction/check.rs, tskv/src/compaction/compact.rs, tskv/tests/test_kvcore_interface.rs
#1641 
1. Restore commented code to get vnode checksum, and fit the new compaction iterator.
2. Improve implements of `std::fmt::Display` of each hash tree structs, the prints now use JSON format.
Change
=> [Feature] Restore feature `vnode checksum <group_id>`

common/models/src/meta_data.rs, common/models/src/utils.rs, config/src/cluster_config.rs, coordinator/src/errors.rs, coordinator/src/raft/manager.rs, coordinator/src/service.rs, main/src/server.rs, meta/src/client.rs, meta/src/error.rs, meta/src/model/meta_admin.rs, meta/src/service/server.rs, meta/src/store/storage.rs, meta/tests/cluster/main.rs
=> feat: start the service through configuration

meta/src/client.rs, meta/src/model/meta_admin.rs, meta/src/model/meta_tenant.rs, meta/src/service/http.rs
Related #1633 .
1. raft do not appear tow leader(split-brain), the new leader will be elected when old leader isolated ,so leader`s data aways right, we just need watch leader.
2. when a meta node failed(like: process exit), raft membership do not change until …
=> feature: support data node sense meta node change

Cargo.lock, client/src/ctx.rs, common/models/src/predicate/domain.rs, common/protos/Cargo.toml, common/protos/src/lib.rs, config/src/deployment_config.rs, coordinator/src/reader/table_scan/opener.rs, coordinator/src/reader/tag_scan/opener.rs, coordinator/src/service.rs, coordinator/src/vnode_mgr.rs, coordinator/src/writer.rs, main/src/http/mod.rs, main/src/rpc/grpc_service.rs, meta/src/model/meta_admin.rs, meta/src/store/state_machine.rs, query_server/query/src/execution/ddl/create_external_table.rs, query_server/query/src/extension/analyse/transform_bottom_func_to_topk_node.rs, query_server/query/src/extension/analyse/transform_topk_func_to_topk_node.rs, query_server/query/src/sql/planner.rs, query_server/query/tests/datafusion.rs, query_server/test/cases/ddl/create_external_table.result, query_server/test/cases/ddl/create_external_table.sql, query_server/test/cases/sys_table/cluster_schema/tenants.result, query_server/test/cases/sys_table/cluster_schema/tenants.sql, tskv/src/compaction/flush.rs
[fix: get_sys_mem unit error](https://github.com/cnosdb/cnosdb/pull/1739/commits/a7224f5c2a2223833a11312811a4943e3fbd4225)
[fix: cli write line protocol didn't show error message](https://github.com/cnosdb/cnosdb/pull/1739/commits/022e203aee8e9b21b83070e58780bbe58b7de67c)
[fix: fix when drop user don't drop tenant member](https://github.com/cnosdb/cnosdb/pull/1739/commits/a48c7899369a79c4ea15fb257cf4db21a945d534)
[fix: table name error when creating external table (](https://github.com/cnosdb/cnosdb/pull/1739/commits/adfa01c99ff521e17a2aa77143ae2768efd67d61)https://github.com/cnosdb/cnosdb/pull/1687[)](https://github.com/cnosdb/cnosdb/pull/1739/commits/adfa01c99ff521e17a2aa77143ae2768efd67d61)
[fix: fix Tenant not found return http status code …
=> [Patch] fix 2.3 bugs

query_server/query/src/execution/factory.rs, query_server/sqllogicaltests/cases/stream/unsupport_op.slt
Related #1715 .
error message:
```
{"error_code":"010005","error_message":"This feature is not implemented: Stream table can only be used as source table in insert select statements."}
```
[//]: # (There is no need to duplicate the description in the issue here, …
=> fix: optimize the error message for direct select the stream table

common/models/src/auth/user.rs, e2e_test/src/independent/restart_tests.rs, query_server/sqllogicaltests/cases/ddl/user.slt, query_server/test/cases/dcl/alter_user.result, query_server/test/cases/dcl/alter_user.sql, query_server/test/cases/sys_table/cluster_schema/users.result
Related #1757 .
The unset user options will no longer be displayed.
=> fix: incorrectly alter non-specified user options

common/models/src/meta_data.rs, common/models/src/utils.rs, config/src/cluster_config.rs, main/src/server.rs, meta/src/bin/main.rs, meta/src/client.rs, meta/src/error.rs, meta/src/model/meta_admin.rs, meta/src/store/state_machine.rs, meta/tests/cluster/main.rs
=> [LTS/2.3] feat: start the service through configuration

tskv/tests/test_kvcore_interface.rs
Related #.
Fixed by: add `#[serial]` above `test_kvcore_recover`.
=> fix: bugs when running test_kvcore_interface::test_kvcore_recover

tskv/src/compute/count.rs
Related #.
When there are too many series_ids, too many parallel tasks made counting too slow.
=> Refactor: let the maximum parallel counting task num of cpus

tskv/src/compaction/compact.rs, tskv/src/compaction/job.rs, tskv/src/tseries_family.rs, tskv/src/tsm/block.rs, tskv/src/tsm/mod.rs, tskv/src/tsm/tombstone.rs
Related #.
`CompactJobInner::enable_compaction` is initialized as `true` but the job starts only when it `compare_exchange(false, true) == Ok(false)`.
https://github.com/cnosdb/cnosdb/blob/3112894e0003a9222e1014b2b34af829916a706d/tskv/src/compaction/job.rs#L122-L134
There may be an error when chunking big blocks, this makes data lost.
Merge `tmp_tsm_blk_meta_iters: Vec<BlockMetaIterator>` and `tmp_tsm_blk_tsm_reader_idx: Vec<usize>` into `tmp_tsm_blk_meta_iters: Vec<(usize, BlockMetaIterator)>`.
Tombstone files may be removed when dropping a `ColumnFile`.
=> Fix bugs around compaction

common/http_protocol/src/encoding.rs
=> feature: add pool for HTTP content codecs

Cargo.lock, Cargo.toml, client/Cargo.toml, client/src/main.rs
=> fix: hide password when starting cli

tskv/src/compaction/compact.rs, tskv/src/tsm/block.rs
…s in CompactIterator for better performance
Related #.
There may be an error when chunking big blocks, this makes data lost.
Merge `tmp_tsm_blk_meta_iters: Vec<BlockMetaIterator>` and `tmp_tsm_blk_tsm_reader_idx: Vec<usize>` into `tmp_tsm_blk_meta_iters: Vec<(usize, BlockMetaIterator)>`.
=> Fix(2.3) bugs around compaction

tskv/src/file_system/file/cursor.rs, tskv/src/file_system/file_manager.rs, tskv/src/index/binlog.rs, tskv/src/kvcore.rs, tskv/src/record_file/writer.rs, tskv/src/tsm/writer.rs, tskv/src/wal/mod.rs, tskv/src/wal/writer.rs
=> add cache buffer for FileCursor

main/src/http/http_service.rs, query_server/query/src/execution/ddl/create_database.rs, query_server/query/src/execution/ddl/create_table.rs, query_server/test/cases/ddl/create_table.result
=> Mock influxdb

query_server/query/src/metadata/mod.rs, query_server/query/src/sql/planner.rs
fix: 'cnosdb' and other tenant check system db(#1567)
Related #.
=> fix: root user not allow change granted_admin(#1702)

common/cache/src/sharded_async_cache.rs, tskv/src/tseries_family.rs
Related #.
fix(tskv): lru cache break down in query that lead to open too many files when opening tsm reader
[//]: # (There is no need to duplicate the description in the issue here, but it is sometimes worth providing a summary of the individual changes in this …
=> Fix: LRU cache of TSM readers break down

query_server/query/src/sql/parser.rs, query_server/sqllogicaltests/cases/dcl/tenant.slt, query_server/sqllogicaltests/cases/dcl/user.slt
```
create/alter tenant/database
copyinto
```
=> feat: sqloption support space and equal(#1775)

tskv/src/compaction/compact.rs, tskv/src/compaction/delta_compact.rs, tskv/src/compaction/mod.rs, tskv/src/compaction/picker.rs, tskv/src/compute/count.rs, tskv/src/tsm/block.rs
Related #.
Data block dropped unexpectedly in this case:
| - | Block#1 | Block#2 | Block#3 |
| :-: | :-: | :-: | :-: |
| **timestamps** | 1~5 | 6~10 | 11~15 |
| **tombstones** | - | 6~10 | 11~15 |
Block#2 and Block#3 will be dropped, but Block#1 was also dropped.
- Fix some typos
- Sometimes the `CompactReq::out_time_range()` does not well  cover the picked files
=> Fix(2.3): Unexpectedly dropped block in compaction

common/models/src/predicate/domain.rs, tskv/src/compaction/compact.rs, tskv/src/compaction/delta_compact.rs, tskv/src/compaction/job.rs, tskv/src/compaction/mod.rs, tskv/src/compaction/picker.rs, tskv/src/file_system/file_manager.rs, tskv/src/tseries_family.rs, tskv/src/tsm/tombstone.rs
Related #.
- Fix some typos.
- Modifications in `TimeRanges::add_time_range`
Now it merges [(t1, t2), (t2+1, t3)] into (t1, t3), at previous it won't merge them.
- Replace method `CompactReq::out_time_range()` to field `CompactReq::out_time_range`
- In order to simplify the code.
- It is `TimeRange::all()` when picking for normal compaction, while it has a lot of different logic in delta compaction picking.
- Fix a bug in `DeltaCompactionPicker::pick_compaction()`
It did not reset `ColumnFile::compacting` when …
=> Fix(2.3): fix some bugs and improve the delta-compaction

tskv/src/compaction/flush.rs, tskv/src/tsm/writer.rs
Related #.
It did not add the field `TsmWriter::size` with the length of data just written. It follows that the file size recorded in the summary file is lesser than the real file size.
=> Fix(2.3): TsmWriter::size hasn't add index_size

tskv/src/compaction/job.rs, tskv/src/tseries_family.rs
Related #.
Parallel vnode compaction produces time-range-overlapped files.
=> Feature(2.3): vnode compaction runs single-threaded

tskv/src/compaction/flush.rs, tskv/src/compaction/job.rs, tskv/src/database.rs, tskv/src/file_system/file_manager.rs, tskv/src/index/ts_index.rs, tskv/src/kvcore.rs, tskv/src/summary.rs, tskv/src/tseries_family.rs, tskv/src/version_set.rs
=> refactor summary file write process

config/config.toml
https://github.com/cnosdb/cnosdb/pull/2006
Outdated configurations cause the configuration file to fail to parse when we package and upload the docker and it won't run.
```
2024-03-28 16:05:53 -----------------------------------------------------------
2024-03-28 16:05:53 Using Config File: /etc/cnosdb/cnosdb.conf
2024-03-28 16:05:53 
2024-03-28 16:06:04 -----------------------------------------------------------
2024-03-28 16:05:53 thread 'main' panicked at main/src/main.rs:230:54:
2024-03-28 16:05:53 called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "Failed to parse configurtion file '/etc/cnosdb/cnosdb.conf': Error { inner: Error { inner: TomlError { message: \"invalid type: integer `16777216`, expected a string\", original: Some(\"[global]\\n# node_id = …
```
=> fix : Updating outdated config files packaged with docker and other platforms

e2e_test/test_data/dump.sql, e2e_test/test_data/dump_tenant.sql, meta/src/store/state_machine.rs, query_server/test/cases/dml/insert/line_protocol_write.sql, query_server/test/cases/sys_table/information_schema/database_privileges.result, query_server/test/cases/sys_table/information_schema/database_privileges.sql
=> fix(2.3): a role can't be assigned privileges if the db is not existent

common/models/src/meta_data.rs, config/config_8902.toml, config/config_8912.toml, config/src/storage_config.rs, tskv/src/compaction/delta_compact.rs, tskv/src/compaction/job.rs, tskv/src/compaction/mod.rs, tskv/src/compaction/picker.rs, tskv/src/database.rs, tskv/src/kv_option.rs, tskv/src/tseries_family.rs, tskv/src/tsm/block.rs
Related #.
Add metrics for delta compactions, to enable set config `storage.collect_compaction_metrics = true`.
Fix the concurrent compactions sometimes less than config `storage.max_concurrent_compaction`.
- Do not trigger normal compaction after …
=> Feature(2.3): metrics of delta_compactions; some improvements

tskv/src/compaction/flush.rs, tskv/src/memcache.rs, tskv/src/tsm/data_block.rs, tskv/src/tsm/writer.rs
fix: series_data.add_column modifies the schema in groups, but series_data.drop_column also removes the corresponding column from rowdata.fields in groups. If we add a column in the schema update, but remove it without updating the value in the fields, it will be out of bounds.
tskv/src/memcache.rs 314-317. 
memcache:
series_data_write_group()
series_data_columns_modify()
series_delete_by_time_ranges()
memcache_write_group()
memcache_to_chunk_group()
memcache_columns_modify()
memcache_read_series_data()
memcache_delete_by_time_ranges()
writers:
write_and_read()
write_and_read2()
write_and_read3()
data_block:
datablock_to_pages()
datablock_merge()
datablock_sort()
datablock_chunk()
datablock_fliter_by_tomb()
flush:
flush_run()
[//]: # (We generally require a GitHub issue to be filed for …
=> [test] Add TSM related unit tests to improve code coverage.

query_server/sqllogicaltests/cases/sys_table/usage_schema/http_metrics.slt
Related #.
The issue with http_metric was encountered when the test was converted to sqllogictest about 2 months ago. The problem is that http_metric has dependencies, but the order of executing sqllogictest in the query_server/sqllogicaltests/src/main.rs based on std::fs::read_dir depends on the operating system. While it runs stably on the local macOS environment, the CI system running on x86 architecture occasionally encounters issues.
To address this, http_metric has added the following:
```
--#LP_BEGIN …
```
=> fix: errors caused by sequential dependencies in CI

meta/src/bin/main.rs
Related #.
actix-web default payloadconfig limit is 256k, need to expand to 100M.
=> fix: 2.3 modify the meta http frame body size to 100M.

Cargo.lock, Cargo.toml, common/models/src/meta_data.rs
Related #.
Replace the call of win32api to get free disk space from  `GetDiskSpaceInformationW` to `GetDiskFreeSpaceExW` to support platform WIndows7.
=> refactor(meta): fix get_disk_info doesn't support winxp

common/models/src/auth/role.rs, common/models/src/sql/mod.rs, meta/src/error.rs, meta/src/model/meta_tenant.rs, meta/src/store/command.rs, meta/src/store/storage.rs, query_server/query/src/metadata/information_schema_provider/factory/roles.rs, query_server/query/src/sql/planner.rs, query_server/spi/src/query/logical_planner.rs, query_server/sqllogicaltests/cases/dcl/role.slt
Related #2068 
1. Now, if you create a role without inherit, you need to add privilege to access db …
=> revoke privilege

e2e_test/src/case/executor.rs, e2e_test/src/case/mod.rs, e2e_test/src/case/step.rs, e2e_test/src/independent/api_router_tests.rs, e2e_test/src/independent/restart_tests.rs, e2e_test/src/lib.rs, e2e_test/src/utils.rs
Related #.
- Make old API of e2e test case executor deprecated, move `Step` to `StepLegacy`, `execute_steps()` to `execute_steps_legacy()`.
- Add new API for e2e test case executor, add trait `Step`, struct `E2eContext`, add step `ShellStep` to execute shell commands.
- Some implementations of `Step` have fields that can lazy init their values using a reference of `E2eContext`, or can even modify context variables in `E2eContext` before or after their execution.  
- `CnosdbMetaTestHelper` and …
=> Feature(e2e_test):  new api of e2e executor; add case 'data lost after compaction and restart'

common/models/src/predicate/domain.rs, tskv/src/reader/memcache_reader.rs, tskv/src/vnode_store.rs
https://github.com/cnosdb/cnosdb/commit/f4b518cdb081acfb233b4475a32bfb4eba0cd523
Migrate refactoring involving timerange from 2.3 to 2.4
Related #.
[//]: # (There is no need to duplicate the description in the issue here, but it is sometimes worth providing a …
=> refactor: use new Timeranges impl in 2.4.

Makefile, common/protos/Cargo.toml, common/protos/build.rs, common/protos/rustfmt.toml, common/protos/src/generated/mod.rs, common/protos/src/lib.rs, common/protos/src/models_helper.rs, coordinator/Cargo.toml, e2e_test/Cargo.toml, meta/Cargo.toml, replication/Cargo.toml, rustfmt.toml, tskv/Cargo.toml
Related #.
Only commands like `cargo check`, `cargo build` enabled this logical. But commands `make build`, `make build_release` is sensitive with the version of protoc&flatc.
=> Refactor(protos): prevent code of common/protos changed by the IDE-code checking

query_server/sqllogicaltests/cases/sys_table/usage_schema/http_metrics.slt, query_server/sqllogicaltests/src/db_request.rs, query_server/sqllogicaltests/src/instance.rs
Related #.
Add instruction `--#HTTP` for query.
This commit aims to make sure the `sqllogicaltests/cases/sys_table/usage_schema/http_metrics.slt` always pass.
In a SQL logical test case, the **query** type communicates with the __Apache-Flight__ service of CnosDB server, while there are some test expect result sets that depend on serial past interactions with __HTTP__ service, such as:
```sql
query 
select column_name, column_type, data_type from information_schema.columns
where column_name != 'database'
and …
```
=> feat(sqllogicaltests): add request type: HTTP for case http_metrics

common/error_code/src/test.rs, common/macros/src/error_code/mod.rs, tskv/src/error.rs, tskv/src/tsm/page.rs
Related #.
Generate some const methods to get error code.
```rust
#[derive(Debug, Snafu, ErrorCoder)]
#[error_code(mod_code = "03")]
enum MyError {
#[error_code(code = 1)]
SomethingFailed,
Io {
source: std::io::Error,
},
}
#[test]
fn test_my_error() {
let …
```
=> Feature(error_code): procedural macro  `ErrorCoder`  generates extra const-methods

Cargo.lock, main/Cargo.toml, main/src/http/auth_cache.rs, main/src/http/header.rs, main/src/http/http_service.rs, main/src/http/mod.rs, query_server/query/src/auth/auth_control.rs
Related #.
Add cache that maps basic auth to checked `User` to improve the performance of write APIs.
| info | rows/sec |
| --- | --- |
| auth_enabled=false | 469545 |
| auth_enabled=true, with bcrypt verify | 106682 |
| auth_enabled=true, no bcrypt verify | …
=> [Feature(LTS/2.3] Add cache maps auth to User with LRU and TTL

tskv/src/compaction/flush.rs, tskv/src/compute/count.rs, tskv/src/memcache.rs, tskv/src/tsm/reader.rs
Related #.
1. When doing flush, the value type may be Unknown, because sometimes data in cache is missing several columns.
> See flush_test_case_1().
2. Improve test helper function `put_rows_to_cache`, support set some of the columns in a row to be None.
=> [Fix(Flush, 2.3)] sometimes the value type is Unknown

query_server/query/src/extension/analyse/transform_exact_count_to_count.rs, query_server/sqllogicaltests/cases/function/common/count.slt
Related #.
For SQL statement:
```sql
select exact_count(temperature),max(pressure) from air;
```
```plaintext
Arrow: Invalid argument error: number of columns(3) must match number of fields(2) in schema"
```
or
```plaintext
Datafusion: Internal error: Sum is not expected to receive the type Utf8. This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker
```
```csv
COUNT(air.temperature),MAX(air.pressure)
6,80.0
```
[//]: # (There is no need to …
=> feat(query): allow exect_count with other aggregate functions

.github/workflows/community-tag_docker_build_and_push.yml, Cargo.lock
Related #.
Fix build failure of docker **memcheck**:
```log
error: failed to run `rustc` to learn about target-specific information
Caused by:
process didn't exit successfully: `/home/runner/.rustup/toolchains/1.76-x86_64-unknown-linux-gnu/bin/rustc - --crate-name ___ --print=file-names -Zsanitizer=address --target x86_64-unknown-linux-gnu --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=split-debuginfo …
```
=> Fix: build docker image for memcheck failed
