cnosdb/cnosdb

- Dockerfile
- docker/entrypoint.sh
- docker/init-cnosdb.sh
- etc/config.sample.toml
This commit can use docker to build a single cnosdb image
> chore(*): Increase the packaging process by docker.

- server/coordinator/shard_mapper.go
> fix(server): Repair can't cross node select data

- cmd/cnosdb_inspect/main.go
[more information](https://docs.influxdata.com/influxdb/v1.7/tools/influx_inspect/)
About #60 
> feat(cmd): add cnosdb inspect utility

- cmd/cnosdb_inspect/main.go
[more information](https://docs.influxdata.com/influxdb/v1.7/tools/influx_inspect/)
About #60 
> feat(cmd): add cnosdb inspect utility (#60) 

- cmd/cnosdb_inspect/dumptsm/dumptsm.go
- cmd/cnosdb_inspect/main.go
> feat(cmd): Update dumptsm tool to cnosdb

- server/http_handler.go
> fix(server): After precision verification fails, it needs to return

- README.cn.md
> chore(docs: cnosdatabase -> cnosdb)

- .vendor/db/tsdb/series_segment.go
- server/http_handler.go
> Series sync

- CONTRIBUTING.md
- ROADMAP.md
> chore: Update cnosdb-2.0 RoadMap

- ROADMAP.md
> chore: Update cnosdb-1.0 RoadMap

- .vendor/db/query/iterator.go
> fix(query): do not panic when closing failed iterators

- .vendor/db/tsdb/store.go
> fix(db): consistent error for missing shard

- cmd/cnosdb_inspect/main.go
- cmd/cnosdb_inspect/verify/tsm/verify.go
> feat(cmd): add feature verify(TSM integrity verification)

- server/snapshotter/service.go
> fix(server): restore portable backup error

- cmd/cnosdb_inspect/main.go
- cmd/cnosdb_inspect/verify/seriesfile/command.go
- cmd/cnosdb_inspect/verify/seriesfile/verify.go
> feat(cmd): add verify-seriesfile tool

- cmd/cnosdb_tools/generate/init/command.go
- cmd/cnosdb_tools/help/help.go
- cmd/cnosdb_tools/main.go
> feat(cmd):add feature help

- cmd/cnosdb_tools/main.go
> fix(cmd): Clear unreferenced packages

- cmd/cnosdb/backup/backup.go
> fix(server): For Windows, close temp file before removing

- cmd/cnosdb_inspect/dumptsmwal/dumptsmwal.go
- cmd/cnosdb_inspect/main.go
> feat(cmd): Update dumptsmwal tool to cnosdb

- cmd/cnosdb_tools/generate/plan.go
> refactor(C1-2:cmd): update var

- .vendor/db/tsdb/index.go
> fix(C1-3 tsdb): Defer closing of underlying SeriesIDSetIterators

- .vendor/db/pkg/estimator/hll/hll_test.go
> C1 5 tests involving randomness

- server/http_handler.go
> fix(server): fix ping http endpoint not available

- README.md
> add Stack Overflow link

- README.cn.md
> add Stack Overflow CN

- README.cn.md
> add twitter in CN

- README.md
> add twitter in EN

- ROADMAP.md
> updated roadmap 1.0  

- main/src/rpc/tskv.rs
- protos/proto/models.fbs
- protos/proto/tskv.proto
- protos/src/lib.rs
1. feat(proto): add #[allow(unsed_imports)]
2. feat(proto): protos for tskv-grp
> Something about protos

- cmd/cnosdb_inspect/deletetsm/deletetsm.go
- cmd/cnosdb_inspect/reportdisk/reportdisk.go
> fix(C1-7:cmd): fix can't build code

- README.md
> Add LinkedIn link

- README.cn.md
> add LinkedIn link in CN

- README.md
> add Tiktok CN

- README.cn.md
> add 抖音 link

- README.md
> add Zhihu link

- README.cn.md
> add Zhihu link in CN

- README.md
> add CSDN in EN

- README.cn.md
> add CSDN in CN

- README.md
> add Jianshu link in EN

- README.cn.md
> add 简书 link in CN

- Cargo.toml
- logger/Cargo.toml
- logger/src/lib.rs
- main/src/main.rs
> add logger crate

- cmd/cnosdb-cli/cli/cli.go
- cmd/cnosdb-cli/cli/command_line.go
- cmd/cnosdb-cli/main.go
- cmd/cnosdb-ctl/main.go
- cmd/cnosdb-meta/main.go
- cmd/cnosdb-meta/run/run.go
- cmd/cnosdb/main.go
> Display version

- README.md
> updated cnosdb-2.0 raodmap

- build.py
> chore: Update cnosdb_inspect to build file

- cmd/cnosdb_inspect/main.go
- cmd/cnosdb_inspect/report/report.go
- go.mod
- go.sum
> feat(C1-12:cmd): add new feature report to inspect

- cmd/cnosdb_inspect/main.go
- cmd/cnosdb_inspect/reporttsi/reporttsi.go
> feat(C1-13:cmd): add new feature report tsi to inspect

- cmd/cnosdb_inspect/main.go
- cmd/cnosdb_inspect/report/report.go
- go.mod
- go.sum
https://github.com/cnosdb/cnosdb/pull/203
> feat(C1-12:cmd): add new feature report to inspect (#203)

- cmd/cnosdb_inspect/buildtsi/buildtsi.go
- cmd/cnosdb_inspect/main.go
> C1 11 build tsi

- server/server.go
> fix: repair the monitor service not available

- Cargo.toml
- tskv/Cargo.toml
- tskv/src/forward_index/field_info.rs
- tskv/src/forward_index/mod.rs
- tskv/src/forward_index/series_info.rs
- tskv/src/forward_index/tags.rs
- tskv/src/forward_index/tests.rs
- tskv/src/lib.rs
- utils/Cargo.toml
- utils/src/bkdr_hash/mod.rs
- utils/src/lib.rs
> Cnosdb next

- server/continuous_querier/config_test.go
- server/continuous_querier/service_test.go
- server/server.go
> fix(server): repair continous query not executed

- vend/db/models/inline_strconv_parse.go
> fix: repair bytestostring is unsafe

- cmd/cnosdb/run/run.go
- tests/server_helpers.go
> Gilbert liang tests

- cmd/cnosdb_inspect/main.go
> feat(cmd):update cnosdb_inspect main.go

- server/config.go
- server/server.go
- tests/server_helpers.go
- tests/server_test.go
> test(server): add server_helpers & modify export of server

- man/cnosdb/Makefile
- man/cnosdb/cnosdb-cli.txt
- man/cnosdb/cnosdb-config.txt
- man/cnosdb/cnosdb-inspect.txt
- man/cnosdb/cnosdb-restore.txt
- man/cnosdb/cnosdb-run.txt
> feat(man):add file cnosdb-inspect.txt to man

- cmd/cnosdb/backup/backup.go
- cmd/cnosdb/restore/restore.go
- meta/data.go
- server/coordinator/shard_mapper.go
- vend/db/tsdb/shard.go
> Backup and restore

- rpctests/src/index_tests.rs
- tskv/Cargo.toml
- tskv/src/forward_index/mod.rs
- tskv/src/forward_index/series_info.rs
- tskv/src/forward_index/tests.rs
> update rpctests index

- cmd/cnosdb-cli/cli/command_line.go
Closes #202 
fix the bug described in issue https://github.com/cnosdb/cnosdb/issues/202#issue-1187431966
> feat(cmd):fix issue 202

- tests/server_helpers.go
- tests/server_test.go
> test(server) add TestMain

- server/server.go
- tests/server_helpers.go
- tests/server_test.go
> test(server) : correct logger init

- protos/build.rs
- protos/proto/kv_service.proto
- protos/proto/models.fbs
- protos/src/models_helper.rs
- tskv/Cargo.toml
- tskv/src/compute.rs
- tskv/src/direct_io/async_rt.rs
- tskv/src/error.rs
- tskv/src/file_manager.rs
- tskv/src/kvcore.rs
- tskv/src/lib.rs
- tskv/src/option.rs
- tskv/src/wal.rs
1. Edit module `protos`
2. Add wal reader & wal writer
4. Modify file_manager::write_at
5. Add async_rt::try_wake
6. Replace dependence  `crc` with `crc32fast`
7. tskv::write now process WalTask in a future
> Something about writing.

- vend/db/tsdb/engine/tsm1/compact.go
> fix: discard excessive errors

- vend/db/tsdb/engine/tsm1/compact.gen.go
- vend/db/tsdb/engine/tsm1/compact.gen.go.tmpl
- vend/db/tsdb/engine/tsm1/compact.go
- vend/db/tsdb/engine/tsm1/digest.go
- vend/db/tsdb/engine/tsm1/encoding.go
- vend/db/tsdb/engine/tsm1/file_store.go
> fix: add error handling

- tests/server_helpers.go
- tests/server_suite.go
- tests/server_test.go
> test(server) add server_suite

- cmd/cnosdb_tools/compact/command.go
- cmd/cnosdb_tools/main.go
> feat(cmd):add compact to cnosdb_tools. fix issue 96

- main/Cargo.toml
- main/src/main.rs
- main/src/rpc/tskv.rs
- protos/Cargo.toml
- protos/build.rs
- protos/src/models_helper.rs
- rpctests/Cargo.toml
- rpctests/src/kv_service_tests.rs
- tskv/src/file_manager.rs
- tskv/src/kv_option.rs
- tskv/src/kvcore.rs
- tskv/src/lib.rs
- tskv/src/wal.rs
1. Upgrade prost from 0.9 to 0.10;
2. Upgrade tonic from 0.6 to 0.7;
3. Add some test-utils in protos::models_helper (feature should be 'test' or 'full');
4. Implement TskvService::write_points;
5. Add testcase in rpctest::kv_service_tests
> make testcases in rpctest::kv_service_test run properly

- tests/server_suite.go
- tests/server_test.go
> test(server): add test command `drop database` && `create database`

- tests/README.md
- tests/server_test.go
> add README && add DropDatabaseIsolated case

- tests/server_suite.go
- tests/server_test.go
> test(server):  add DeleteSeries case

- tests/server_suite.go
- tests/server_test.go
> test(server):  add test case

- cmd/cnosdb-tools/generate/exec/command.go
- cmd/cnosdb-tools/generate/spec.go
- cmd/cnosdb-tools/main.go
> feat(cmd):c-16 add feature gen-exec to tools

- cmd/cnosdb-tools/export/command.go
- cmd/cnosdb-tools/main.go
- cmd/cnosdb-tools/server/server.go
> feat(cmd):C1-18 add feature cnosdb-tools export

- README.md
> RoadMap:change the deadline

- .github/workflows/docker.yml
> ci(github):add action(build and push Docker images) to workflows

- tests/server_test.go
> test: verify user commands work

- tests/server_test.go
> test: verify create point via line protocol with float and read it back

- tests/server_test.go
> update server test

- tests/server_helpers.go
> test: add remote access interface

- tests/server_test.go
> test: test write lineprotocol with unsigned type

- tests/server_test.go
> code review check && add test server case

- tests/server_test.go
> Test server :  add case

- server/snapshotter/service.go
fix for :https://github.com/cnosdb/cnosdb/issues/293
> fix panic on writeDatabaseInfo

- server/http_handler.go
> fix : add metaclient when create http_handler (#296)

- cmd/cnosdb-ctl/main.go
- cmd/cnosdb-ctl/node/commands.go
- cmd/cnosdb-ctl/node/node.go
- server/server.go
refactor func startNodeServer 
print-meta update-data cnosdb-ctl command
> refactor func startNodeServer ;print-meta update-data cnosdb-ctl command

- cmd/cnosdb-ctl/main.go
- cmd/cnosdb-ctl/shard/commands.go
- server/snapshotter/service.go
> feat(cnosdb-ctl):add feature copy-shard-status

- vend/cnosql/parser.go
Solves the error when IN clause only have one value
> Support IN operator, Bugfix

- server/server.go
- usage_client/client.go
now we can store our usage data
> feature : Deploy usage_server

- meta/data.go
> fix(DropRetentionPolicy):set DefaultRetentionPolicy after drop RetentionPolicy

- README.md
> Update cnosdb 1.0 features desc, match Chinese and English 

- tests/server_test.go
- vend/cnosql/ast.go
- vend/db/query/compile.go
> fix(query):Repair the bug that the field cannot be after group by

- go.mod
- go.sum
For [#343](https://github.com/cnosdb/cnosdb/issues/343)
> delete no used package in go.sum/go.mod

- server/coordinator/statement_executor.go
- server/http_handler.go
- tests/server_delete_test.go
- tests/server_test.go
> Revert "数据库当中最少需要保留一个保留策略"

- cnosdb.go
- config/config.go
- meta/client.go
- meta/client_test.go
- meta/data.go
- meta/data_test.go
- meta/node.go
- meta/remote_client.go
- meta/server.go
- meta/store.go
- pkg/errors/errors.go
- server/coordinator/meta_executor.go
- server/coordinator/points_writer.go
- server/coordinator/statement_executor.go
- server/http_handler.go
- server/server.go
- server/snapshotter/service.go
> refactor:code tidy(errors.go, node.go, cnosdb.go, config.go)

- cmd/cnosdb-meta/run/run.go
Closes #
when use `cnosdb-meta`, if we want to close this server and press `control+c`, we need to press twice.
> fix(meta): deal with SIGTERM and stop the meta server quickly.

- cmd/cnosdb-ctl/node/commands.go
- cmd/cnosdb-ctl/node/node.go
- meta/http_handler.go
- meta/store.go
- server/coordinator/service.go
> NiCAD6.x check & add license

- ROADMAP.md
> docs: update roadmap.

- docs/get-started.md
* docs #447: add cmake to the dependency
* docs #447: add detailed installation methods of cmake
> docs #447: add cmake to the dependency (#85)

- README_CN.md
related #442 , no close. 
update chinese version roadmap
roadmap changed.
README_CN.md
Yes.
> update chinese version roadmap issue #442

- protos/src/models_helper.rs
- tskv/src/summary.rs
- tskv/src/tseries_family.rs
- tskv/src/tsm/writer.rs
- tskv/src/wal.rs
Closes #462.
improve test case, and fix ci
add a test case, change dir of test, add ignore for doc test
None
> fix #462 : fix ci and add a test case

- tskv/src/tsm/tombstone.rs
Closes #470.
Fixed a code that will produce out-of-range error.
> fix #470: fix that fails when load big tombstones

- tskv/src/compaction/compact.rs
- tskv/src/compaction/flush.rs
- tskv/src/kv_option.rs
- tskv/src/kvcore.rs
- tskv/src/summary.rs
- tskv/src/tseries_family.rs
- tskv/src/tsm/block.rs
- tskv/src/tsm/reader.rs
- tskv/src/tsm/tombstone.rs
- tskv/src/version_set.rs
- tskv/src/wal.rs
Close #431.Close #474 
improve read,to skip data which have been deleted
add a filter when read data block
no
> feature #431 : read data skip already deleted

- protos/src/models_helper.rs
- tskv/benches/kvcore_bench.rs
- tskv/src/kvcore.rs
- tskv/src/tseries_family.rs
Closes #480 .
fix bug
flushing shoulb be changed after req is ok
none
> fix #480 : fix flush bug

- protos/src/models_helper.rs
- rpctests/src/kv_service_tests.rs
- tskv/Cargo.toml
- tskv/benches/kvcore_bench.rs
- tskv/src/compaction/flush.rs
- tskv/src/compaction/mod.rs
- tskv/src/kvcore.rs
- tskv/src/summary.rs
- tskv/src/tseries_family.rs
- tskv/src/version_set.rs
- tskv/src/wal.rs
Closes #485 
lock and some bug
relace lock
no
> refactor #485 : use parking lot

- README.md
- README_CN.md
No Close. related #442. 
update readme to link new roadmap 2022.
readme files. both en and cn.
yes, good exps.
> modify raodmap 2022 links

- trace/src/lib.rs
- tskv/src/compaction/flush.rs
- tskv/src/compaction/picker.rs
- tskv/src/error.rs
- tskv/src/forward_index/forward_index.rs
- tskv/src/memcache.rs
- tskv/src/record_file/errors.rs
- tskv/src/record_file/reader.rs
- tskv/src/record_file/writer.rs
- tskv/src/runtime/task.rs
- tskv/src/runtime/work_queue.rs
- tskv/src/summary.rs
- tskv/src/tseries_family.rs
- tskv/src/tsm/block.rs
- tskv/src/version_set.rs
- tskv/src/wal.rs
Closes #426.
remove unwarp
remove unwarp add match result
no
> refactor #426 : check unnecessary painc

- tskv/src/file_utils.rs
- tskv/src/record_file/reader.rs
- tskv/src/record_file/writer.rs
- tskv/src/summary.rs
- tskv/src/tseries_family.rs
- tskv/src/version_set.rs
Closes #495 .
improve summary
when summary size exceed max_summary_size, create a new file and write summary state to it, then move to replace origin summary file
> feature #495 : clean summary file

- tskv/src/summary.rs
none
bug fix
change timerange
no
> bug : fix ts min and ts max

- tskv/src/compaction/compact.rs
- tskv/src/summary.rs
> fix(clippy): use flatten instead of if let OK

- tskv/src/compaction/flush.rs
This function has too many arguments
I split a function into two
> fix(clippy): build_tsm_file_workflow

- tskv/src/compaction/flush.rs
- tskv/tests/test_kvcore_interface.rs
no close
bug fix
start from 000001
no
> bug : file id start with 1

- tskv/src/compaction/compact.rs
- tskv/src/file_utils.rs
- tskv/src/tseries_family.rs
- tskv/src/tsm/block.rs
- tskv/src/tsm/index.rs
- tskv/src/tsm/reader.rs
- tskv/src/tsm/tombstone.rs
- tskv/src/tsm/writer.rs
- tskv/src/version_set.rs
> fix(clippy): auto fix by "make clippy"

- tskv/src/direct_io/cache.rs
Option<(Option<DonorPage<T>>, Box<RwLock<Page>>)> is too complex
> fix(clippy): add a type alias

- .gitignore
- tskv/src/tseries_family.rs
- tskv/src/tsm/reader.rs
- tskv/tests/test_kvcore_interface.rs
no related
bug fix
move block_meta_limit
no
> bug : fix read column file

- query/Cargo.toml
- query/src/tskv_exec.rs
- query/tests/datafusion.rs
- rust-toolchain
> update datafusion version

- clippy.toml
- protos/build.rs
- tskv/src/compaction/compact.rs
- tskv/src/summary.rs
set max arguments as 6
6 = self and 5 normal arguments
add a `Default` implementation for `VersionEdit`
> fix(clippy): summary.rs

- tskv/src/tsm/reader.rs
- tskv/src/tsm/writer.rs
- tskv/src/version_set.rs
1. impl From<ReadTsmError> for Error
2. unwrap_or_else(|| Path::new("/"))
3. impl From<WriteTsmError> for Error
4. insert_block_meta() has too many arguments
5. add_tsfamily() has too many arguments
> fix(clippy): reader.rs, writer.rs, version_set.rs

- tskv/src/tsm/tombstone.rs
warning: used `assert_eq!` with a literal bool
> fix(clippy): tombstone.rs

- Cargo.toml
- coordinator/Cargo.toml
- coordinator/src/lib.rs
- coordinator/src/meta_client.rs
- models/src/consistency_level.rs
- models/src/lib.rs
- models/src/node_info.rs
Closes #498
add coordinator package and some required struct and traits
> add coordinator package and some required struct and traits

- tskv/src/kvcore.rs
- tskv/src/memcache.rs
- tskv/src/tseries_family.rs
- tskv/tests/test_kvcore_interface.rs
no related.
about read
read return data block
no
> refactor : read return data block

- README.md
- README_CN.md
related #442 .
Because homepage is open now, we change to homepage links desc.
Readme and readme(CN)
No.
> #442 : update readme and readmeCN

- main/Cargo.toml
- main/src/http/handler.rs
- models/src/field_info.rs
- models/src/series_info.rs
Closes #.
1. Modify parameter 'database' in API 'write/line_protocol' to 'db'.
2. Remove body size check in http API.
3. Line protocol parse now has type check.
4. Implement Display trait for SeriesInfo and FieldInfo.
> Some modifications for http API.

- main/src/http/handler.rs
> fix: created unexpected write request

- query/Cargo.toml
- query/src/error.rs
- query/src/extend_sql/ast.rs
- query/src/extend_sql/mod.rs
- query/src/extend_sql/parser.rs
> Extent SQL

- main/Cargo.toml
- main/src/http/handler.rs
- main/src/http/mod.rs
- main/src/main.rs
- main/src/rpc/tskv.rs
- tskv/Cargo.toml
- tskv/src/compaction/flush.rs
- tskv/src/database.rs
- tskv/src/index/db_index.rs
- tskv/src/index/errors.rs
- tskv/src/kvcore.rs
- tskv/src/memcache.rs
- tskv/src/tseries_family.rs
> write performance optimizing

- tskv/src/lib.rs
- tskv/src/main.rs
- tskv/src/record_file/reader.rs
- tskv/src/summary.rs
Closes #.
For example: `tskv print [--summary <summary_path>]`
> feat: Add a command to print summary file.

- query/src/error.rs
- query/src/extend_sql/ast.rs
- query/src/extend_sql/mod.rs
- query/src/extend_sql/parser.rs
- query/src/extend_sql/planner.rs
- query/src/lib.rs
> Extent planner

- docs/coding-specifications.md
- main/src/http/mod.rs
- main/src/main.rs
- query/src/db.rs
- query/tests/query_db.rs
- tskv/benches/kvcore_bench.rs
- tskv/src/compaction/compact.rs
- tskv/src/compaction/flush.rs
- tskv/src/compaction/picker.rs
- tskv/src/kvcore.rs
- tskv/src/summary.rs
- tskv/src/tseries_family.rs
- tskv/src/tsm/reader.rs
- tskv/src/tsm/tombstone.rs
- tskv/tests/test_kvcore_interface.rs.del
1. Tombstone::add_range() uses TimeRange instead of (min_ts, max_ts) #490
2. Refactor codes of flush.
3. Remove parameter ts_family_num in Tskv::open().
> Some refactorings for tskv.

- config/Cargo.toml
- config/config.toml
- config/src/lib.rs
- main/src/http/mod.rs
- main/src/main.rs
- query/src/db.rs
- query/tests/query_db.rs
- tskv/benches/kvcore_bench.rs
- tskv/src/compaction/compact.rs
- tskv/src/compaction/flush.rs
- tskv/src/compaction/mod.rs
- tskv/src/compaction/picker.rs
- tskv/src/database.rs
- tskv/src/direct_io/file/system.rs
- tskv/src/error.rs
- tskv/src/file_manager.rs
- tskv/src/index/db_index.rs
- tskv/src/index/engine.rs
- tskv/src/kv_option.rs
- tskv/src/kvcore.rs
- tskv/src/summary.rs
- tskv/src/tseries_family.rs
- tskv/src/tsm/reader.rs
- tskv/src/tsm/writer.rs
- tskv/src/version_set.rs
- tskv/src/wal.rs
- tskv/tests/test_kvcore_interface.rs.del
> feat(config) #580: using new config.

- config/config.toml
- tskv/src/database.rs
- tskv/src/engine.rs
- tskv/src/index/db_index.rs
- tskv/src/index/tests.rs
- tskv/src/kv_option.rs
- tskv/src/kvcore.rs
- tskv/src/tseries_family.rs
- tskv/src/version_set.rs
1. Fix failed delete series info; 
2. Simplify dropping codes;
3. Put data in $path/data/$database
> feat(drop) #567: Something about dropping and configuration

- main/src/http/handler.rs
- query_server/query/src/catalog.rs
- query_server/query/src/db.rs
- query_server/query/src/dispatcher/manager.rs
- query_server/query/src/error.rs
- query_server/query/src/execution/ddl.rs
- query_server/query/src/execution/factory.rs
- query_server/query/src/execution/query.rs
- query_server/query/src/metadata.rs
- query_server/server/src/instance.rs
- query_server/spi/src/query/dispatcher.rs
- query_server/spi/src/query/execution.rs
- query_server/spi/src/service/protocol.rs
- tskv/src/engine.rs
> Implements drop statements parsing.

- common/protos/src/models_helper.rs
- tskv/src/direct_io/file.rs
- tskv/src/wal.rs
> fix(wal): fix wal file re-initialized to 32 bytes when roll

- e2e_test/Cargo.toml
- main/Cargo.toml
- main/src/http/mod.rs
- main/src/main.rs
- query_server/query/Cargo.toml
- query_server/query/src/db.rs
- query_server/query/tests/query_db.rs
- query_server/server/Cargo.toml
- tskv/Cargo.toml
- tskv/src/database.rs
- tskv/src/kvcore.rs
> fix(drop) #567: drop table table executement hang.

- main/src/main.rs
Closes #594 .
fix init trace
use init global tracing
none
> fix(#594) : use init_global_tracing

- common/line_protocol/src/lib.rs
- common/line_protocol/src/parser.rs
- config/Cargo.toml
- config/config.toml
- config/src/lib.rs
- main/src/http/handler.rs
- main/src/main.rs
- tskv/src/kv_option.rs
Closes #.
1. change Line::fields to Vec<(&str, enum)>.
2. Add configuration for logging.
> feat(line_protocol): Some works for parser, and configuration.

- Cargo.toml
- common/mem_allocator/Cargo.toml
- common/mem_allocator/src/lib.rs
- config/config.toml
- main/Cargo.toml
- main/src/main.rs
> add mem_allocator

- common/datafusion_dep/Cargo.toml
- query_server/query/Cargo.toml
- query_server/query/src/extension/expr/selector_function/bottom.rs
- query_server/query/src/extension/expr/selector_function/topk.rs
- query_server/query/src/extension/logical/optimizer_rule/merge_limit_with_sort.rs
- query_server/query/src/extension/logical/optimizer_rule/transform_bottom_func_to_topk_node.rs
- query_server/query/src/extension/logical/optimizer_rule/transform_topk_func_to_topk_node.rs
- query_server/query/src/helper/domain.rs
- query_server/spi/src/query/session.rs
> chore: Upgrade datafusion version to 11.0.0

- query_server/query/src/extension/logical/plan_node/topk.rs
- query_server/query/src/extension/physical/plan_node/topk.rs
- query_server/query/src/sql/planner.rs
- query_server/server/src/instance.rs
- query_server/server/tests/selector_function.rs
- query_server/spi/src/query/session.rs
> feat(sql): implement parser&planner for explain statement

- docs/get-started.md
#608 
doc: add a startup method to get-started.
> doc: add a startup method to get-started.

- tskv/Cargo.toml
- tskv/benches/kvcore_bench.rs
- tskv/src/tsm/coders/mod.rs
- tskv/src/tsm/coders/test.rs
- tskv/src/tsm/mod.rs
> test(#607) : test data block encode

- tskv/tests/test_kvcore_interface.rs
> feat(#425): add some test case of kvcore

- .gitignore
- query_server/query/Cargo.toml
- query_server/query/src/iterator.rs
- tskv/Cargo.toml
- tskv/src/compaction/compact.rs
- tskv/src/memcache.rs
- tskv/src/tsm/block.rs
- tskv/src/tsm/coders/string.rs
- tskv/src/tsm/reader.rs
feat(#621): refactor struct FieldType FieldVal to reduce size.
> feat(#621): refactor struct FieldType FieldVal to reduce size.

- .gitignore
> modify .gitignore to ignore tmpfiles created in testing

- tskv/src/database.rs
- tskv/src/memcache.rs
- tskv/src/tseries_family.rs
> feat(#621):Improved cache size calculation

- common/models/src/field_info.rs
- common/models/src/series_info.rs
- common/models/src/utils.rs
- tskv/Cargo.toml
- tskv/src/compaction/compact.rs
- tskv/src/compaction/flush.rs
- tskv/src/database.rs
- tskv/src/error.rs
- tskv/src/index/tests.rs
- tskv/src/kvcore.rs
- tskv/src/main.rs
- tskv/src/tseries_family.rs
- tskv/src/tsm/block.rs
- tskv/src/tsm/coders/boolean.rs
- tskv/src/tsm/coders/coder_instence.rs
- tskv/src/tsm/coders/float.rs
- tskv/src/tsm/coders/integer.rs
- tskv/src/tsm/coders/mod.rs
- tskv/src/tsm/coders/string.rs
- tskv/src/tsm/coders/timestamp.rs
- tskv/src/tsm/coders/unsigned.rs
- tskv/src/tsm/reader.rs
- tskv/src/tsm/writer.rs
- tskv/tests/test_kvcore_interface.rs
> future(#607) : add high compress ratio algorithm

- tskv/src/kvcore.rs
> [fix] make wal enable valid

- query_server/query/src/sql/parser.rs
- query_server/spi/src/query/ast.rs
- query_server/test/src/case.rs
- query_server/test/src/client.rs
- query_server/test/src/error.rs
- query_server/test/src/groups.rs
- query_server/test/src/main.rs
- query_server/test/src/query.rs
- tskv/src/tsm/mod.rs
> future(#619) : support parser create table

- tskv/src/compaction/flush.rs
> feature : improve get table schema

- Makefile
- common/models/src/series_info.rs
- common/models/src/tag.rs
- common/protos/build.rs
- query_server/query/src/iterator.rs
- query_server/query/src/predicate.rs
- query_server/query/src/sql/parser.rs
- query_server/query/src/stream.rs
- query_server/spi/src/query/ast.rs
- tskv/src/compaction/flush.rs
- tskv/src/database.rs
- tskv/src/direct_io/cache/page.rs
- tskv/src/engine.rs
- tskv/src/index/db_index.rs
- tskv/src/index/tests.rs
- tskv/src/kv_option.rs
- tskv/src/kvcore.rs
- tskv/src/lru_cache.rs
- tskv/src/memcache.rs
- tskv/src/summary.rs
- tskv/src/tseries_family.rs
- tskv/src/tsm/codec/instance.rs
- tskv/src/tsm/codec/mod.rs
> refactor: fix clippy mutex guard

- query_server/query/src/execution/ddl/create_table.rs
- query_server/query/src/execution/ddl/mod.rs
- query_server/query/src/sql/parser.rs
- query_server/query/src/sql/planner.rs
- query_server/spi/src/query/ast.rs
- query_server/spi/src/query/logical_planner.rs
> feature(#619): support create table local plan

- Dockerfile_jenkins
- Jenkinsfile
> ci(jenkins): add automated test process script

- .github/actions/setup-builder/action.yaml
- .github/workflows/makefile.yml
> fix clippy check

- Cargo.toml
- common/metrics/Cargo.toml
- common/metrics/src/lib.rs
- main/Cargo.toml
- main/src/http/http_service.rs
- main/src/main.rs
- tskv/Cargo.toml
- tskv/src/compaction/mod.rs
- tskv/src/kvcore.rs
> Ob metrics

- query_server/query/Cargo.toml
- query_server/query/src/iterator.rs
- tskv/Cargo.toml
- tskv/src/compaction/compact.rs
- tskv/src/database.rs
- tskv/src/memcache.rs
- tskv/src/tseries_family.rs
- tskv/src/tsm/block.rs
- tskv/src/tsm/codec/instance.rs
- tskv/src/tsm/codec/string.rs
- tskv/src/tsm/reader.rs
Closes #621 
cherry-pick from data_format brach
> Optimize the MemCache 

- Dockerfile_jenkins
- Jenkinsfile
> ci: update flatbuffer version to v2.0.6 and run to all test

- Dockerfile
- docker/entrypoint.sh
> CD/CI(jenkins):add automated Dockerfile and scripts

- .github/workflows/makefile.yml
- main/src/http/http_service.rs
- main/src/http/parameter.rs
- query_server/query/src/dispatcher/manager.rs
- query_server/query/src/extension/logical/optimizer_rule/implicit_type_conversion.rs
- query_server/query/src/extension/logical/optimizer_rule/mod.rs
- query_server/query/src/instance.rs
- query_server/query/src/predicate.rs
- query_server/query/src/sql/logical/optimizer.rs
- query_server/query/src/tskv_exec.rs
- query_server/spi/src/query/session.rs
- query_server/spi/src/service/protocol.rs
- query_server/test/cases/data_type/type_conversion/double.result
- query_server/test/cases/data_type/type_conversion/double.sql
- query_server/test/cases/data_type/type_conversion/timestamp.result
- query_server/test/cases/data_type/type_conversion/timestamp.sql
- query_server/test/src/client.rs
Closes #672 .
- Implement string to timestamp data type conversion. 
```
eg.
'1997-01-31 09:26:56' -> TimestampNanosecond(854674016000000000, None)
``` 
- Implement string to numeric data type conversion
```
eg.
'10' -> 10
``` 
- Implement integer to timestamp data type conversion
```
eg.
12345678865 -> TimestampNanosecond(12345678865, None)
```
> feat(query): implement implicit timestamp/string data type conversion

- query_server/query/src/data_source/sink.rs
- query_server/query/src/data_source/tskv_sink.rs
- query_server/query/src/extension/physical/plan_node/table_writer.rs
- query_server/query/src/extension/physical/transform_rule/table_writer.rs
- query_server/query/src/iterator.rs
- query_server/query/src/sql/planner.rs
- query_server/query/src/stream.rs
- query_server/query/src/table.rs
- query_server/query/src/tskv_exec.rs
- query_server/spi/src/query/logical_planner.rs
Closes #684 .
Collect metrics of table TableWriter and TableScan operators.
> feat(query): collect metrics of TableWriter and TableScan operators

- query_server/query/src/catalog.rs
- query_server/query/src/dispatcher/manager.rs
- query_server/query/src/execution/ddl/create_external_table.rs
- query_server/query/src/execution/ddl/create_table.rs
- query_server/query/src/execution/ddl/drop_object.rs
- query_server/query/src/execution/ddl/mod.rs
- query_server/query/src/execution/factory.rs
- query_server/query/src/metadata.rs
- query_server/spi/src/catalog/mod.rs
- query_server/spi/src/query/execution.rs
- query_server/test/cases/ddl/create_table.result
- query_server/test/cases/ddl/create_table.sql
> feature(#616) : add create table test and fix bug

- docs/get-started.md
> doc: specify flatbuffers with v2.0.6

- query_server/query/src/iterator.rs
- tskv/src/engine.rs
- tskv/src/kvcore.rs
- tskv/src/memcache.rs
For #613
I found some `field_id`s with primitive types.
> chore: argument field_id refactors.

- Dockerfile
- Dockerfile.build
- config/config.toml
- config/src/lib.rs
- docker/entrypoint.sh
- tskv/src/tseries_family.rs
- tskv/tests/test_kvcore_interface.rs
Closes #.
- use cnosdb/alpine-glibc as the base-image to shrink the size of image 
- use the `Dockerfile.build` as the building image
- little change to the config, use `/data` as the data directory not `/dev`
> build: dockerfile reinforce

- Dockerfile_jenkins
- Jenkinsfile
> test : add clippy and integration for jenkins

- Makefile
- docs/README.md
- docs/get-started.md
- main/src/main.rs
> fix readme.md

- Dockerfile
> ci: build cnosdb-cli

- .gitignore
- common/models/src/schema.rs
- query_server/query/src/catalog.rs
- query_server/query/src/iterator.rs
- query_server/test/cases/dql/empty_table.result
- query_server/test/cases/dql/empty_table.sql
- tskv/src/engine.rs
- tskv/src/index/db_index.rs
- tskv/src/kvcore.rs
- tskv/src/version_set.rs
Fixed the bug of directly `selecting * from empty_table` without inserting data into table after creating a database.
> fix: fix select first empty table error

- query_server/query/src/catalog.rs
- query_server/query/src/instance.rs
- query_server/query/src/sql/parser.rs
- query_server/test/cases/ddl/drop_database.result
- query_server/test/cases/ddl/drop_database.sql
- tskv/src/database.rs
- tskv/src/engine.rs
- tskv/src/index/db_index.rs
- tskv/src/kvcore.rs
> bug : fix create table can use empty fields

- query_server/query/src/metadata.rs
> bug : create db with tsf

- client/Cargo.toml
- common/models/src/schema.rs
- main/src/http/http_service.rs
- tskv/src/database.rs
- tskv/src/memcache.rs
- tskv/src/tseries_family.rs
> bug : fix schema id

- common/models/src/schema.rs
- query_server/query/src/catalog.rs
- tskv/src/compaction/flush.rs
- tskv/src/database.rs
- tskv/src/index/db_index.rs
- tskv/src/memcache.rs
- tskv/src/summary.rs
- tskv/src/tsm/reader.rs
- tskv/src/version_set.rs
> refactor: make key of HashMap clearer

- query_server/query/src/catalog.rs
> bug : fix external table not found

- common/protos/src/models_helper.rs
- tskv/src/kvcore.rs
- tskv/src/tsm/codec/instance.rs
- tskv/src/wal.rs
> improve : add compress for wal

- query_server/test/cases/ddl/create_table.result
- query_server/test/cases/dml/insert/insert_values.result
- query_server/test/cases/dml/insert/insert_values.sql
- query_server/test/cases/dql/filter_push_down.result
- query_server/test/cases/sqlancer/function.result
- query_server/test/cases/sqlancer/select.result
- tskv/src/database.rs
- tskv/src/error.rs
> fix : check empty field

- config/config.toml
- config/src/lib.rs
- main/src/http/http_service.rs
- main/src/main.rs
- query_server/query/src/dispatcher/manager.rs
- query_server/query/src/instance.rs
- query_server/spi/src/query/mod.rs
- tskv/src/kv_option.rs
> query: limit queries connections and queries content size

- common/line_protocol/src/parser.rs
Closes #.
When line protocol contains this, it fails:
`tb1,ta=a1 fa="hello, world"`
> fix: failed parsing request contains string field with commas or equal sign.

- query_server/query/src/sql/planner.rs
- query_server/test/cases/ddl/create_table.result
> fix : check field and tag name

- tskv/src/kvcore.rs
Closes #.
It seems that variables in the if expression lives too long ( whole if block ) like `LockGuard`.
I changed the code to fix that compaction read locked VersionSet and TsFamily too long.
> fix(tskv): compact read locked VersionSet and TsFamily too long

- config/config.toml
- config/src/lib.rs
- tskv/src/file_system/file/system.rs
- tskv/src/file_system/file_manager.rs
- tskv/src/kv_option.rs
- tskv/src/kvcore.rs
- tskv/src/wal.rs
> improve : improve performance

- Makefile
- tskv/src/context.rs
- tskv/src/database.rs
- tskv/src/kvcore.rs
- tskv/src/summary.rs
- tskv/src/tseries_family.rs
> fix : add tsfid for global context

- query_server/query/src/extension/logical/optimizer_rule/mod.rs
- query_server/query/src/extension/logical/optimizer_rule/reject_cross_join.rs
- query_server/query/src/sql/logical/optimizer.rs
> fix: reject cross join

- common/models/src/points.rs
- common/models/src/series_info.rs
- common/protos/proto/models.fbs
- common/protos/src/models_helper.rs
- main/src/http/http_service.rs
- query_server/query/src/utils/point_util.rs
- tskv/src/database.rs
- tskv/src/index/db_index.rs
- tskv/src/kvcore.rs
Closes #.
`flatc` generated conflict method `Table()` in Golang.
> refactor: rename Point::table to tab, Points::database to db

- main/Cargo.toml
> chore: add termination feature for 'ctrlc'

- Makefile
- tskv/src/context.rs
> jenkins : fix jenkins unit test failed

- Dockerfile_jenkins
- Jenkinsfile
- query_server/test/script/start_and_test.sh
> ci: clean cache data

- Dockerfile.build
> build: use gcc-9

- Dockerfile.build
> build: fix missing libssl.so.10

- common/models/src/predicate/transformation.rs
> fix : clippy error

- main/src/http/result_format.rs
- query_server/query/src/dispatcher/manager.rs
- query_server/query/src/dispatcher/mod.rs
- query_server/query/src/dispatcher/query_tracker.rs
- query_server/query/src/execution/ddl/describe_database.rs
- query_server/query/src/execution/ddl/describe_table.rs
- query_server/query/src/execution/ddl/mod.rs
- query_server/query/src/execution/factory.rs
- query_server/query/src/execution/mod.rs
- query_server/query/src/execution/query.rs
- query_server/query/src/execution/sys/kill_query.rs
- query_server/query/src/execution/sys/mod.rs
- query_server/query/src/execution/sys/show_queries.rs
- query_server/query/src/instance.rs
- query_server/query/src/metadata.rs
- query_server/query/src/sql/parser.rs
- query_server/query/src/sql/planner.rs
- query_server/spi/src/query/ast.rs
- query_server/spi/src/query/dispatcher.rs
- query_server/spi/src/query/execution.rs
- query_server/spi/src/query/logical_planner.rs
- query_server/spi/src/query/mod.rs
- query_server/spi/src/server/dbms.rs
- query_server/spi/src/service/protocol.rs
- query_server/test/cases/ddl/create_table.result
- query_server/test/cases/dml/insert/insert_select.result
- query_server/test/cases/dml/insert/insert_values.result
- query_server/test/cases/dql/filter_push_down.result
- query_server/test/cases/sqlancer/function.result
- query_server/test/cases/sqlancer/select.result
> implement show queries & kill query

- .github/actions/setup-builder/action.yaml
- .github/workflows/makefile.yml
- query_server/test/script/start_and_test.sh
> ci: Running integration tests using self-hosted

- common/metrics/src/lib.rs
- main/src/http/http_service.rs
- main/src/main.rs
#627
refactor metrics and support multi-dimensional metrics
> improve: improve metrics

- tskv/Cargo.toml
- tskv/src/file_system/file/async_file.rs
Closes #.
There is an old problem in the code of async IO.
> fix: errors in code in feature io_uring

- tskv/src/file_system/file/async_file.rs
Closes #.
Removed an unsafe mark to let clippy check passed.
> fix(file): Remove unnecessary unsafe mark

- tskv/src/compaction/compact.rs
- tskv/src/compaction/flush.rs
- tskv/src/compaction/picker.rs
- tskv/src/database.rs
- tskv/src/summary.rs
- tskv/src/tseries_family.rs
> fix : compaction throw not found file error

- common/license/src/lib.rs
- coordinator/src/hh_queue.rs
- coordinator/src/reader.rs
- main/src/tcp/tcp_service.rs
- meta/src/meta_client.rs
- query_server/query/src/execution/ddl/drop_database_object.rs
- tskv/src/compaction/flush.rs
- tskv/src/database.rs
- tskv/src/engine.rs
- tskv/src/iterator.rs
- tskv/src/kvcore.rs
- tskv/src/summary.rs
- tskv/src/tseries_family.rs
- tskv/src/version_set.rs
- tskv/src/wal.rs
> change parking_lot::RwLock to tokio::sync::RwLock

- Cargo.toml
- common/models/src/meta_data.rs
- common/models/src/schema.rs
- common/protos/src/models_helper.rs
- meta/src/limiter.rs
- meta/src/meta_client.rs
- meta/src/store/state_machine.rs
- tskv/Cargo.toml
- tskv/src/compaction/check.rs
- tskv/src/compaction/compact.rs
- tskv/src/compaction/flush.rs
- tskv/src/compaction/mod.rs
- tskv/src/database.rs
- tskv/src/kvcore.rs
- tskv/src/memcache.rs
- tskv/src/schema/schemas.rs
- tskv/src/tseries_family.rs
- tskv/src/tsm/block.rs
- tskv/src/tsm/index.rs
- tskv/src/tsm/reader.rs
Closes #.
Add a method to get a hash tree for ts_family.
> feature(repair): Get hash tree for tsfamily

- .github/workflows/makefile.yml
- Dockerfile
- Makefile
- client/Cargo.toml
- main/Cargo.toml
- meta/Cargo.toml
- meta/singleton.sh
- query_server/test/script/start_and_test.sh
- run_cluster.sh
Closes #.
1. main/Cargo.toml: add binary target cnosdb
2. meta/Cargo.toml: add binary target cnosdb-meta
3. client/Cargo.toml: add binary target cnosdb-cli
4. refactor shell scripts to fit binary name changes
5. meta/cluster.sh: remove precondition `cd meta`
> feat(script): Refactor some Cargo.toml and shell scripts

- tskv/src/compaction/check.rs
- tskv/src/error.rs
Closes #.
To fix error that there are serial non-existent error type `Error::Compact` in code.
> fix(repair): Change return error types in check.rs

- .github/actions/setup-builder/action.yaml
- common/models/src/meta_data.rs
- coordinator/src/command.rs
- coordinator/src/writer.rs
- meta/src/meta_client.rs
- meta/src/meta_client_mock.rs
- query_server/query/src/execution/ddl/checksum_group.rs
- query_server/query/src/execution/ddl/compact_vnode.rs
- query_server/query/src/execution/ddl/copy_vnode.rs
- query_server/query/src/execution/ddl/drop_vnode.rs
- query_server/query/src/execution/ddl/mod.rs
- query_server/query/src/execution/ddl/move_node.rs
- query_server/query/src/sql/parser.rs
- query_server/query/src/sql/planner.rs
- query_server/spi/src/query/ast.rs
- query_server/spi/src/query/logical_planner.rs
- tskv/src/engine.rs
- tskv/src/index/engine.rs
- tskv/src/kv_option.rs
- tskv/src/kvcore.rs
> feature : add vnode sql and kv drop vnode

- common/models/src/auth/user.rs
- meta/src/user_manager.rs
> fix: uncomment password authentication

- common/models/src/auth/role.rs
> feat: add system privilege to admin

- client/src/command.rs
- common/models/src/auth/mod.rs
- common/models/src/auth/role.rs
- common/models/src/auth/user.rs
- meta/src/store/state_machine.rs
- meta/src/tenant_manager.rs
- meta/src/user_manager.rs
- query_server/query/src/execution/ddl/create_tenant.rs
- query_server/query/src/metadata/cluster_schema_provider/factory/users.rs
- query_server/query/src/sql/planner.rs
- query_server/test/cases/sys_table/cluster_schema/users.result
improve: fix select * tenants
* cli add switch system schema
* hidden user password
> improve: fix bugs 

- Cargo.toml
- coordinator/src/hh_queue.rs
- main/src/main.rs
- query_server/test/script/start_and_test.sh
> test : improve test speed

- .github/actions/setup-builder/action.yaml
> ci: skip flatbuffers comilpe in the basic builder

- README.md
No issue Closed.
Readme note
README.ME file 
Yes.
> Update README.MD to fix some words

- Dockerfile
- Dockerfile.build
- Dockerfile_jenkins
> upgrade flatterbuffer and install protobuffer 

- tskv/Cargo.toml
- tskv/src/index/cache.rs
- tskv/src/index/mod.rs
- tskv/src/index/ts_index.rs
> forward index lru cache

- config/config.toml
- config/config_31001.toml
- config/config_32001.toml
- config/src/lib.rs
- tskv/src/kv_option.rs
- tskv/src/wal.rs
Closes #.
1. Add config `max_file_size` for wal, instead of const variable `SEGMENT_SIZE`
2. Add default values for config, copied from `config/config.toml`, for more details about serde.rs, see [Document: attr-default](https://serde.rs/attr-default.html)
> feat(config): Add default values for config; Add wal/max_file_size(1Gib)

- README.md
- README_CN.md
Nothing close.
#472 related.
README.md
README_CN.md
Yes.
> Fix EN and CN links of Homepage

- meta/singleton.sh
- tskv/src/compaction/compact.rs
- tskv/src/summary.rs
- tskv/src/tsm/index.rs
- tskv/src/tsm/reader.rs
- tskv/src/tsm/writer.rs
Closes #.
1. CompactMeta::tsf_id not set in compaction.
2. VersionEdit::has_seq_no is true in compaction, it must be false.
3. Fixed some bugs in tsm::reader::BlockMetaIterator.
1. Add two arguments in this script:
```
Start and initialize CnosDB Metadata Server.
USAGE:
meta/singleton.sh [OPTIONS]
OPTIONS:
-sb, --skip-build    Skip building before running CnosdDB Metadata Server
-sc, --skip-clean    Clean data directory before running CnosdDB Metadata Server
```
2. Align outputs of function rpc()
```
Initialize server 1 as a single-node cluster
--- rpc(:21001/init, {})
--- {"Ok":null}
```
> fix(db): Fix some bugs in recover and read

- common/http_protocol/src/parameter.rs
- common/line_protocol/Cargo.toml
- common/line_protocol/src/lib.rs
- common/line_protocol/src/parser.rs
- e2e_test/src/http_api_tests.rs
- main/src/http/http_service.rs
- meta/src/tenant_manager.rs
- query_server/query/Cargo.toml
- query_server/query/src/prom/mod.rs
- query_server/query/src/prom/remote_read.rs
- query_server/query/src/prom/remote_server.rs
- query_server/query/src/sql/planner.rs
- query_server/spi/src/lib.rs
- query_server/spi/src/server/prom.rs
- query_server/test/cases/dml/insert/line_protocol_write.result
- query_server/test/cases/dml/insert/line_protocol_write.sql
> feature: support prom remote write

- common/line_protocol/src/parser.rs
Closes #.
Line protocol parser will crush when parsing statements with unicode characters like '中', '发', etc..
> fix(line_protocol): Fix failed parsing statements with unicode tag keys

- meta/singleton.sh
- tskv/src/tsm/index.rs
- tskv/src/tsm/reader.rs
Closes #.
Using `sort_unstable_by_key()` gives function `load_index()` a tremendous increase of speed.
> feat(index): improve load_index performance

- client/src/command.rs
- client/src/exec.rs
- client/src/main.rs
- main/src/flight_sql/auth_middleware/generated_bearer_token_authenticator.rs
- main/src/flight_sql/flight_sql_server.rs
- main/src/http/http_service.rs
* improve: cli add use statement
* improve: update ping version
> improve: remove moka cache thread pool

- meta/Cargo.toml
- meta/cluster.sh
- meta/src/bin/main.rs
- meta/src/client.rs
- meta/src/service/api.rs
- meta/src/service/connection.rs
- meta/src/store/config.rs
- meta/src/store/mod.rs
- meta/src/store/state_machine.rs
> meta enhancement & improve meta performance

- common/utils/src/bloom_filter.rs
- tskv/src/compaction/check.rs
- tskv/src/compaction/compact.rs
- tskv/src/compaction/flush.rs
- tskv/src/compaction/mod.rs
- tskv/src/compaction/picker.rs
- tskv/src/database.rs
- tskv/src/iterator.rs
- tskv/src/kvcore.rs
- tskv/src/summary.rs
- tskv/src/tseries_family.rs
- tskv/src/tsm/index.rs
- tskv/src/tsm/reader.rs
- tskv/src/tsm/tombstone.rs
- tskv/src/tsm/writer.rs
- tskv/src/version_set.rs
Closes #.
To avoid unnecessary fopen.
Recovers and compactoins will generate this filter.
OPtimizes: String database turned to Arc<String>.
> feat(read): Add field-id-filter in ColumnFile and some optimizes.

- config/config.toml
- config/config_31001.toml
- config/config_32001.toml
- config/src/duration.rs
- config/src/lib.rs
- tskv/Cargo.toml
- tskv/src/compaction/check.rs
- tskv/src/compaction/compact.rs
- tskv/src/compaction/flush.rs
- tskv/src/compaction/job.rs
- tskv/src/compaction/mod.rs
- tskv/src/compaction/picker.rs
- tskv/src/database.rs
- tskv/src/kv_option.rs
- tskv/src/kvcore.rs
- tskv/src/summary.rs
- tskv/src/tseries_family.rs
- tskv/src/version_set.rs
#530
Trigger of compaction using the number of level 0 files.
TsFamily starts compaction `compact_trigger_cold_duration`  after last write.
Max concurent compaction at the same time.
> Feature: Add some configurations about compaction

- coordinator/src/command.rs
- coordinator/src/errors.rs
- coordinator/src/reader.rs
- coordinator/src/service.rs
- coordinator/src/writer.rs
- meta/Cargo.toml
- meta/src/client.rs
> implement request timeout and add write/read request logs

- meta/src/store/command.rs
- tskv/src/compaction/picker.rs
- tskv/src/kvcore.rs
- tskv/src/tsm/index.rs
> improve : multi thread flush

- meta/src/client.rs
- meta/src/service/api.rs
> fix: when meta data no change will persist holding watch connection

- common/models/src/meta_data.rs
- common/models/src/schema.rs
- meta/src/meta_client.rs
> fix: Overflow when calculating time range

- Cargo.toml
- common/models/src/schema.rs
- meta/src/meta_client.rs
- meta/src/meta_client_mock.rs
- query_server/query/src/execution/ddl/alter_table.rs
- query_server/query/src/execution/ddl/create_external_table.rs
- query_server/query/src/execution/ddl/create_table.rs
- query_server/query/src/extension/logical/optimizer_rule/implicit_type_conversion.rs
- query_server/query/src/metadata/information_schema_provider/factory/columns.rs
- query_server/query/src/metadata/mod.rs
- query_server/query/src/prom/remote_server.rs
- query_server/query/src/table.rs
- tskv/src/compaction/check.rs
- tskv/src/compaction/flush.rs
- tskv/src/database.rs
- tskv/src/engine.rs
- tskv/src/kvcore.rs
- tskv/src/memcache.rs
- tskv/src/schema/schemas.rs
- tskv/src/tseries_family.rs
- tskv/src/tsm/writer.rs
> improve : remove memory copy in get schema

- config/config.toml
- config/src/lib.rs
- main/src/main.rs
- query_server/test/src/groups.rs
- tskv/src/compaction/check.rs
- tskv/src/compaction/flush.rs
- tskv/src/compaction/job.rs
- tskv/src/compaction/picker.rs
- tskv/src/context.rs
- tskv/src/database.rs
- tskv/src/file_system/file_manager.rs
- tskv/src/kv_option.rs
- tskv/src/kvcore.rs
- tskv/src/summary.rs
- tskv/src/tseries_family.rs
- tskv/src/version_set.rs
> improve : opt lock and remove unbounded channel

- tskv/src/compaction/flush.rs
- tskv/src/summary.rs
- tskv/src/tseries_family.rs
> fix: set flushed to true after summary write finished

- meta/src/client.rs
- meta/src/meta_admin.rs
- meta/src/meta_client.rs
- meta/src/meta_manager.rs
- meta/src/tenant_manager.rs
- meta/src/user_manager.rs
> fix : meta switch leader

- Cargo.lock
- meta/config/config_21001.toml
- meta/config/config_21002.toml
- meta/config/config_21003.toml
- meta/src/bin/main.rs
- meta/src/lib.rs
- meta/src/service/mod.rs
- meta/src/service/raft_api.rs
- meta/src/store/config.rs
- query_server/query/src/instance.rs
> improve: refactor init meta

- meta/src/error.rs
- tskv/src/schema/schemas.rs
> fix : bench throw table already exists

- coordinator/src/hh_queue.rs
- tskv/src/error.rs
- tskv/src/file_system/mod.rs
- tskv/src/file_system/queue.rs
- tskv/src/file_utils.rs
> implement a file queue and refactor hinted handoff

- coordinator/src/hh_queue.rs
- main/src/main.rs
- main/src/server.rs
- tskv/src/engine.rs
- tskv/src/error.rs
- tskv/src/file_system/mod.rs
- tskv/src/file_system/queue.rs
- tskv/src/file_utils.rs
- tskv/src/kvcore.rs
> refactor system main function

- meta/src/store/state_machine.rs
Closes #867
Check if the IP address of the cluster node is valid.
If we add the submitted ip for the same cluster, we should output the error log.
> fix(meta): effective ip

- main/src/main.rs
https://github.com/cnosdb/cnosdb/issues/934
Closes #.
modify cnosdb help info 
before:
after :
> fix(cnosdb):modify  cnosdb help info

- tskv/src/context.rs
Closes #.
There has an error in calculation of minimum sequence  of all ts_families.
> fix(wal): error in wal auto deletion

- common/metrics/src/prom_reporter.rs
- meta/src/store/state_machine.rs
* fix: restart throws add datanode error
> fix: encoding fails when prom metrics_family is empty

- Cargo.lock
- Cargo.toml
- common/memory_pool/Cargo.toml
> feat: version 2.2.0

- Cargo.lock
- Cargo.toml
- common/models/src/duration.rs
- common/models/src/errors.rs
- common/models/src/lib.rs
- query_server/query/src/extension/expr/expr_fn.rs
- query_server/query/src/extension/expr/expr_rewriter.rs
- query_server/query/src/extension/expr/mod.rs
- query_server/query/src/extension/expr/window/mod.rs
- query_server/query/src/extension/expr/window/time_window.rs
- query_server/query/src/extension/logical/logical_plan_builder.rs
- query_server/query/src/extension/logical/mod.rs
- query_server/query/src/extension/logical/optimizer_rule/mod.rs
- query_server/query/src/extension/logical/optimizer_rule/transform_bottom_func_to_topk_node.rs
- query_server/query/src/extension/logical/optimizer_rule/transform_time_window.rs
- query_server/query/src/extension/logical/optimizer_rule/transform_topk_func_to_topk_node.rs
- query_server/query/src/extension/logical/plan_node/expand.rs
- query_server/query/src/extension/logical/plan_node/mod.rs
- query_server/query/src/extension/physical/plan_node/expand.rs
- query_server/query/src/extension/physical/plan_node/mod.rs
- query_server/query/src/extension/physical/transform_rule/expand.rs
- query_server/query/src/extension/physical/transform_rule/mod.rs
- query_server/query/src/sql/logical/optimizer.rs
- query_server/query/src/sql/physical/planner.rs
- query_server/spi/src/lib.rs
- query_server/test/cases/function/time_window.result
- query_server/test/cases/function/time_window.sql
> Implement tumbling_window and sliding_window

- query_server/query/src/sql/parser.rs
- query_server/query/src/sql/planner.rs
- query_server/spi/src/query/ast.rs
> feat: implement the syntax parsing of stream-related sql

- query_server/query/src/extension/logical/plan_node/mod.rs
- query_server/query/src/extension/logical/plan_node/watermark.rs
- query_server/query/src/extension/mod.rs
> feat: add logical node Watermark

- README.md
- README_CN.md
related #472 
change logo, and SQLancer Chinese desc.
> update readme 

- query_server/query/src/sql/parser.rs
fix: fix the problem that the keywords of the statement creating an external table are case-sensitive
> fix: fix keywords parse failed. 

- Cargo.lock
- common/limiter_bucket/Cargo.toml
- tskv/src/kvcore.rs
- tskv/src/summary.rs
> fix : fix memory pool

- query_server/query/src/sql/parser.rs
- query_server/test/cases/ddl/create_table.result
- query_server/test/cases/ddl/create_table.sql
> fix : create table at least one field

- query_server/query/src/extension/logical/plan_node/table_writer.rs
- query_server/query/src/sql/parser.rs
- query_server/test/cases/dml/explain/explain_copy_into.result
- query_server/test/cases/dml/explain/explain_copy_into.sql
> fix: parse explain statement

- coordinator/src/service.rs
- main/src/rpc/tskv.rs
- query_server/query/src/extension/physical/plan_node/aggregate_filter_scan.rs
- query_server/query/src/extension/physical/plan_node/tskv_exec.rs
- query_server/test/cases/dql/limit.result
- query_server/test/cases/dql/limit.sql
> feature: support limit table scan

- tskv/src/kvcore.rs
> fix : set channel cap to 1024

- query_server/query/src/extension/expr/window/time_window.rs
- query_server/query/src/extension/logical/optimizer_rule/transform_time_window.rs
- query_server/test/cases/tsbench/avg_daily_driving_duration.result
- query_server/test/cases/tsbench/avg_daily_driving_duration.sql
fix transform error in the case of nested time_window in subquery
> fix: time_window transform rule

- tskv/src/compaction/flush.rs
- tskv/src/kvcore.rs
- tskv/src/query_iterator/iterator.rs
> feat(iterator): split RowIterator into series-groups

- config/config.toml
- config/config_31001.toml
- config/config_32001.toml
- config/src/lib.rs
- config/src/storage_config.rs
- config/src/wal_config.rs
- tskv/src/compaction/check.rs
- tskv/src/compaction/flush.rs
- tskv/src/database.rs
- tskv/src/kv_option.rs
- tskv/src/kvcore.rs
- tskv/src/record_file/writer.rs
- tskv/src/tseries_family.rs
- tskv/src/version_set.rs
- tskv/src/wal.rs
Closes #.
Vnodes that write low-frequency also flush low-frequency, make WALs too large.
- Add config `wal.flush_trigger_total_file_size`, if file size of all WALs exceeds that value, causes a flush on all Vnodes. 
- Fixed some typos.
> feat(wal): add config wal.flush_trigger_total_file_size

- meta/config/config_21001.toml
- meta/config/config_21002.toml
- meta/config/config_21003.toml
- meta/src/store/config.rs
- tskv/src/tseries_family.rs
Closes #.
```toml
[log]
logs_level = "info"
logs_path = "/tmp/cnosdb/logs"
```
```rust
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct LogConfig {
#[serde(default = "LogConfig::default_level")]
pub level: String,
#[serde(default = "LogConfig::default_path")]
pub path: String,
pub tokio_trace: Option<TokioTrace>,
}
```
> fix(test): remove redundant file/dirs created during test

- Cargo.toml
- coordinator/Cargo.toml
- query_server/query/Cargo.toml
- query_server/query/src/extension/logical/optimizer_rule/implicit_type_conversion.rs
- query_server/spi/Cargo.toml
- query_server/test/cases/data_type/type_conversion/double.result
- query_server/test/cases/data_type/type_conversion/double.sql
> fix: fix the problem that there is no alias when converting expressions

- meta/src/model/user_manager.rs
- query_server/query/src/sql/planner.rs
- query_server/test/cases/sys_table/cluster_schema/users.result
- query_server/test/cases/sys_table/cluster_schema/users.sql
- query_server/test/cases/sys_table/information_schema/database_privileges.result
- query_server/test/cases/sys_table/information_schema/database_privileges.sql
- query_server/test/cases/sys_table/information_schema/roles.result
- query_server/test/cases/sys_table/information_schema/roles.sql
* fix drop database privileges
* add some test
> fix: fix alter user throws invalid type

- config/config.toml
- config/config_31001.toml
- config/config_32001.toml
- config/src/deployment.rs
- config/src/lib.rs
- main/src/main.rs
- query_server/test/script/start_and_test.sh
* change run command
1. Add configuration file deployment
```toml
[deployment]
mode = 'singleton'
```
2. The running command becomes `cnosdb run --deployment-mode tskv`
> improve: add deployment-mode config

- .gitlab-ci.yml
> add gitlab ci file

- tskv/src/query_iterator/iterator.rs
- tskv/src/query_iterator/mod.rs
*fix: fix throw "failed get array primitive-type builder" error log
> refactor: change the method of trait Cursor

- config/config.toml
- config/config_31001.toml
- config/config_32001.toml
- config/src/deployment.rs
- config/src/lib.rs
- main/src/main.rs
Now change the string accepted by the configuration file deployment.mode item to lowercase snake
> minor: deployment-mode config str only accept snake_case

- README.md
- README_CN.md
> add sqllogictest-rs to acknowledgement

- .gitlab-ci.yml
- meta/cluster.sh
- run_cluster.sh
> Avoid gitlab bench CI failures due to excessive log output to the screen,modify resource info.

- .github/workflows/github_mirror_to_gitlab.yml
> Added active sync code to gitlab

- Dockerfile.build
> fix unable compile flight sql

- .github/ISSUE_TEMPLATE/bug_report.md
> fix hide bug_report.md

- .github/ISSUE_TEMPLATE/bug_report.md
- Cargo.lock
- Cargo.toml
- Dockerfile.build
- common/http_protocol/Cargo.toml
- common/limiter_bucket/Cargo.toml
- common/metrics/Cargo.toml
- coordinator/Cargo.toml
- main/Cargo.toml
- meta/Cargo.toml
- query_server/query/Cargo.toml
- tskv/Cargo.toml
```shell
cargo install cargo-udeps --locked
cargo +nightly udeps
```
> build: Remove unused deps

- Cargo.lock
- common/trace/src/lib.rs
- coordinator/src/reader/query_executor.rs
- coordinator/src/service.rs
- coordinator/src/writer.rs
- main/src/http/http_service.rs
- main/src/http/result_format.rs
- main/src/meta_single/meta_service.rs
- main/src/rpc/tskv.rs
- main/src/server.rs
- meta/src/store/state_machine.rs
- query_server/query/src/dispatcher/manager.rs
- query_server/query/src/execution/ddl/mod.rs
- query_server/query/src/execution/query.rs
- query_server/query/src/execution/scheduler/dedicated.rs
- query_server/query/src/execution/scheduler/local.rs
- query_server/query/src/instance.rs
- query_server/query/src/prom/remote_server.rs
- query_server/query/src/sql/optimizer.rs
- query_server/query/src/sql/physical/planner.rs
- query_server/spi/Cargo.toml
- query_server/spi/src/lib.rs
- query_server/spi/src/query/execution.rs
- query_server/spi/src/query/logical_planner.rs
- query_server/spi/src/server/prom.rs
- query_server/spi/src/service/protocol.rs
* refactor prometheus server
* remove unused async
* refactor http service
* fix deployment-mode default memory
> refactor: refactor log

- .github/workflows/docker_build_and_push_on_time.yml
- .github/workflows/docker_build_and_push_with_tag.yml
> Add scripts to automate the deployment of docker images

- Dockerfile
> rm the entrypoint of dockerfile

- Cargo.lock
- tskv/src/index/ts_index.rs
> fix(tskv): blocked when dropping table

- meta/cluster.sh
- query_server/test/script/start_and_test.sh
- query_server/test/script/start_and_test_3meta2data.sh
- query_server/test/script/start_and_test_all.sh
- run_cluster.sh
> Add test cases of different deployment

- .github/workflows/github_mirror_to_gitlab.yml
> modify sync gitlab info

- .github/workflows/docker_build_and_push_on_time.yml
- .github/workflows/docker_build_and_push_with_tag.yml
> Update the community version docker image logo

- .gitlab-ci.yml
Adapt to configuration file port changes.
Closes #.
> Benxiaohai001 patch 2

- common/trace/src/lib.rs
> improve: remove log color

- common/models/src/lib.rs
- common/models/src/meta_data.rs
- common/models/src/node_info.rs
- common/models/src/utils.rs
- config/config.toml
- config/config_8902.toml
- config/config_8912.toml
- config/src/cluster_config.rs
- config/src/heartbeat_config.rs
- config/src/lib.rs
- config/src/nodebasic_config.rs
- coordinator/src/service.rs
- main/src/main.rs
- main/src/server.rs
- meta/config/config.toml
- meta/config/config_8901.toml
- meta/config/config_8911.toml
- meta/config/config_8921.toml
- meta/src/bin/main.rs
- meta/src/client.rs
- meta/src/model/meta_admin.rs
- meta/src/model/meta_client_mock.rs
- meta/src/model/meta_manager.rs
- meta/src/model/mod.rs
- meta/src/store/command.rs
- meta/src/store/config.rs
- meta/src/store/key_path.rs
- meta/src/store/state_machine.rs
Closes #.
The heartbeat time stamp of the node side is integrated into nodemetrics along with the disk_free information and reported to the meta node.For the meta side, the modification of node state logic will only be triggered when the node is a leader node.The heartbeat detection interval of the meta node is defined as heartbeat_recheck_interval, which is defined as the timeout period of heartbeat_expired_interval. When the leader node of meta detects that the timestamp distance of the currently acquired node has exceeded the heart_expired_interval, the node is considered offline and its status will be changed.
> implement heartbeat mechanism

- query_server/test/cases/dml/copy_into/copy_into_location.result
- query_server/test/cases/dml/copy_into/copy_into_location.sql
> copy_into_location ADD copy into table CASE

- Cargo.lock
- query_server/query/src/extension/analyse/mod.rs
- query_server/query/src/extension/analyse/transform_bottom_func_to_topk_node.rs
- query_server/query/src/extension/analyse/transform_time_window.rs
- query_server/query/src/extension/analyse/transform_topk_func_to_topk_node.rs
- query_server/query/src/extension/logical/optimizer_rule/mod.rs
- query_server/query/src/extension/logical/plan_node/expand.rs
- query_server/query/src/sql/analyzer.rs
- query_server/query/src/sql/logical/optimizer.rs
- query_server/query/src/sql/planner.rs
- query_server/test/cases/function/bottom.result
- query_server/test/cases/function/topk.result
Move some optimization rules to the analyzer stage.
> adapt to datafusion's analyzer

- Cargo.lock
- Cargo.toml
- meta/Cargo.toml
- meta/start_meta.sh
- meta/tests/cluster/main.rs
> [Test]Add meta cases

- tskv/src/compaction/flush.rs
Closes #.
Speed up flushing by remove `if` statement in iterations.
> feat(flush): split values by max_level_ts before iteration

- Cargo.lock
- query_server/query/src/extension/analyse/transform_time_window.rs
- query_server/query/src/extension/expr/mod.rs
- query_server/query/src/extension/expr/window/time_window.rs
- query_server/query/src/sql/analyzer.rs
- query_server/sqllogicaltests/cases/function/time_window.slt
- query_server/sqllogicaltests/cases/stream/basic.slt
- query_server/test/cases/tsbench/avg_daily_driving_duration.result
- query_server/test/cases/tsbench/avg_daily_driving_duration.sql
```
time_window(time, <String>[, <String> [, String]]) -> time_window(time, <Interval>[, <Interval> [, Timestamp]])
```
> Synchronize documents, thanks @ZuoTiJia
> refactor: time_window signature

- Cargo.lock
- query_server/query/Cargo.toml
- query_server/query/src/extension/analyse/mod.rs
- query_server/query/src/extension/analyse/transform_gapfill/mod.rs
- query_server/query/src/extension/analyse/transform_gapfill/range_predicate.rs
- query_server/query/src/extension/expr/mod.rs
- query_server/query/src/extension/expr/scalar_function/gapfill.rs
- query_server/query/src/extension/expr/scalar_function/interpolate.rs
- query_server/query/src/extension/expr/scalar_function/locf.rs
- query_server/query/src/extension/expr/scalar_function/mod.rs
- query_server/query/src/extension/expr/window/mod.rs
- query_server/query/src/extension/expr/window/time_window.rs
- query_server/query/src/extension/logical/plan_node/gapfill.rs
- query_server/query/src/extension/logical/plan_node/mod.rs
- query_server/query/src/extension/physical/plan_node/gapfill/algo.rs
- query_server/query/src/extension/physical/plan_node/gapfill/algo/interpolate.rs
- query_server/query/src/extension/physical/plan_node/gapfill/buffered_input.rs
- query_server/query/src/extension/physical/plan_node/gapfill/mod.rs
- query_server/query/src/extension/physical/plan_node/gapfill/params.rs
- query_server/query/src/extension/physical/plan_node/gapfill/stream.rs
- query_server/query/src/extension/physical/plan_node/mod.rs
- query_server/query/src/extension/physical/transform_rule/gapfill.rs
- query_server/query/src/extension/physical/transform_rule/mod.rs
- query_server/query/src/extension/utils.rs
- query_server/query/src/sql/analyzer.rs
- query_server/query/src/sql/physical/planner.rs
- query_server/sqllogicaltests/cases/function/gapfill.slt
inspired by influxdb_iox
Closes #.
> feat: implement gap filling

- query_server/test/cases/sys_table/cluster_schema/tenants.result
- query_server/test/cases/sys_table/cluster_schema/tenants.sql
> sys_table tenants ADD cases

- query_server/query/src/data_source/mod.rs
- query_server/query/src/data_source/sink/obj_store/mod.rs
- query_server/query/src/data_source/sink/tskv.rs
- query_server/query/src/extension/physical/plan_node/table_writer.rs
- query_server/spi/src/query/datasource/mod.rs
- query_server/test/cases/dml/copy_into/copy_into_location.result
- query_server/test/cases/dml/copy_into/copy_into_location.sql
Add task id to the exported file name to prevent repeated export data from being overwritten
Closes #1131 .
> fix: add task id prefix to the exported file

- common/trace/src/lib.rs
Closes #.
The `DEBUG` level logging prints too much irrelevant text.
Add a `Targets` filter to tracing sub-registry, which defines all we want to print.
> feat(log): add tracing target filter

- Cargo.lock
- Cargo.toml
- common/error_code/error_code_macro/Cargo.toml
- common/lru_cache/Cargo.toml
- common/memory_pool/Cargo.toml
> version 2.3

- tskv/src/kvcore.rs
- tskv/src/memcache.rs
> feat(tskv): bring release of cache partition rwlock ahead

- common/metrics/src/metric.rs
- query_server/sqllogicaltests/cases/sys_table/usage_schema/coord_data_in.slt
- query_server/sqllogicaltests/cases/sys_table/usage_schema/setup.slt
- query_server/sqllogicaltests/cases/sys_table/usage_schema/vnode_cache_size.slt
> fix: store metrics

- query_server/query/src/dispatcher/query_tracker.rs
> fix: unable to track sql statements

- common/models/src/schema.rs
- meta/src/store/state_machine.rs
> fix bucket start/end time precision match database precision

- query_server/query/src/data_source/sink/obj_store/mod.rs
- query_server/query/src/extension/mod.rs
> fix: copy into location export empty file

- common/models/src/schema.rs
- query_server/query/src/execution/ddl/alter_table.rs
https://github.com/cnosdb/cnosdb/issues/1148
Closes #.
https://github.com/cnosdb/cnosdb/issues/1148
> check column encoding when alter table

- common/models/src/meta_data.rs
> fix compatibility issue

- common/models/src/meta_data.rs
> fix allocation replication set policy error

- config/src/query_config.rs
- coordinator/src/hh_queue.rs
- coordinator/src/reader/query_executor.rs
- coordinator/src/service.rs
- coordinator/src/writer.rs
- main/src/rpc/tskv.rs
- tskv/src/file_system/queue.rs
>  Illegal data no longer wrtten to handoff && config read/write timeout

- main/src/http/http_service.rs
> fix(server): api_v1_write not work when use https

- query_server/query/benches/aggregate_function.rs
- query_server/query/benches/data_utils/mod.rs
- query_server/query/src/extension/expr/aggregate_function/mod.rs
- query_server/query/src/extension/expr/aggregate_function/sample.rs
- query_server/query/src/extension/expr/func_manager.rs
- query_server/query/src/extension/expr/mod.rs
- query_server/sqllogicaltests/cases/function/sample.slt
> feat: implement sample function

- config/src/hinted_off_config.rs
- coordinator/src/hh_queue.rs
> support mutil-thread delivery hinted handoff

- Cargo.lock
- meta/Cargo.toml
- meta/src/client.rs
- query_server/query/src/metadata/cluster_schema_provider/builder/tenants.rs
- query_server/query/src/metadata/cluster_schema_provider/builder/users.rs
- query_server/query/src/metadata/cluster_schema_provider/factory/tenants.rs
- query_server/query/src/metadata/cluster_schema_provider/factory/users.rs
- query_server/query/src/metadata/cluster_schema_provider/mod.rs
- query_server/query/src/metadata/information_schema_provider/builder/columns.rs
- query_server/query/src/metadata/information_schema_provider/builder/database_privileges.rs
- query_server/query/src/metadata/information_schema_provider/builder/databases.rs
- query_server/query/src/metadata/information_schema_provider/builder/enabled_roles.rs
- query_server/query/src/metadata/information_schema_provider/builder/members.rs
- query_server/query/src/metadata/information_schema_provider/builder/queries.rs
- query_server/query/src/metadata/information_schema_provider/builder/roles.rs
- query_server/query/src/metadata/information_schema_provider/builder/tables.rs
- query_server/query/src/metadata/information_schema_provider/factory/columns.rs
- query_server/query/src/metadata/information_schema_provider/factory/database_privileges.rs
- query_server/query/src/metadata/information_schema_provider/factory/databases.rs
- query_server/query/src/metadata/information_schema_provider/factory/enabled_roles.rs
- query_server/query/src/metadata/information_schema_provider/factory/members.rs
- query_server/query/src/metadata/information_schema_provider/factory/queries.rs
- query_server/query/src/metadata/information_schema_provider/factory/roles.rs
- query_server/query/src/metadata/information_schema_provider/factory/tables.rs
- query_server/query/src/metadata/information_schema_provider/mod.rs
- query_server/query/src/metadata/mod.rs
> fix issue 1184, change http client to reqwest

- coordinator/src/reader/mod.rs
- coordinator/src/reader/query_executor.rs
> fix: ParallelMergeStream not catch None

- README.md
- README_CN.md
> fix(docs): fix some invalid links

- tskv/src/index/binlog.rs
- tskv/src/index/mod.rs
- tskv/src/index/ts_index.rs
- tskv/src/main.rs
> tools: repair damaged index log file, usage: tskv repair --index filename

- coordinator/src/hh_queue.rs
- coordinator/src/lib.rs
- coordinator/src/reader/status_listener.rs
- coordinator/src/service.rs
- coordinator/src/vnode_mgr.rs
- main/src/rpc/tskv.rs
- meta/src/store/state_machine.rs
> improve move vnode: the vnode id not motify fix for hinted handoff routing error

- tskv/src/compaction/compact.rs
- tskv/src/summary.rs
- tskv/src/tseries_family.rs
> fix(tskv): remove cached reader when dropping ColumnFile.

- README.md
- README_CN.md
> [MINOR] fix doc

- .gitlab-ci.yml
- benchmark/benchmark.sh
- benchmark/generate_metadata.sh
- benchmark/hits/run_queries.sh
- benchmark/shell_env.sh
- benchmark/update-results.sh
> Modify benchmark and gitlab-ci

- query_server/query/src/prom/remote_server.rs
> remove prom remote write request debug log

- .github/workflows/github_mirror_to_gitlab.yml
- .github/workflows/github_mirror_to_gitlab_pr.yml
> Add action to trigger benchmark with the keyword "begin benchmark"

- .github/workflows/github_mirror_to_gitlab.yml
- .github/workflows/github_mirror_to_gitlab_pr.yml
> Upgrade the action checkout version

- .github/workflows/github_mirror_to_gitlab.yml
- .github/workflows/github_mirror_to_gitlab_pr.yml
> Change shallow cloning to deep cloning

- .github/workflows/github_mirror_to_gitlab_pr.yml
> Specify specific git hash code to sync to gitlab

- .github/actions/setup-builder/action.yaml
- .github/workflows/makefile.yml
- Cargo.lock
- Cargo.toml
- coordinator/src/errors.rs
- coordinator/src/hh_queue.rs
- coordinator/src/reader/mod.rs
- coordinator/src/reader/table_scan/opener.rs
- coordinator/src/reader/tag_scan/opener.rs
- coordinator/src/writer.rs
- main/Cargo.toml
- query_server/test/script/start_and_test.sh
- query_server/test/script/start_and_test_all.sh
> reduce ci disk usage

- tskv/src/index/ts_index.rs
https://github.com/cnosdb/cnosdb/issues/1300
Related #.
> fix: generate duplicate series id

- query_server/query/src/extension/expr/aggregate_function/sample.rs
- query_server/sqllogicaltests/cases/function/sample.slt
> fix: sample n

- .github/pull_request_template.md
> chore: add required list to check before merging code

- query_server/test/cases/sys_table/cluster_schema/tenants.result
- query_server/test/cases/sys_table/cluster_schema/tenants.sql
> [test]Add drop tenant test case for issue [#1302]

- README.md
> chore: add the discord icon to READMD.md

- .github/workflows/docker_build_and_push_manual.yml
- .github/workflows/docker_build_and_push_on_time.yml
> [ci]Added docker image arm architecture

- .github/actions/setup-builder/action.yaml
- .github/tools/free_disk_space.sh
- .github/workflows/makefile.yml
> ci: free disk space

- .github/workflows/github_mirror_to_gitlab.yml
- .github/workflows/github_mirror_to_gitlab_pr.yml
- .gitlab-ci.yml
- benchmark/hits/prepare_data.sh
- benchmark/hits/sql/create.sql
- benchmark/shell_env.sh
> [ci]related script changes, gitlab migration

- Cargo.lock
- common/limiter_bucket/Cargo.toml
- common/limiter_bucket/src/rate_bucket.rs
json deserialization failure causes limit request to fail.
> fix: fix rate_bucket json deserialize

- Cargo.lock
https://cnosdb-admin.teleport.cnosdb.com/benchmark-hits/hits_cc46710.html
fix q8 q10 q11 q13
cherry pick df's bugfix
* Field not found, releated https://github.com/apache/arrow-datafusion/issues/6790
[//]: # (There is no need to duplicate the description in the …
> update datafusion dep commit id

- common/models/src/series_info.rs
- config/config_8902.toml
- tskv/src/database.rs
- tskv/src/index/binlog.rs
- tskv/src/index/ts_index.rs
- tskv/src/kvcore.rs
Related #.
Add some unit test cases for tskv index.
Delete wrong method `Database:: get_table_sids()` .
Repair features that used `Database:: get_table_sids()`.
> [Fix] Fix DROP TABLE fetched unexpected series id

- .github/workflows/makefile.yml
- query_server/test/script/start_and_test.sh
- query_server/test/script/start_and_test_all.sh
- tskv/src/file_utils.rs
- tskv/src/kvcore.rs
> ci: fix ci runtime config 

- tskv/src/kvcore.rs
Fix: dropping table prints all series_ids, column_ids to log.
> [Fix] Reduce logs in drop table methods

- .gitlab-ci.yml
> [ci]archive each benchmark log

- Cargo.lock
- query_server/query/src/extension/expr/aggregate_function/example.rs
- query_server/query/src/extension/expr/aggregate_function/mod.rs
- query_server/query/src/extension/expr/aggregate_function/sample.rs
- query_server/query/src/extension/expr/aggregate_function/state_agg/compact_state_agg.rs
- query_server/query/src/extension/expr/aggregate_function/state_agg/mod.rs
- query_server/query/src/lib.rs
- query_server/sqllogicaltests/cases/function/compact_state_agg.slt
> feat: implement aggregate func compact_state_agg

- coordinator/src/writer.rs
- meta/src/error.rs
- meta/src/model/meta_tenant.rs
- meta/src/store/command.rs
- meta/src/store/state_machine.rs
- tskv/src/schema/schemas.rs
> fix : insert lineprotocol error

- clippy.toml
- common/models/src/schema.rs
- meta/src/model/meta_tenant.rs
- meta/src/store/state_machine.rs
- tskv/src/database.rs
- tskv/src/schema/schemas.rs
> fix : line protocol schema change conflict

- Cargo.toml
- client/src/exec.rs
- common/models/src/predicate/domain.rs
- common/models/src/predicate/transformation.rs
- common/models/src/schema.rs
- common/protocol_parser/src/open_tsdb/parser.rs
- common/protos/build.rs
- common/utils/src/bitset.rs
- common/utils/src/pprof_tools.rs
- e2e_test/src/flight_sql.rs
- main/src/tcp/tcp_service.rs
- query_server/query/benches/data_utils/mod.rs
- query_server/query/src/data_source/batch/tskv.rs
- query_server/query/src/execution/ddl/create_external_table.rs
- query_server/query/src/instance.rs
- query_server/query/src/sql/planner.rs
- query_server/test/src/groups.rs
- tskv/src/compaction/check.rs
- tskv/src/compaction/compact.rs
- tskv/src/compaction/flush.rs
- tskv/src/compute/count.rs
- tskv/src/memcache.rs
- tskv/src/reader/iterator.rs
- tskv/src/summary.rs
- tskv/src/tsm/codec/integer.rs
- tskv/src/tsm/reader.rs
- tskv/src/tsm/writer.rs
- tskv/src/wal/mod.rs
> improve: fix cargo warning

- .github/workflows/github_mirror_to_gitlab_pr.yml
> [ci]remove printed comments to avoid security breaches

- .github/actions/setup-builder/action.yaml
- .github/workflows/makefile.yml
* ci: use mold to speed link
Related #.
Try to speed up CI compilation
> ci: add sccache to speed compile

- coordinator/src/reader/mod.rs
- coordinator/src/service.rs
- meta/src/limiter/local_request_limiter.rs
- meta/src/limiter/mod.rs
- meta/src/model/meta_admin.rs
- tskv/src/reader/iterator.rs
> fix: fix check_writes error

- query_server/query/src/extension/expr/aggregate_function/gauge/gauge_agg.rs
- query_server/query/src/extension/expr/aggregate_function/gauge/mod.rs
- query_server/query/src/extension/expr/aggregate_function/mod.rs
- query_server/query/src/extension/expr/scalar_function/gauge/delta.rs
- query_server/query/src/extension/expr/scalar_function/gauge/mod.rs
- query_server/query/src/extension/expr/scalar_function/mod.rs
- query_server/query/src/extension/expr/scalar_function/utils.rs
- query_server/sqllogicaltests/cases/function/gauge/delta.slt
- query_server/sqllogicaltests/cases/function/gauge/gauge_agg.slt
> feat: support scalar function delta

- query_server/query/src/extension/expr/aggregate_function/gauge/gauge_agg.rs
- query_server/query/src/extension/expr/aggregate_function/gauge/mod.rs
- query_server/query/src/extension/expr/aggregate_function/mod.rs
- query_server/query/src/extension/expr/aggregate_function/state_agg/compact_state_agg.rs
- query_server/query/src/extension/expr/expr_utils.rs
- query_server/query/src/extension/expr/scalar_function/gauge/mod.rs
- query_server/query/src/extension/expr/scalar_function/gauge/time_delta.rs
- query_server/query/src/extension/expr/scalar_function/utils.rs
- query_server/sqllogicaltests/cases/function/gauge/time_delta.slt
> feat: support scalar function time_delta

- Cargo.lock
- Cargo.toml
- common/protocol_parser/src/lib.rs
- common/protocol_parser/src/open_tsdb/parser.rs
- common/protos/build.rs
- common/protos/proto/vector_event.proto
- common/protos/src/generated/protobuf_generated/mod.rs
- common/protos/src/generated/protobuf_generated/vector.rs
- config/config.toml
- config/config_8902.toml
- config/config_8912.toml
- config/src/cluster_config.rs
- config/src/lib.rs
- e2e_test/src/lib.rs
- e2e_test/src/vector_service_test.rs
- main/Cargo.toml
- main/src/main.rs
- main/src/server.rs
- main/src/tcp/tcp_service.rs
- main/src/vector/mod.rs
- main/src/vector/vector_grpc_service.rs
- main/src/vector/vector_server.rs
> feature : adapt vector

- .github/workflows/makefile.yml
> ci: migrating part of ci

- query_server/query/src/metadata/mod.rs
- query_server/sqllogicaltests/cases/sys_table/usage_schema/usage_schema_privilege.slt
- query_server/test/cases/sys_table/usage_schema/coord_data_in.sql
- query_server/test/cases/sys_table/usage_schema/coord_data_out.sql
- query_server/test/cases/sys_table/usage_schema/usage_schema_privilege.result
- query_server/test/cases/sys_table/usage_schema/usage_schema_privilege.sql
- query_server/test/cases/sys_table/usage_schema/user_queries.sql
- query_server/test/cases/sys_table/usage_schema/user_writes.sql
- query_server/test/cases/sys_table/usage_schema/vnode_cache_size.sql
- query_server/test/cases/sys_table/usage_schema/vnode_disk_storage.sql
> fix: allow modify usage_schema database

- .github/workflows/community-latest_docker_build_and_push.yml
- .github/workflows/makefile.yml
> ci: change docker build to 18:00 every day from Monday to Friday

- .github/workflows/makefile.yml
- Makefile
- e2e_test/src/coordinator_tests.rs
- main/src/meta_single/meta_service.rs
- meta/src/model/meta_admin.rs
- meta/src/service/mod.rs
- meta/src/store/command.rs
- meta/src/store/state_machine.rs
- meta/tests/cluster/main.rs
- query_server/query/src/metadata/mod.rs
- query_server/sqllogicaltests/cases/sys_table/usage_schema/usage_schema_privilege.slt
- query_server/test/cases/sys_table/usage_schema/coord_data_in.sql
- query_server/test/cases/sys_table/usage_schema/coord_data_out.sql
- query_server/test/cases/sys_table/usage_schema/usage_schema_privilege.result
- query_server/test/cases/sys_table/usage_schema/usage_schema_privilege.sql
- query_server/test/cases/sys_table/usage_schema/user_queries.sql
- query_server/test/cases/sys_table/usage_schema/user_writes.sql
- query_server/test/cases/sys_table/usage_schema/vnode_cache_size.sql
- query_server/test/cases/sys_table/usage_schema/vnode_disk_storage.sql
> Merge 2.3 Bug Fixes

- query_server/query/src/extension/expr/aggregate_function/state_agg/state_agg_data.rs
- query_server/query/src/extension/expr/scalar_function/duration_in.rs
- query_server/query/src/extension/expr/scalar_function/mod.rs
- query_server/query/src/extension/expr/scalar_function/state_at.rs
- query_server/sqllogicaltests/cases/function/state_agg/state_at.slt
> feat: impl state_at for state_agg

- common/protocol_parser/src/lib.rs
- common/protocol_parser/src/line_protocol/parser.rs
- main/src/vector/vector_server.rs
> fix: line protocol parser '\n' error

- query_server/query/src/execution/ddl/drop_global_object.rs
> [fix]when drop tenant, do not drop data(#1311)

- e2e_test/src/https_api_tests.rs
- e2e_test/src/lib.rs
> ci: add https_api_tests

- query_server/query/benches/aggregate_function.rs
- query_server/query/src/extension/expr/aggregate_function/mod.rs
- query_server/query/src/extension/expr/aggregate_function/mode.rs
- query_server/sqllogicaltests/cases/function/mode.slt
> feat: support aggregate function mode

- query_server/sqllogicaltests/cases/data_tests/data_ttl.slt
- query_server/sqllogicaltests/cases/data_tests/get_last_data.slt
> ci: add sql test cases

- main/src/vector/vector_server.rs
> refactor : map array to string

- query_server/sqllogicaltests/cases/function/gauge/rate.slt
- query_server/sqllogicaltests/cases/function/mode.slt
- query_server/sqllogicaltests/src/main.rs
- query_server/test/cases/data_type/type_conversion/double.result
- query_server/test/cases/data_type/type_conversion/double.sql
- query_server/test/cases/ddl/describe_database.result
- query_server/test/cases/ddl/describe_database.sql
- query_server/test/cases/dml/insert/insert_select.result
- query_server/test/cases/dml/insert/insert_select.sql
- query_server/test/cases/dml/insert/insert_values.result
- query_server/test/cases/dml/insert/insert_values.sql
- query_server/test/cases/dql/empty_table.result
- query_server/test/cases/dql/empty_table.sql
- query_server/test/src/case.rs
> fix: modify the cases to be repeatable

- Cargo.lock
- Cargo.toml
- query_server/test/Cargo.toml
- query_server/test/cases/data_type/type_conversion/double.result
- query_server/test/cases/data_type/type_conversion/double.sql
- query_server/test/cases/data_type/type_conversion/timestamp.result
- query_server/test/cases/data_type/type_conversion/timestamp.sql
- query_server/test/cases/ddl/describe_database.sql
- query_server/test/cases/dml/copy_into/copy_into_location.sql
- query_server/test/cases/dql/empty_table.result
- query_server/test/cases/dql/empty_table.sql
- query_server/test/src/client.rs
- query_server/test/src/db_request.rs
> improve: enable shell scripts to be added to test cases

- Cargo.lock
- common/memory_pool/src/lib.rs
- common/utils/Cargo.toml
- tskv/benches/kvcore_bench.rs
- tskv/src/compaction/check.rs
- tskv/src/compaction/flush.rs
- tskv/src/compaction/picker.rs
- tskv/src/compute/count.rs
- tskv/src/context.rs
- tskv/src/kv_option.rs
- tskv/src/kvcore.rs
- tskv/src/tseries_family.rs
- tskv/src/version_set.rs
- tskv/src/wal/mod.rs
- tskv/src/wal/writer.rs
- tskv/tests/test_kvcore_interface.rs
> feat: split wal by vnode

- tskv/src/database.rs
- tskv/src/file_system/file/async_file.rs
- tskv/src/index/binlog.rs
- tskv/src/index/ts_index.rs
> improve: optimize build index

- Cargo.lock
- common/http_protocol/Cargo.toml
- common/http_protocol/src/response.rs
> improve: change big dependency 'models' to small dependency 'error_code'

- common/metrics/src/lib.rs
- common/metrics/src/metric.rs
- common/metrics/src/metric_register.rs
- common/metrics/src/prom_reporter.rs
- common/metrics/src/reporter.rs
- coordinator/src/metrics.rs
* change &'static str to Cow<'static, str>
Related #1474
> improve: Add histogram Line Protocol export

- tskv/src/database.rs
- tskv/src/index/ts_index.rs
> fix : data lose when create tsf

- query_server/query/benches/aggregate_function.rs
- query_server/query/src/extension/expr/aggregate_function/increase.rs
- query_server/query/src/extension/expr/aggregate_function/mod.rs
- query_server/sqllogicaltests/cases/function/increase.slt
> feat: impl aggregate function `increase`

- tskv/src/index/ts_index.rs
> doc: add comments to TSIndex struct

- tskv/src/reader/iterator.rs
> fix: cancel query tasks on tskv

- meta/src/limiter/mod.rs
> doc: add limiter description

- .github/workflows/makefile.yml
- e2e_test/src/flight_sql.rs
- e2e_test/src/kv_service_tests.rs
> ci: enable e2e test

- tskv/src/schema/schemas.rs
> fix : retry after update table conflict

- common/models/src/meta_data.rs
- meta/src/model/meta_tenant.rs
- query_server/query/src/execution/ddl/alter_database.rs
> fix: fix alter database

- client/src/exec.rs
- client/src/main.rs
- common/utils/src/bitset.rs
- coordinator/src/hh_queue.rs
- coordinator/src/service.rs
- main/src/meta_single/meta_service.rs
- meta/src/model/meta_tenant.rs
- meta/src/service/mod.rs
- query_server/query/src/extension/analyse/transform_bottom_func_to_topk_node.rs
- query_server/query/src/extension/analyse/transform_topk_func_to_topk_node.rs
- query_server/query/src/extension/physical/plan_node/expand.rs
- query_server/query/src/metadata/mod.rs
rustc 1.74.0-nightly (ca2b74f1a 2023-09-14)
> fix: cargo clippy

- .github/workflows/build_package_and_push.yml
- releng/build_package.sh
- releng/scripts/cnosdb-meta/after-install.sh
- releng/scripts/cnosdb-meta/after-remove.sh
- releng/scripts/cnosdb-meta/before-install.sh
- releng/scripts/cnosdb-meta/cnosdb-meta.service
- releng/scripts/cnosdb-meta/init.sh
- releng/scripts/cnosdb/after-install.sh
- releng/scripts/cnosdb/after-remove.sh
- releng/scripts/cnosdb/before-install.sh
- releng/scripts/cnosdb/cnosdb.service
- releng/scripts/cnosdb/init.sh
- releng/scripts/cnosdb/logrotate
> ci: add github action packaging script

- coordinator/src/metrics.rs
- main/src/http/http_service.rs
* fix metrics export lp type error
Related #1505
> fix: fix http metrics field order error

- query_server/query/src/dispatcher/persister.rs
- query_server/query/src/extension/logical/plan_node/stream_scan.rs
- query_server/query/src/extension/logical/plan_node/watermark.rs
- query_server/sqllogicaltests/cases/stream/basic.slt
- query_server/sqllogicaltests/src/utils/normalize.rs
1. Fix filter is not pushed down in stream plan
2. Use serde json to replace bincode to serialize query info. Caused by https://github.com/bincode-org/bincode/issues/326
[//]: # (There is no need to duplicate the description in the issue here, but it is sometimes …
> fix: stream plan not perform filter pushdown

- e2e_test/src/flight_sql.rs
- main/src/flight_sql/flight_sql_server.rs
> fix: arrow flight sql jdbc api: getCatalogs getSchemas getTables

- e2e_test/src/flight_sql.rs
- main/src/flight_sql/flight_sql_server.rs
> [Patch] bug fixes from main to LTS/2.3 

- query_server/query/src/execution/ddl/alter_table.rs
- query_server/sqllogicaltests/cases/ddl/rename_field.slt
> feat: support rename field

- main/src/flight_sql/flight_sql_server.rs
> fix: arrow flight sql getTables api

- .github/workflows/community-2.3_docker_build_and_push.yml
> ci: update community-2.3_docker_build_and_push.yml for LTS/2.3

- client/src/exec.rs
> fix: fix cli array out-of-bounds access

- common/protocol_parser/src/lib.rs
- common/protocol_parser/src/line_protocol/parser.rs
- common/protocol_parser/src/open_tsdb/parser.rs
> fix: parser line protocol error

- common/models/src/meta_data.rs
- meta/src/error.rs
- meta/src/model/meta_admin.rs
- meta/src/store/state_machine.rs
- query_server/sqllogicaltests/src/utils/normalize.rs
- tskv/src/summary.rs
- tskv/src/tseries_family.rs
- tskv/tests/test_kvcore_interface.rs
> fix: Fix the problem of not reporting NodeMetrics in time

- .github/workflows/community-latest_docker_build_and_push.yml
- Dockerfile_for_k8s
- endpoint.sh
> ci: add build k8s image and push to aliyun image repository

- .github/workflows/community-latest_docker_build_and_push.yml
> ci: update docker image naming rule

- .github/workflows/community-tag_docker_build_and_push.yml
> ci: rename docker build yaml

- main/src/rpc/tskv.rs
- query_server/query/src/execution/ddl/alter_table.rs
- tskv/src/kvcore.rs
> fix: update table cause lose data

- .github/workflows/community-tag_docker_build_and_push.yml
> ci: update docker image building script

- .gitlab-ci.yml
> ci: fix benchmark too many open files

- config/config.toml
- config/src/hinted_off_config.rs
- config/src/log_config.rs
- config/src/security_config.rs
- config/src/storage_config.rs
- config/src/wal_config.rs
> ci: update default config file

- query_server/query/src/extension/expr/scalar_function/gis/mod.rs
- query_server/query/src/extension/expr/scalar_function/gis/st_area.rs
- query_server/sqllogicaltests/cases/function/gis/st_area.slt
> feat: impl `st_area` function

- .github/workflows/build_package_and_push.yml
> ci: update packaging script

- common/models/src/auth/user.rs
> fix: fix password verify failed

- query_server/query/src/extension/analyse/transform_time_window.rs
- query_server/sqllogicaltests/cases/function/time_window.slt
> fix: fix `time_window` function cannot handle constant cast expression

- tskv/src/memcache.rs
- tskv/src/reader/iterator.rs
- tskv/src/tsm/block.rs
there are some clone
https://github.com/cnosdb/cnosdb/blob/5378a3d6e12ccde5a8c2236eca1349caf6f7eb86/tskv/src/reader/iterator.rs#L744-L747
https://github.com/cnosdb/cnosdb/blob/5378a3d6e12ccde5a8c2236eca1349caf6f7eb86/tskv/src/reader/iterator.rs#L88-L95
> improve: decrease clone

- common/limiter_bucket/src/rate_bucket.rs
- meta/src/limiter/local_request_limiter.rs
- meta/src/store/storage.rs
* add test
* add some debug log of limiter
Related #1562
> fix: fix rate bucket refill

- query_server/query/src/sql/planner.rs
> fix: Confusing error message

- tskv/src/kvcore.rs
> fix : restart recover invalid data

- meta/src/model/meta_admin.rs
- meta/src/store/storage.rs
- query_server/query/src/execution/ddl/drop_global_object.rs
- query_server/spi/src/lib.rs
- query_server/test/cases/dcl/alter_user.result
- query_server/test/cases/dcl/alter_user.sql
> fix: forbidden drop root user

- tskv/src/compaction/check.rs
- tskv/src/kvcore.rs
- tskv/src/schema/schemas.rs
> fix: drop column case tskv get empty db

- meta/src/store/command.rs
https://github.com/cnosdb/cnosdb/issues/1401
Related #.
> fix: /cluster/users/user change not notify to server [#1401]

- meta/src/service/http.rs
- meta/src/service/init.rs
- meta/src/service/server.rs
- meta/src/service/single.rs
- meta/src/store/storage.rs
https://github.com/cnosdb/cnosdb/issues/1495
Related #.
> fix: meta create duplicate data version[#1495]

- Cargo.lock
- query_server/sqllogicaltests/cases/function/gis/st_asbinary.slt
> fix: fix check scalar args check

- coordinator/src/service.rs
- query_server/query/src/execution/ddl/create_database.rs
- query_server/query/src/execution/ddl/create_tenant.rs
- query_server/query/src/metadata/mod.rs
- query_server/query/src/metadata/usage_schema_provider/mod.rs
- query_server/query/src/sql/planner.rs
- query_server/sqllogicaltests/cases/sys_table/system_database.slt
> fix: fix create system database `usage_schema`

- query_server/sqllogicaltests/cases/dml/update_tag.slt
- tskv/src/index/ts_index.rs
- tskv/src/lib.rs
> fix: update set tag value

- common/protos/proto/kv_service.proto
- common/protos/src/generated/protobuf_generated/kv_service.rs
- coordinator/src/lib.rs
- coordinator/src/raft/mod.rs
- coordinator/src/raft/writer.rs
- coordinator/src/service.rs
- coordinator/src/service_mock.rs
- main/src/rpc/tskv.rs
> extend raft write interface

- common/metrics/src/label.rs
- main/src/http/api_type.rs
- main/src/http/http_service.rs
- main/src/http/metrics.rs
- main/src/http/mod.rs
- query_server/test/cases/sys_table/usage_schema/http_metrics.result
- query_server/test/cases/sys_table/usage_schema/http_metrics.sql
> fix: http metrics add new TAG `api`

- .github/tools/install_dependencies.sh
- .github/workflows/build_package_and_push.yml
> ci: add windows packaging

- common/models/src/schema.rs
- coordinator/src/errors.rs
- coordinator/src/lib.rs
- coordinator/src/resource_manager.rs
- coordinator/src/service.rs
- coordinator/src/service_mock.rs
- query_server/query/src/execution/ddl/alter_table.rs
- query_server/query/src/execution/ddl/drop_database_object.rs
- query_server/query/src/execution/ddl/drop_global_object.rs
- query_server/query/src/execution/ddl/drop_tenant_object.rs
- query_server/query/src/execution/ddl/recover_database.rs
- query_server/query/src/execution/ddl/recover_tenant.rs
- query_server/test/cases/ddl/drop_and_recover_tenant.result
- query_server/test/cases/ddl/drop_and_recover_tenant.sql
> feat: move UpdateTagValue feature to ResourceManager

- .github/tools/install_dependencies.sh
- .github/workflows/compatibility_test.yaml
- e2e_test/src/independent/mod.rs
- e2e_test/src/independent/restart_tests.rs
- e2e_test/src/utils.rs
- query_server/test/cases/dcl/user_access.result
- query_server/test/cases/dcl/user_access.sql
- query_server/test/cases/sys_table/cluster_schema/tenants.result
- query_server/test/cases/sys_table/cluster_schema/tenants.sql
test: add new test cases
Related #.
> ci: add compatibility test

- meta/src/store/state_machine.rs
- query_server/query/src/execution/ddl/drop_global_object.rs
> fix: drop tenant not drop members bug

- Cargo.lock
- Cargo.toml
- coordinator/src/writer.rs
- main/src/rpc/grpc_service.rs
> feat: add support for grpc compression

- coordinator/src/resource_manager.rs
- e2e_test/src/independent/restart_tests.rs
- e2e_test/src/utils.rs
- meta/src/model/meta_tenant.rs
- query_server/query/src/execution/ddl/drop_tenant_object.rs
- tskv/src/schema/schemas.rs
> fix: restart get actual database schema

- tskv/src/tsm/block.rs
> [Fix] tskv iterator sometimes returns more data than expected

- coordinator/src/service.rs
- query_server/query/src/extension/analyse/transform_update.rs
- query_server/query/src/extension/physical/plan_node/update_tag.rs
Related #1060 .
Remove the `time` column from projection on TableScan, retain only the tag columns, and ensure that the data scanning method is TagScan to reduce the amount of data scanning.
[//]: # (There is no need to duplicate the description in the issue here, …
> refactor: the way to scan data in the update tag plan

- tskv/src/compaction/compact.rs
- tskv/src/compaction/job.rs
- tskv/src/error.rs
- tskv/src/kvcore.rs
- tskv/src/tseries_family.rs
- tskv/src/tsm/reader.rs
- tskv/src/tsm/tombstone.rs
Related #1594.
Stop Vnode compaction job when executing deletions, restart Vnode compaction when deletion done.
Remove method `ColumnFile::add_tombstone(field_ids, time_ranges)`, move this method into `TsmReader` which holds `Arc<TsmTombstone>`.
Add method `SuperVersion::add_tsm_tombstone(field_ids, time_ranges)` to reuse logic in kvcore.rs: **for each column files in each levels of current version in super version, get TsmReader from LRU cache and call `TsmReader::add_tombstone`**.
> [Fix] fix errors in execution of DELETE FROM TABLE.

- .github/tools/install_dependencies.sh
- .github/workflows/build_package_and_push.yml
> [LTS/2.3] ci: add windows packaging

- Cargo.lock
- e2e_test/src/independent/coordinator_tests.rs
- e2e_test/src/independent/restart_tests.rs
- e2e_test/src/utils.rs
> test: optimize e2e test

- config/src/deployment_config.rs
> fix: get_sys_mem unit error

- README.md
- README_CN.md
> chore: complete source code compilation

- Cargo.lock
- client/src/ctx.rs
> fix: cli write line protocol didn't show error message

- Cargo.lock
- common/models/src/schema.rs
- common/models/src/tag.rs
- tskv/Cargo.toml
- tskv/src/database.rs
- tskv/src/error.rs
- tskv/src/index/ts_index.rs
- tskv/src/kvcore.rs
- tskv/src/memcache.rs
- tskv/src/schema/error.rs
- tskv/src/schema/schemas.rs
- tskv/src/tseries_family.rs
> Refactor write

- meta/src/store/storage.rs
> fix: fix when drop user don't drop tenant member

- common/models/src/schema.rs
- query_server/query/src/execution/ddl/drop_global_object.rs
- query_server/spi/src/query/logical_planner.rs
- query_server/test/cases/ddl/drop_and_recover_tenant.result
- query_server/test/cases/ddl/drop_and_recover_tenant.sql
- query_server/test/cases/sys_table/cluster_schema/tenants.result
> feat: add tenant parameter for drop delay(#1640)

- common/models/src/schema.rs
- coordinator/src/resource_manager.rs
- coordinator/src/service.rs
- e2e_test/src/independent/restart_tests.rs
- meta/src/model/meta_admin.rs
- meta/src/model/meta_tenant.rs
- meta/src/store/command.rs
- meta/src/store/key_path.rs
- meta/src/store/storage.rs
- query_server/query/src/execution/ddl/alter_table.rs
- query_server/query/src/execution/ddl/drop_database_object.rs
- query_server/query/src/execution/ddl/drop_global_object.rs
- query_server/query/src/execution/ddl/drop_tenant_object.rs
- query_server/query/src/execution/ddl/recover_database.rs
- query_server/query/src/execution/ddl/recover_tenant.rs
- query_server/query/src/metadata/information_schema_provider/factory/resource_status.rs
- query_server/sqllogicaltests/cases/ddl/drop_and_recover_database.slt
1. ResourceOperator
Add annotation
Reduce unnecessary parameters
2. ResourceInfo
Ambiguous vec is removed, change to name: String
Add db name for permission validation
> refactor: ResourceManager code optimize

- .github/workflows/build_package_and_push.yml
- docker/Dockerfile
- docker/Dockerfile_meta
> [LST/2.3] ci: upload package to oss

- .github/workflows/build_package_and_push.yml
- docker/Dockerfile
- docker/Dockerfile_meta
- e2e_test/src/independent/restart_tests.rs
> ci: upload package to oss

- common/models/src/predicate/domain.rs
- common/protocol_parser/src/line_protocol/parser.rs
- main/src/http/encoding.rs
- query_server/query/src/execution/ddl/create_external_table.rs
- query_server/query/src/extension/analyse/transform_bottom_func_to_topk_node.rs
- query_server/query/src/extension/analyse/transform_topk_func_to_topk_node.rs
- query_server/query/src/extension/expr/aggregate_function/state_agg/state_agg_data.rs
- query_server/query/src/sql/planner.rs
- query_server/query/tests/datafusion.rs
- query_server/test/cases/ddl/create_external_table.result
- query_server/test/cases/ddl/create_external_table.sql
- tskv/src/compaction/flush.rs
> Fix external table

- main/src/http/http_service.rs
- main/src/http/mod.rs
- meta/src/store/storage.rs
- query_server/test/cases/ddl/drop_and_recover_tenant.result
- query_server/test/cases/sys_table/cluster_schema/tenants.result
- query_server/test/cases/sys_table/cluster_schema/tenants.sql
> fix: fix `Tenant not found` return http status code 500

- coordinator/src/raft/manager.rs
- tskv/src/record_file/reader.rs
- tskv/src/wal/raft_store.rs
https://github.com/cnosdb/cnosdb/issues/1690
Related #.
> fix write in raft mode: WalTruncated and restart lost data

- Cargo.lock
- common/protos/Cargo.toml
- common/protos/src/lib.rs
- coordinator/src/raft/manager.rs
- coordinator/src/raft/mod.rs
- coordinator/src/raft/writer.rs
- coordinator/src/reader/table_scan/opener.rs
- coordinator/src/reader/tag_scan/opener.rs
- coordinator/src/service.rs
- coordinator/src/vnode_mgr.rs
- coordinator/src/writer.rs
- main/src/rpc/grpc_service.rs
> fix: fix grpc size limit

- Cargo.lock
- meta/Cargo.toml
- meta/src/bin/main.rs
- meta/src/lib.rs
- meta/src/service/server.rs
- meta/src/signal.rs
> refactor: meta receive ctrl-c

- common/models/src/schema.rs
- common/models/src/series_info.rs
- common/protos/proto/kv_service.proto
- common/protos/src/generated/protobuf_generated/kv_service.rs
- coordinator/src/raft/mod.rs
- coordinator/src/resource_manager.rs
- coordinator/src/service.rs
- main/src/rpc/tskv.rs
- query_server/query/src/execution/ddl/alter_table.rs
- tskv/src/database.rs
- tskv/src/engine_mock.rs
- tskv/src/error.rs
- tskv/src/index/ts_index.rs
- tskv/src/kvcore.rs
- tskv/src/lib.rs
- tskv/src/reader/iterator.rs
- tskv/src/reader/tag_scan.rs
> [Improve] use TagId replace to TagName

- .github/workflows/build_package_and_push.yml
- .github/workflows/community-tag_docker_build_and_push.yml
> ci: build docker image after tagging

- query_server/query/src/execution/ddl/alter_table.rs
- query_server/query/src/sql/planner.rs
- query_server/spi/src/query/logical_planner.rs
- tskv/src/kvcore.rs
- tskv/src/reader/iterator.rs
- tskv/src/reader/tag_scan.rs
> refactor: refactor `get_series_key`

- query_server/query/src/data_source/stream/tskv/factory.rs
- query_server/sqllogicaltests/cases/stream/syntax.slt
> fix: add check of parameter event_time_column of stream table

- query_server/query/src/data_source/table_source.rs
- query_server/query/src/sql/planner.rs
- query_server/sqllogicaltests/cases/stream/unsupport_op.slt
> fix: fix the error_message error when alter stream table

- query_server/query/src/dispatcher/manager.rs
- query_server/query/src/dispatcher/query_tracker.rs
- query_server/query/src/execution/ddl/mod.rs
- query_server/query/src/execution/dml/mod.rs
- query_server/query/src/execution/query.rs
- query_server/query/src/execution/stream/mod.rs
- query_server/query/src/execution/sys/mod.rs
- query_server/spi/src/query/dispatcher.rs
> fix: stream job lost database info when restart

- query_server/query/src/data_source/stream/tskv/factory.rs
- query_server/sqllogicaltests/cases/stream/syntax.slt
> fix: disable creation of stream table with columns with the same name

- main/src/http/http_service.rs
> [LTS/2.3] feat: routing both write requests and SQL requests to query server

- main/src/http/http_service.rs
> feat: routing both write requests and SQL requests to query server

- common/models/src/arrow/mod.rs
- common/models/src/errors.rs
- common/models/src/sql/mod.rs
- meta/src/store/dump.rs
> refactor: add trait ToDDLSql

- Cargo.lock
- Cargo.toml
- common/protocol_parser/src/lib.rs
- main/src/http/http_service.rs
- main/src/http/mod.rs
- main/src/server.rs
- query_server/query/src/extension/expr/scalar_function/gis/mod.rs
- query_server/query/src/extension/expr/scalar_function/gis/st_area.rs
- query_server/query/src/extension/expr/scalar_function/gis/st_binary_op.rs
- query_server/query/src/extension/expr/scalar_function/gis/st_distance.rs
- query_server/sqllogicaltests/cases/function/gis/st_contains.slt
- query_server/sqllogicaltests/cases/function/gis/st_disjoint.slt
- query_server/sqllogicaltests/cases/function/gis/st_equals.slt
- query_server/sqllogicaltests/cases/function/gis/st_intersects.slt
- query_server/sqllogicaltests/cases/function/gis/st_within.slt
- tskv/src/file_utils.rs
> feat: add relation gis function 

- client/src/main.rs
> fix: hidden cli user password

- main/src/http/http_service.rs
- query_server/query/src/dispatcher/manager.rs
- query_server/query/src/sql/parser.rs
> fix: fix log show user password

- common/models/src/schema.rs
- e2e_test/src/independent/restart_tests.rs
- query_server/query/src/execution/ddl/drop_global_object.rs
- query_server/spi/src/query/logical_planner.rs
- query_server/test/cases/sys_table/cluster_schema/tenants.result
> fix: uniform drop_after name, add unset drop after(#1773)

- client/src/main.rs
https://github.com/cnosdb/cnosdb/issues/1751
> fix：add description for client chunk

- client/src/main.rs
> Merge some commits into LTS/2.3

- meta/src/store/storage.rs
- query_server/query/src/dispatcher/query_tracker.rs
> improve: delete debug log

- e2e_test/src/independent/api_router_tests.rs
- e2e_test/src/independent/coordinator_tests.rs
- e2e_test/src/independent/mod.rs
- e2e_test/src/independent/restart_tests.rs
- e2e_test/src/utils.rs
> test: add test case for api router

- config/config_8902.toml
- config/config_8912.toml
- config/config_8922.toml
- config/src/lib.rs
- config/src/storage_config.rs
- main/src/main.rs
- main/src/server.rs
- meta/src/model/meta_admin.rs
- meta/src/service/http.rs
- meta/src/service/single.rs
https://github.com/cnosdb/cnosdb/issues/1650
https://github.com/cnosdb/cnosdb/issues/1800
https://github.com/cnosdb/cnosdb/issues/1798
Related #.
[//]: # (There is no need to duplicate the description in the issue here, but it is sometimes worth providing a …
> fix bugs: server panic && reserve space && init dir

- common/utils/src/dedup.rs
- tskv/src/compaction/flush.rs
- tskv/tests/test_kvcore_interface.rs
> Fix/2.3: function dedup_by_front dropped wrong element

- common/lru_cache/src/sharded/asynchronous.rs
- tskv/src/tseries_family.rs
Related #1819, and #1561, #1742
> Fix/2.3: async LruCache sometimes causes segment fault

- e2e_test/src/independent/api_router_tests.rs
- e2e_test/src/independent/auth_tests.rs
- e2e_test/src/independent/coordinator_tests.rs
- e2e_test/src/independent/dump.rs
- e2e_test/src/independent/mod.rs
- e2e_test/src/independent/restart_tests.rs
- e2e_test/src/utils.rs
- query_server/sqllogicaltests/cases/dcl/role.slt
- query_server/sqllogicaltests/cases/dcl/tenant.slt
- query_server/sqllogicaltests/cases/dcl/user.slt
refactor: refact e2e_test
Related #.
> test: add test case: api router, auth

- .github/workflows/community-tag_docker_build_and_push.yml
> ci: fix docker ci

- common/utils/src/dedup.rs
- tskv/src/compaction/flush.rs
> Fix: function dedup_by_front dropped wrong element

- common/protos/src/lib.rs
- config/config.toml
- config/config_8902.toml
- config/config_8912.toml
- config/config_8922.toml
- config/src/lib.rs
- config/src/service_config.rs
- coordinator/src/raft/manager.rs
- coordinator/src/raft/mod.rs
- coordinator/src/raft/writer.rs
- coordinator/src/reader/table_scan/opener.rs
- coordinator/src/reader/tag_scan/opener.rs
- coordinator/src/service.rs
- coordinator/src/vnode_mgr.rs
- coordinator/src/writer.rs
- main/src/rpc/grpc_service.rs
- main/src/rpc/tskv.rs
- main/src/server.rs
- meta/config/config.toml
- meta/config/config_8901.toml
- meta/config/config_8911.toml
- meta/config/config_8921.toml
- meta/config/config_8931.toml
- meta/src/service/server.rs
- meta/src/store/config.rs
- replication/src/main.rs
- replication/src/network_client.rs
- replication/src/raft_node.rs
> feat: add config service.grpc_enable_gzip

- coordinator/src/lib.rs
- coordinator/src/resource_manager.rs
- coordinator/src/service.rs
- coordinator/src/service_mock.rs
- meta/src/service/init.rs
- replication/src/lib.rs
- replication/src/node_store.rs
- tskv/src/index/ts_index.rs
- tskv/src/kvcore.rs
- tskv/src/vnode_store.rs
- tskv/src/wal/raft_store.rs
> implement ddl raft write

- meta/src/store/state_machine.rs
https://github.com/cnosdb/cnosdb/issues/1829
Related #.
> fix: create meta snapshot is empty 

- common/models/src/meta_data.rs
- config/config.toml
- config/config_8902.toml
- config/config_8912.toml
- config/config_8922.toml
- config/src/global_config.rs
- config/src/lib.rs
- meta/src/client.rs
- meta/src/model/meta_admin.rs
- meta/src/store/storage.rs
- meta/tests/cluster/main.rs
> refactor: remove cold_data_server config in community version

- .github/workflows/makefile.yml
> ci: add windows compitibility test to ci

- common/models/src/meta_data.rs
- config/config.toml
- config/config_8902.toml
- config/config_8912.toml
- config/src/lib.rs
- config/src/node_config.rs
- meta/src/client.rs
- meta/src/model/meta_admin.rs
- meta/src/store/state_machine.rs
- meta/tests/cluster/main.rs
> refactor: remove cold_data_server and NodeAttribute

- Cargo.lock
- meta/Cargo.toml
- meta/src/bin/main.rs
- meta/src/service/api.rs
- meta/src/store/command.rs
- meta/src/store/state_machine.rs
> add setkv/delete http interface in meta

- Cargo.lock
- Cargo.toml
- client/Cargo.toml
- client/src/main.rs
> [LTS/2.3] fix: hide password when starting cli

- Cargo.lock
- Cargo.toml
- common/http_protocol/Cargo.toml
- e2e_test/Cargo.toml
- e2e_test/src/case.rs
- e2e_test/src/cluster_def.rs
- e2e_test/src/independent/api_router_tests.rs
- e2e_test/src/independent/coordinator_tests.rs
- e2e_test/src/independent/dump.rs
- e2e_test/src/independent/https_api_tests.rs
- e2e_test/src/independent/mod.rs
- e2e_test/src/independent/restart_tests.rs
- e2e_test/src/lib.rs
- e2e_test/src/reliant/flight_sql.rs
- e2e_test/src/reliant/http_api_tests.rs
- e2e_test/src/reliant/kv_service_tests.rs
- e2e_test/src/reliant/mod.rs
- e2e_test/src/reliant/prom.rs
- e2e_test/src/reliant/vector_service_test.rs
- e2e_test/src/utils.rs
- meta/src/store/config.rs
> [Refactor/2.3] Refactor e2e_test utilities and independents

- .github/workflows/build_package_and_push.yml
- .github/workflows/community-tag_docker_build_and_push.yml
- .github/workflows/compatibility_test.yaml
> [LTS/2.3] ci: add compatibility test

- common/models/src/meta_data.rs
- coordinator/src/lib.rs
- coordinator/src/resource_manager.rs
- coordinator/src/service.rs
- coordinator/src/service_mock.rs
- meta/src/model/meta_admin.rs
- meta/src/model/meta_tenant.rs
- query_server/query/src/auth/auth_control.rs
- query_server/query/src/data_source/sink/tskv.rs
- query_server/query/src/execution/ddl/alter_database.rs
- query_server/query/src/execution/ddl/create_database.rs
- query_server/query/src/execution/ddl/drop_tenant_object.rs
- query_server/query/src/execution/ddl/recover_tenant.rs
- query_server/query/src/metadata/base_table.rs
- query_server/query/src/metadata/information_schema_provider/factory/columns.rs
- query_server/query/src/metadata/information_schema_provider/factory/databases.rs
- query_server/query/src/metadata/information_schema_provider/factory/tables.rs
- query_server/query/src/metadata/mod.rs
- tskv/src/schema/schemas.rs
- tskv/src/version_set.rs
> refactor tenant/database hidden

- .github/tools/install_dependencies.sh
- .github/workflows/build_package_and_push.yml
- .github/workflows/community-tag_docker_build_and_push.yml
- .github/workflows/compatibility_test.yaml
> [LTS/2.3] ci: fix package, docker ci, compatibility test ci

- tskv/src/tsm/block.rs
Merge PR #1638 of the `main` branch into `LTS/2.3` branch.
> [Fix/2.3] tskv iterator sometimes returns more data than expected

- config/config_8902.toml
- config/config_8912.toml
- config/config_8922.toml
- e2e_test/src/utils.rs
> using raft replication as the default mode

- config/config_8902.toml
- config/config_8912.toml
- config/config_8922.toml
- config/src/cluster_config.rs
- coordinator/src/raft/manager.rs
- main/src/server.rs
- meta/config/config_8901.toml
- meta/config/config_8911.toml
- meta/config/config_8921.toml
- meta/config/config_8931.toml
- meta/src/error.rs
- meta/src/model/meta_admin.rs
- meta/src/service/server.rs
- meta/src/service/single.rs
- meta/src/store/config.rs
- meta/src/store/storage.rs
- meta/tests/cluster/main.rs
- replication/src/apply_store.rs
- replication/src/entry_store.rs
- replication/src/lib.rs
- replication/src/main.rs
- replication/src/network_client.rs
- replication/src/network_http.rs
- replication/src/node_store.rs
- replication/src/raft_node.rs
- replication/src/state_store.rs
- tskv/src/wal/raft_store.rs
> impl replication config in config file

- README.md
- README_CN.md
> chore: add CnosDB Cloud Portal.

- query_server/query/src/sql/parser.rs
> refactor: modify show syntax error info(#1841)

- coordinator/src/raft/manager.rs
- coordinator/src/raft/mod.rs
- coordinator/src/raft/writer.rs
- replication/src/errors.rs
- replication/src/main.rs
- replication/src/network_client.rs
> response raft replication apply error to user

- query_server/query/src/metadata/mod.rs
> fix: 'cnosdb' and other tenant check system db(#1567)

- coordinator/src/service.rs
- coordinator/src/writer.rs
- main/src/rpc/tskv.rs
- tskv/src/compaction/check.rs
- tskv/src/engine_mock.rs
- tskv/src/kvcore.rs
- tskv/src/wal/mod.rs
- tskv/src/wal/reader.rs
> fix: wide-table cause copy_into error

- tskv/src/compaction/flush.rs
- tskv/src/compaction/mod.rs
- tskv/src/memcache.rs
- tskv/src/tseries_family.rs
> fix: update version before flush

- Cargo.lock
- common/models/src/predicate/domain.rs
- common/models/src/schema.rs
> fix: remove ScalarValueForkDF

- config/config.toml
- config/config_8902.toml
- config/config_8912.toml
- config/src/storage_config.rs
- coordinator/src/lib.rs
- coordinator/src/service.rs
- coordinator/src/service_mock.rs
- query_server/query/src/data_source/sink/obj_store/mod.rs
- query_server/query/src/dispatcher/manager.rs
- query_server/query/src/sql/planner.rs
- query_server/spi/src/query/datasource/mod.rs
- query_server/spi/src/query/execution.rs
- query_server/spi/src/query/session.rs
issue: https://github.com/cnosdb/cnosdb/issues/1935
> feat: add copyinto flush config and add queryid info at export file

- main/src/http/http_service.rs
- query_server/query/src/execution/ddl/create_database.rs
- query_server/query/src/execution/ddl/create_table.rs
- query_server/test/cases/ddl/create_table.result
> test: mock influxdb

- tskv/src/kvcore.rs
> fix: when no data, do not delete column data(#1795)

- tskv/src/compute/count.rs
> chore: count parallel by cpu nums

- query_server/query/src/dispatcher/persister.rs
> fix: when restart, deserialize stream failed

- config/config.toml
- config/config_8902.toml
- config/config_8912.toml
- config/src/lib.rs
- config/src/storage_config.rs
- e2e_test/src/utils.rs
- main/src/main.rs
- main/src/server.rs
- meta/src/model/meta_admin.rs
> [LTS/2.3] fix bugs: server panic && reserve space && init dir

- Cargo.lock
- config/Cargo.toml
- config/config.toml
- config/config_8902.toml
- config/config_8912.toml
- config/src/lib.rs
- tskv/src/file_system/file/cursor.rs
> feat: add "file_buffer_size" config item

- .github/workflows/community-tag_docker_build_and_push.yml
> ci: remove 'if branch judge' in docker-ci

- client/src/exec.rs
- client/src/helper.rs
> optimize-cmd

- e2e_test/src/independent/restart_tests.rs
- tskv/src/database.rs
- tskv/src/kvcore.rs
- tskv/src/schema/schemas.rs
- tskv/src/vnode_store.rs
> fix DBschemas use wrong meta client

- tskv/src/compaction/compact.rs
- tskv/src/compaction/delta_compact.rs
- tskv/src/file_system/file/async_file.rs
- tskv/src/file_system/file/cursor.rs
- tskv/src/file_system/file/mod.rs
- tskv/src/file_system/file_manager.rs
- tskv/src/index/binlog.rs
- tskv/src/record_file/reader.rs
- tskv/src/record_file/writer.rs
- tskv/src/tsm/reader.rs
- tskv/src/wal/reader.rs
- tskv/src/wal/writer.rs
Related https://github.com/cnosdb/cnosdb/issues/1742
> fix memory use after free caused by pread

- README.md
- README_CN.md
> chore: repair some invaild links.

- common/models/src/series_info.rs
- tskv/src/compaction/compact.rs
- tskv/src/database.rs
- tskv/src/index/ts_index.rs
- tskv/src/memcache.rs
- tskv/src/reader/memcache_reader.rs
- tskv/src/tseries_family.rs
- tskv/src/tsm2/mod.rs
- tskv/src/tsm2/page.rs
- tskv/src/tsm2/writer.rs
> feature: tsm meta add series buf

- tskv/src/file_system/file/async_file.rs
- tskv/src/file_system/file/cursor.rs
- tskv/src/file_system/file/mod.rs
- tskv/src/index/binlog.rs
- tskv/src/record_file/writer.rs
- tskv/src/tsm/writer.rs
Related #.https://github.com/cnosdb/cnosdb/issues/1995
> fix change async_file sync_data() to sync_all()

- query_server/spi/src/query/logical_planner.rs
- query_server/sqllogicaltests/cases/dml/copy_into/copy_into_location.slt
> fix: delimiter and with_header fields are specific to CSV

- .github/workflows/community-tag_docker_build_and_push.yml
> [LTS/2.3] ci: build memcheck version image

- common/models/src/predicate/domain.rs
- coordinator/src/reader/table_scan/opener.rs
- coordinator/src/reader/tag_scan/opener.rs
- main/src/rpc/tskv.rs
- tskv/src/reader/iterator.rs
- tskv/src/reader/query_executor.rs
> fix: count(tag) distributed problem

- .github/workflows/community-tag_docker_build_and_push.yml
> ci: remove "github.ref" judge in docker ci

- .github/workflows/community-tag_docker_build_and_push.yml
> ci: build memcheck version image

- config/config_8902.toml
- config/config_8912.toml
- config/config_8922.toml
- config/src/cluster_config.rs
- config/src/lib.rs
- config/src/meta_config.rs
- config/src/query_config.rs
- coordinator/src/raft/manager.rs
- coordinator/src/raft/writer.rs
- coordinator/src/reader/table_scan/opener.rs
- coordinator/src/reader/tag_scan/opener.rs
- main/src/server.rs
- query_server/spi/src/query/logical_planner.rs
- tskv/src/kv_option.rs
fix the difference in whether the same metric in the configuration file has units or not.
Return value json key to all lowercase, mainly related to vnode, datanodes interface, starting from version 2.3.4 onwards.
Related #.
[//]: # (There is no need to duplicate …
> fix: the difference in whether the same metric in the configuration file has units or not.

- e2e_test/src/independent/restart_tests.rs
- tskv/src/compaction/compact.rs
- tskv/src/compaction/flush.rs
- tskv/src/compaction/job.rs
- tskv/src/compaction/mod.rs
- tskv/src/database.rs
- tskv/src/kvcore.rs
- tskv/src/summary.rs
- tskv/src/tseries_family.rs
- tskv/src/version_set.rs
- tskv/tests/test_kvcore_interface.rs
> fix sequnece number in Version and VersionEdit when flush or compact

- query_server/query/src/extension/expr/aggregate_function/data_quality/accumulator.rs
- query_server/query/src/extension/expr/aggregate_function/data_quality/common.rs
- query_server/query/src/extension/expr/aggregate_function/data_quality/mod.rs
- query_server/query/src/extension/expr/aggregate_function/mod.rs
- query_server/sqllogicaltests/cases/function/data_quality.slt
> feat: add data quality functions

- tskv/src/error.rs
- tskv/src/tsm/page.rs
- tskv/src/tsm/reader.rs
- tskv/src/tsm/writer.rs
> Feature: Adding CRC32 checksums to TSM Page Files

- README.md
- README_CN.md
> docs: update eco integration to docs website.

- tskv/src/file_system/file/os/windows.rs
> fix: cnosdb restart failed on windows

- Cargo.lock
- common/http_protocol/src/parameter.rs
- common/protocol_parser/Cargo.toml
- common/protocol_parser/src/es_log/mod.rs
- common/protocol_parser/src/es_log/parser.rs
- common/protocol_parser/src/lib.rs
- e2e_test/src/independent/api_router_tests.rs
- main/src/http/api_type.rs
- main/src/http/http_service.rs
- main/src/http/mod.rs
Related #.
support index and create operator
> feat: Support log writing in es format

- client/src/exec.rs
- e2e_test/src/independent/client_tests.rs
> fix: Supports string values ​​with semicolon

- tskv/src/reader/iterator.rs
> perf: limit push down to RecordBatch read(#2033)

- query_server/sqllogicaltests/cases/dcl/assignment.slt
> test: support equal and space

- client/src/main.rs
> fix: update client help info

- e2e_test/test_data/dump.sql
- e2e_test/test_data/dump_tenant.sql
- meta/src/store/storage.rs
- query_server/sqllogicaltests/cases/dml/insert/line_protocol_write.slt
- query_server/sqllogicaltests/cases/sys_table/information_schema/database_privileges.slt
> fix: a role can't be assigned privileges if the db is not existent

- common/metrics/src/metric.rs
- tskv/src/database.rs
- tskv/src/tseries_family.rs
> fix: metric can delete vnode

- common/models/src/predicate/domain.rs
- common/protos/proto/kv_service.proto
- common/protos/src/generated/protobuf_generated/kv_service.rs
- common/protos/src/models_helper.rs
- coordinator/src/errors.rs
- coordinator/src/lib.rs
- coordinator/src/raft/manager.rs
- coordinator/src/raft/mod.rs
- coordinator/src/raft/writer.rs
- coordinator/src/reader/mod.rs
- coordinator/src/reader/table_scan/opener.rs
- coordinator/src/reader/tag_scan/opener.rs
- coordinator/src/resource_manager.rs
- coordinator/src/service.rs
- coordinator/src/service_mock.rs
- coordinator/src/tskv_executor.rs
- e2e_test/src/reliant/prom.rs
- main/src/rpc/tskv.rs
- meta/src/model/meta_tenant.rs
- query_server/query/src/execution/ddl/checksum_group.rs
- query_server/query/src/execution/ddl/compact_vnode.rs
- query_server/query/src/execution/ddl/copy_vnode.rs
- query_server/query/src/execution/ddl/drop_vnode.rs
- query_server/query/src/execution/ddl/move_node.rs
- query_server/query/src/prom/remote_server.rs
> optimize tskv server request process

- tskv/src/summary.rs
https://github.com/cnosdb/cnosdb/issues/2017
Related #.
> refactor: change del_tsf/add_tsf to enum in VersionEdit

- tskv/src/file_system/file/async_file.rs
- tskv/src/file_system/file/cursor.rs
- tskv/src/file_system/file_manager.rs
> fix pread & pwrite

- query_server/sqllogicaltests/cases/function/common/array_agg.slt
- query_server/sqllogicaltests/cases/function/common/avg.slt
- query_server/sqllogicaltests/cases/function/common/count.slt
- query_server/sqllogicaltests/cases/function/common/first.slt
- query_server/sqllogicaltests/cases/function/common/increase.slt
- query_server/sqllogicaltests/cases/function/common/last.slt
- query_server/sqllogicaltests/cases/function/common/max.slt
- query_server/sqllogicaltests/cases/function/common/min.slt
- query_server/sqllogicaltests/cases/function/common/mode.slt
- query_server/sqllogicaltests/cases/function/common/sum.slt
Related #.
Add test cases about functions count, sum, min, max, avg, array_agg, first, last, mode, increase.
[//]: # (There is no need to duplicate the description in the issue here, but it is sometimes worth providing a summary of the individual changes in this …
> [TESTCASES]Add common function test cases.

- query_server/query/src/sql/planner.rs
- query_server/sqllogicaltests/cases/dcl/user.slt
> fix: forbid other users modifying the root user information

- tskv/src/index/ts_index.rs
> fix: index lose data when multi thread write

- tskv/src/compaction/compact.rs
- tskv/src/compaction/flush.rs
- tskv/src/reader/chunk.rs
- tskv/src/reader/page.rs
- tskv/src/tsm/chunk.rs
- tskv/src/tsm/chunk_group.rs
- tskv/src/tsm/column_group.rs
- tskv/src/tsm/footer.rs
- tskv/src/tsm/mod.rs
- tskv/src/tsm/page.rs
- tskv/src/tsm/reader.rs
- tskv/src/tsm/writer.rs
https://github.com/cnosdb/cnosdb/issues/1919
Related #.
> fix : Adjust the execution order of flush, change usize to u64, rationalize the execution of the tsm part of the statement.

- common/models/src/auth/user.rs
- e2e_test/src/independent/restart_tests.rs
- meta/config/config.toml
- meta/config/config_8901.toml
- meta/config/config_8911.toml
- meta/config/config_8921.toml
- meta/config/config_8931.toml
- meta/src/service/init.rs
- meta/src/service/single.rs
- meta/src/store/config.rs
Related #1750 
root has a default password "root" now 
> fix: user root has a default password.

- tskv/src/compaction/compact.rs
- tskv/src/compaction/job.rs
- tskv/src/memcache.rs
https://github.com/cnosdb/cnosdb/issues/2060
Related #.
> fix: memcache drop error causing reading of outdated data.

- common/models/src/auth/user.rs
- e2e_test/src/independent/auth_tests.rs
- main/src/http/http_service.rs
- query_server/query/src/dispatcher/manager.rs
- query_server/query/src/sql/planner.rs
- query_server/spi/src/query/logical_planner.rs
> feat: implement the must_change_password field for the user.

- Cargo.lock
- Cargo.toml
- common/trace/Cargo.toml
- common/trace/src/lib.rs
- tskv/Cargo.toml
> fix: security issue

- query_server/query/src/sql/planner.rs
- query_server/test/cases/dcl/alter_user.result
- query_server/test/cases/dcl/alter_user.sql
> fix(2.3): forbid other users modifying the root user information (#2052)

- common/metrics/src/metric.rs
- query_server/sqllogicaltests/cases/sys_table/usage_schema/vnode_cache_size.slt
- tskv/src/database.rs
- tskv/src/tseries_family.rs
> fix(2.3): metric can delete vnode info

- tskv/src/index/ts_index.rs
> fix: serial build inverted index

- tskv/src/compaction/compact.rs
- tskv/src/tseries_family.rs
> fix: load bloom filter dead lock

- Cargo.lock
- Cargo.toml
- config/src/cluster_config.rs
- coordinator/src/raft/manager.rs
- coordinator/src/raft/mod.rs
- meta/src/service/http.rs
- meta/src/service/server.rs
- meta/src/store/storage.rs
- replication/src/apply_store.rs
- replication/src/entry_store.rs
- replication/src/errors.rs
- replication/src/lib.rs
- replication/src/multi_raft.rs
- replication/src/network_client.rs
- replication/src/network_http.rs
- replication/src/node_store.rs
- replication/src/raft_node.rs
- replication/src/state_store.rs
- tskv/src/tseries_family.rs
- tskv/src/vnode_store.rs
- tskv/src/wal/wal_store.rs
- tskv/tests/test_kvcore_interface.rs
> update openraft to v0.9.5

- config/config.toml
- config/config_8902.toml
- config/config_8912.toml
- config/config_8922.toml
- config/src/lib.rs
- config/src/storage_config.rs
- tskv/src/compaction/compact.rs
- tskv/src/kv_option.rs
- tskv/src/tseries_family.rs
> refactor: add config for datablock size

- client/src/exec.rs
- dump.sql
- e2e_test/src/independent/client_tests.rs
- e2e_test/src/independent/dump.rs
- e2e_test/test_data/dump.sql
- e2e_test/test_data/dump_multi.sql
- query_server/sqllogicaltests/cases/sys_table/usage_schema/vnode_cache_size.slt
- query_server/sqllogicaltests/cases/sys_table/usage_schema/vnode_disk_storage.slt
Related #1873 #1874 #1875 #1877 #2013 
> add test for 1873 1874 1875 1877 2013

- main/src/rpc/tskv.rs
- meta/src/model/meta_tenant.rs
- meta/src/store/command.rs
- meta/src/store/storage.rs
https://github.com/cnosdb/cnosdb/issues/2064
Related #.
> request meta when write data not found replication set

- tskv/src/wal/wal_store.rs
> fix: recover data mark wal entries use wrong reader

- common/http_protocol/src/parameter.rs
- common/protocol_parser/src/es_log/mod.rs
- common/protocol_parser/src/es_log/parser.rs
- e2e_test/src/case.rs
- e2e_test/src/independent/api_router_tests.rs
- e2e_test/src/independent/computing_storage_tests.rs
- e2e_test/src/independent/https_api_tests.rs
- main/src/http/http_service.rs
Related #2075 .
Fixed issue2075 
Multi-layer json patting flat 
Multiple tags are supported; if no tag is specified, it is treated as a field 
Remove msg_field and change the http parameters to tag_columns and time_column
add e2e_test
> feat: optimize eslog api usage methods and add e2e_test

- .github/tools/install_dependencies.sh
- Cargo.lock
- Cargo.toml
- common/protos/src/generated/flatbuffers_generated/models.rs
> [LTS/2.3] chore: upgrade flatbuffers

- .github/workflows/makefile.yml
- client/src/exec.rs
- e2e_test/src/independent/client_tests.rs
- e2e_test/src/independent/mod.rs
> fix(2.3):supports string values ​​with semicolon

- tskv/src/reader/page.rs
> fix: page slice out of index

- coordinator/src/raft/manager.rs
- coordinator/src/service.rs
> improve: wal multithreading recover

- tskv/src/index/binlog.rs
> fix: binlog next block panic

- common/http_protocol/src/parameter.rs
- common/protocol_parser/src/es_log/parser.rs
- main/src/http/http_service.rs
> feat: add 'have_es_command' for es api

- common/protos/proto/kv_service.proto
- common/protos/src/generated/protobuf_generated/kv_service.rs
- coordinator/src/errors.rs
- coordinator/src/lib.rs
- coordinator/src/raft/manager.rs
- coordinator/src/service.rs
- main/src/rpc/tskv.rs
- tskv/src/file_system/mod.rs
ReplicationCmdType::PromoteLeader
Related #.
> promote follower as leader process

- meta/src/service/server.rs
> fix: 2.4 modify the meta http frame body size to 100M.

- Cargo.lock
- Cargo.toml
- replication/Cargo.toml
- replication/src/main.rs
> add some replication model unit tests

- meta/src/store/storage.rs
> fix: meta decode request failed result in openraft panic

- query_server/query/src/sql/parser.rs
> fix: replica and shard should not eq 0

- query_server/sqllogicaltests/cases/data_type/type_conversion/boolean.slt
> test: boolean parse test

- coordinator/src/raft/manager.rs
- e2e_test/src/independent/mod.rs
- e2e_test/src/independent/replica_test.rs
- query_server/query/src/execution/ddl/mod.rs
- query_server/query/src/execution/ddl/replica_add.rs
- query_server/query/src/execution/ddl/replica_destory.rs
- query_server/query/src/execution/ddl/replica_promote.rs
- query_server/query/src/execution/ddl/replica_remove.rs
- query_server/query/src/execution/ddl/show_replica.rs
- query_server/query/src/sql/parser.rs
- query_server/query/src/sql/planner.rs
- query_server/spi/src/lib.rs
- query_server/spi/src/query/ast.rs
- query_server/spi/src/query/logical_planner.rs
Related #.
using example:
● show replicas
● replica destory replica_id 111 
● replica add replica_id 111 …
> implement replica manager sql command

- query_server/query/src/extension/expr/aggregate_function/gauge/gauge_agg.rs
- query_server/query/src/extension/physical/optimizer_rule/add_sort.rs
- query_server/query/src/extension/physical/optimizer_rule/mod.rs
- query_server/query/src/sql/physical/planner.rs
- query_server/sqllogicaltests/cases/function/gauge_agg.slt
> Ensure that the gaugeagg functions are ordered

- query_server/query/src/extension/expr/aggregate_function/gauge/gauge_agg.rs
- query_server/query/src/extension/physical/optimizer_rule/add_sort.rs
- query_server/query/src/extension/physical/optimizer_rule/mod.rs
- query_server/query/src/sql/physical/planner.rs
- query_server/sqllogicaltests/cases/function/gauge/gauge_agg.slt
> fix: gauge_agg func out of order problem

- dump.sql
- query_server/query/src/metadata/information_schema_provider/factory/resource_status.rs
- query_server/sqllogicaltests/cases/sys_table/information_schema/resource_status.slt
> fix: read privilege can read drop resource

- tskv/src/compaction/flush.rs
- tskv/src/compaction/job.rs
- tskv/src/compaction/mod.rs
- tskv/src/engine_mock.rs
- tskv/src/kvcore.rs
- tskv/src/lib.rs
- tskv/src/memcache.rs
- tskv/src/tseries_family.rs
- tskv/src/vnode_store.rs
- tskv/tests/test_kvcore_interface.rs
> enhance the flush timing of memcache

- config/config.toml
None
None
No
Minor typos have been corrected.
> chore(typo): config

- query_server/query/src/extension/physical/optimizer_rule/add_sort.rs
- query_server/sqllogicaltests/cases/function/common/unorderdata_func.slt
> fix: data disorder leads to inconsistent function results

- query_server/sqllogicaltests/cases/function/common/statistical_agg/corr.slt
- query_server/sqllogicaltests/cases/function/common/statistical_agg/covar.slt
- query_server/sqllogicaltests/cases/function/common/statistical_agg/covar_pop.slt
- query_server/sqllogicaltests/cases/function/common/statistical_agg/covar_samp.slt
- query_server/sqllogicaltests/cases/function/common/statistical_agg/stddev.slt
- query_server/sqllogicaltests/cases/function/common/statistical_agg/stddev_pop.slt
- query_server/sqllogicaltests/cases/function/common/statistical_agg/stddev_samp.slt
- query_server/sqllogicaltests/cases/function/common/statistical_agg/var.slt
- query_server/sqllogicaltests/cases/function/common/statistical_agg/var_pop.slt
- query_server/sqllogicaltests/cases/function/common/statistical_agg/var_samp.slt
Related #.
Add statistical agg func cases
NO
> [testcases]Add statistical agg func cases

- tskv/src/tseries_family.rs
> fix: frequent redundant flush request

- tskv/src/compaction/job.rs
> fix: add lock guard for flush

- tskv/src/compaction/compact.rs
- tskv/src/tsm/chunk.rs
- tskv/src/tsm/chunk_group.rs
- tskv/src/tsm/footer.rs
- tskv/src/tsm/mod.rs
- tskv/src/tsm/reader.rs
- tskv/src/tsm/writer.rs
> chore: add version for tsm

- e2e_test/src/cluster_def.rs
- e2e_test/src/independent/grpc_gzip_test.rs
- e2e_test/src/independent/mod.rs
- e2e_test/src/utils.rs
- query_server/sqllogicaltests/cases/sys_table/information_schema/enabled_roles.slt
> test: add some tests

- query_server/sqllogicaltests/cases/dcl/role.slt
> [testcase]Add testcase about issue2068

- config/config.toml
- config/config_8902.toml
- config/config_8912.toml
- config/src/cache_config.rs
- tskv/src/compaction/check.rs
- tskv/src/database.rs
- tskv/src/kv_option.rs
- tskv/src/kvcore.rs
- tskv/src/schema/schemas.rs
- tskv/src/summary.rs
- tskv/src/tseries_family.rs
> fix: add tsfamily dead lock

- query_server/sqllogicaltests/cases/ddl/delete_table.slt
- tskv/src/memcache.rs
> fix: delete data case inconsistency

- .github/workflows/compatibility_test.yaml
- .github/workflows/makefile.yml
> ci: add clippy_check in compatibility test

- main/src/http/api_type.rs
- main/src/http/http_service.rs
- main/src/http/metrics.rs
> feat: add http_flow table and http_response_time table

- Cargo.lock
- Cargo.toml
- common/models/src/schema.rs
- config/config.toml
- config/config_8902.toml
- config/config_8912.toml
- config/config_8922.toml
- config/src/tskv/query_config.rs
- e2e_test/src/independent/auth_tests.rs
- e2e_test/src/independent/restart_tests.rs
- e2e_test/test_data/dump.sql
- e2e_test/test_data/dump_tenant.sql
- meta/config/config.toml
- meta/config/config_8901.toml
- meta/config/config_8911.toml
- meta/config/config_8921.toml
- meta/config/config_8931.toml
- meta/src/service/single.rs
- query_server/query/Cargo.toml
- query_server/query/src/dispatcher/query_tracker.rs
- query_server/query/src/instance.rs
- query_server/query/src/metadata/cluster_schema_provider/factory/tenants.rs
- query_server/query/src/metadata/cluster_schema_provider/factory/users.rs
- query_server/query/src/metadata/cluster_schema_provider/mod.rs
- query_server/query/src/metadata/mod.rs
> feat: add sql_history table

- replication/src/entry_store.rs
- replication/src/lib.rs
- replication/src/node_store.rs
- tskv/src/file_system/file/stream_writer.rs
- tskv/src/wal/mod.rs
- tskv/src/wal/reader.rs
- tskv/src/wal/wal_store.rs
> Refactor: remove enum Block in wal; fix typos

- query_server/sqllogicaltests/src/instance.rs
- query_server/sqllogicaltests/src/main.rs
> feat: sqllogic support replaceable parameters

- common/cache/src/sharded_async_cache.rs
- config/config.toml
- config/config_8902.toml
- config/config_8912.toml
- config/src/wal_config.rs
- tskv/src/compaction/flush.rs
- tskv/src/context.rs
- tskv/src/kv_option.rs
- tskv/src/kvcore.rs
- tskv/src/summary.rs
- tskv/src/tseries_family.rs
- tskv/src/version_set.rs
- tskv/src/wal/mod.rs
> Feature(2.3): improve the performance to append summary

- common/models/src/lib.rs
- common/models/src/utils.rs
- tskv/src/compaction/compact.rs
- tskv/src/compaction/flush.rs
- tskv/src/memcache.rs
> Fix(2.3): Compaction cache offset overflow; Field blocks in delta files in order of field_id

- tskv/src/record_file/reader.rs
- tskv/src/wal/mod.rs
- tskv/src/wal/reader.rs
- tskv/src/wal/wal_store.rs
- tskv/src/wal/writer.rs
> fix: handle wal truncated

- common/models/src/schema.rs
- query_server/query/src/execution/ddl/create_external_table.rs
- query_server/query/src/sql/planner.rs
- query_server/query/tests/data/json/basic.ndjson
- query_server/sqllogicaltests/cases/ddl/create_external_table.slt
> fix: allow external table file with any extension

- Cargo.lock
- common/protos/Cargo.toml
- common/protos/src/lib.rs
- meta/src/service/single.rs
- meta/src/store/storage.rs
> create bucket test servers alive

- common/models/src/column_data.rs
> fix: minivec from empty s

- Cargo.lock
- client/Cargo.toml
- client/src/main.rs
- e2e_test/src/independent/mod.rs
- e2e_test/src/independent/version_check.rs
- meta/src/bin/main.rs
> chore: all component support --version

- config/src/meta/mod.rs
- meta/config/config.toml
- meta/config/config_8901.toml
- meta/config/config_8911.toml
- meta/config/config_8921.toml
- meta/config/config_8931.toml
- meta/src/service/server.rs
https://github.com/cnosdb/cnosdb/issues/2082
Currently we don't support modifying meta_init or it will cause the cluster to fail, so we need to temporarily remove the meta_config from the
Related #.
[//]: # (There is no need to duplicate the description in the …
> [Refactor] remove some config items in meta config.

- tskv/src/memcache.rs
- tskv/src/reader/iterator.rs
- tskv/src/reader/memcache_reader.rs
- tskv/src/tseries_family.rs
https://github.com/cnosdb/cnosdb/issues/2185
Related #.
> perf query read memcache

- Cargo.toml
- common/cache/Cargo.toml
- common/error_code/Cargo.toml
- common/http_protocol/Cargo.toml
- common/license/Cargo.toml
- common/license/src/rsa_aes.rs
- common/limiter_bucket/Cargo.toml
- common/macros/Cargo.toml
- common/memory_pool/Cargo.toml
- common/metrics/Cargo.toml
- common/models/Cargo.toml
- common/protocol_parser/Cargo.toml
- common/protos/Cargo.toml
- common/trace/Cargo.toml
- common/utils/Cargo.toml
- config/Cargo.toml
- coordinator/Cargo.toml
- e2e_test/Cargo.toml
- main/Cargo.toml
- meta/Cargo.toml
- query_server/query/Cargo.toml
- query_server/spi/Cargo.toml
- query_server/sqllogicaltests/Cargo.toml
- replication/Cargo.toml
- tskv/Cargo.toml
> Chore: reformat Cargo.toml files

- query_server/sqllogicaltests/src/os/windows.rs
> fix: support new sqllogic's feature for windows

- Cargo.lock
- common/cache/Cargo.toml
> fix: add backtrace dep for cache

- Cargo.lock
- coordinator/src/raft/manager.rs
- coordinator/src/raft/mod.rs
- coordinator/src/service.rs
- meta/src/service/server.rs
- replication/Cargo.toml
- replication/src/lib.rs
- replication/src/main.rs
- replication/src/metrics.rs
- replication/src/multi_raft.rs
https://github.com/cnosdb/cnosdb/issues/2205
Related #.
> fix: update replication metrics result in deadlock

- query_server/query/src/metadata/information_schema_provider/builder/queries.rs
- query_server/query/src/metadata/information_schema_provider/factory/queries.rs
- query_server/query/src/sql/planner.rs
> feat: add datbase_name to queries

- query_server/query/src/metadata/information_schema_provider/factory/resource_status.rs
- query_server/sqllogicaltests/cases/sys_table/information_schema/resource_status.slt
> fix: only admin can read DropTenant

- tskv/src/compaction/compact.rs
- tskv/src/compaction/mod.rs
- tskv/src/compaction/picker.rs
- tskv/src/database.rs
- tskv/src/kv_option.rs
- tskv/src/kvcore.rs
- tskv/src/memcache.rs
- tskv/src/summary.rs
- tskv/src/tseries_family.rs
- tskv/src/version_set.rs
- tskv/src/vnode_store.rs
- tskv/src/wal/mod.rs
- tskv/tests/test_kvcore_interface.rs
> refactor: change the name to better distinguish owner from database

- common/models/src/schema/database_schema.rs
- coordinator/src/raft/mod.rs
- tskv/src/compaction/compact.rs
- tskv/src/compaction/flush.rs
- tskv/src/compaction/mod.rs
- tskv/src/compaction/picker.rs
- tskv/src/database.rs
- tskv/src/kv_option.rs
- tskv/src/kvcore.rs
- tskv/src/mem_cache/memcache.rs
- tskv/src/summary.rs
- tskv/src/tsfamily/level_info.rs
- tskv/src/tsfamily/tseries_family.rs
- tskv/src/tsfamily/tsf_metrics.rs
- tskv/src/tsfamily/version.rs
- tskv/src/version_set.rs
- tskv/src/vnode_store.rs
- tskv/tests/test_kvcore_interface.rs
…ring) tuple.
refactor:Replace the String type of tenant.database with a (String,String) tuple.
Related #.
[//]: # (There is no need to duplicate the description in the issue here, but it is sometimes worth providing a summary of the individual changes in this …
> refactor: replace the String type of tenant.database with a tuple.

- e2e_test/src/independent/auth_tests.rs
> test: test default root password

- e2e_test/src/independent/client_tests.rs
- e2e_test/src/independent/restart_tests.rs
- e2e_test/src/reliant/flight_sql.rs
- e2e_test/src/reliant/mod.rs
- e2e_test/src/utils.rs
- query_server/spi/src/query/execution.rs
> test: enable flight_sql test

- e2e_test/src/case.rs
- e2e_test/src/independent/auth_tests.rs
- e2e_test/src/independent/client_tests.rs
- e2e_test/src/independent/flush_tests.rs
- e2e_test/src/independent/grpc_gzip_test.rs
- e2e_test/src/independent/https_api_tests.rs
- e2e_test/src/independent/restart_tests.rs
- e2e_test/src/lib.rs
- e2e_test/src/reliant/http_api_tests.rs
- e2e_test/src/reliant/prom.rs
- e2e_test/src/utils.rs
- query_server/query/src/sql/parser.rs
- query_server/query/src/sql/planner.rs
> Refactor(e2e_test): improve the customization of data&meta instances

- common/metrics/src/count.rs
- common/metrics/src/duration.rs
- common/metrics/src/gauge.rs
- common/metrics/src/histogram.rs
- common/metrics/src/lib.rs
- common/metrics/src/metric.rs
- common/metrics/src/metric_register.rs
- coordinator/src/metrics.rs
- coordinator/src/service.rs
- tskv/src/compaction/metrics.rs
Related #2148.
-  Add unit tests and comments in package metrics.
- Merge all metrics in one batch and send to tskv.
- Add an upper bound for the histogram buckets of compaction metrics.
[//]: # (There is no need to duplicate the description in the issue here, but …
> Chore(metrics): Merge all reported metrics in one batch and send to tskv

- tskv/src/summary.rs
- tskv/src/version_set.rs
> fix: restart case data lose

- query_server/sqllogicaltests/cases/sys_table/information_schema/queries.slt
> test: add database_name for information_schema.queries

- coordinator/src/raft/writer.rs
- tskv/src/vnode_store.rs
> add debug log message

- e2e_test/src/independent/restart_tests.rs
Related #.
Add test case about restart count(*)
NO
> [testcase]Add test case about restart count(*)

- coordinator/src/raft/manager.rs
- main/src/http/http_service.rs
- main/src/vector/vector_server.rs
- query_server/sqllogicaltests/src/main.rs
- replication/src/main.rs
- replication/src/network_grpc.rs
> fix: unwrap_or constructed ahead of time.

- tskv/src/tsm/writer.rs
https://github.com/cnosdb/cnosdb/issues/1919
https://github.com/cnosdb/cnosdb/pull/2036
Related #.
> fix : rationalize the execution of the tsm part of the statement. 

- coordinator/src/tskv_executor.rs
- tskv/src/wal/wal_store.rs
> add log in recover && fix write result not exact

- client/src/ctx.rs
- client/src/main.rs
- common/http_protocol/src/http_client.rs
- e2e_test/Cargo.toml
- e2e_test/src/independent/client_tests.rs
- e2e_test/src/utils.rs
- main/src/http/http_service.rs
- main/src/report/mod.rs
Related #.
I used Axum to build a reverse-proxy [reverse-proxy](https://github.com/tokio-rs/axum/tree/main/examples/reverse-proxy) or use Hyper to build a gateway [gateway](https://github.com/hyperium/hyper/blob/master/examples/gateway.rs) to test this feature.
```sh
--proxy-url <URL>
Proxy URL, for HTTP or HTTPS requests
```
> Feature(cnosdb-cli): add argument --proxy-url for cnosdb-cli

- main/src/http/api_type.rs
- main/src/http/http_service.rs
- main/src/opentelemetry/otlp_to_jaeger.rs
> refactor: v1/traces change to api/v1/traces,table argument change to required entry

- common/protocol_parser/src/json_protocol/parser.rs
- e2e_test/src/independent/https_api_tests.rs
- main/src/http/http_service.rs
- main/src/http/mod.rs
1. when flattening json, name is empty and not filled in
2. multiple identical error messages are distinguished
3. remove the use of create and index in the es write interface
> refactor: optimize log related code

- common/protocol_parser/src/json_protocol/parser.rs
- main/src/http/http_service.rs
1. remove empty strings written to es log
2. increase error information, easy to locate
> fix: es log write error

- common/protocol_parser/src/json_protocol/mod.rs
- main/src/http/http_service.rs
> fix: eslog interface bulk format missing return value problem

- coordinator/src/errors.rs
- coordinator/src/lib.rs
- coordinator/src/service.rs
- e2e_test/src/independent/replica_test.rs
- meta/src/model/meta_tenant.rs
> enhance remove leader replica

- tskv/src/compaction/flush.rs
> fix: multi memcache flush

- Cargo.lock
- Cargo.toml
- common/utils/Cargo.toml
- common/utils/src/pprof_tools.rs
> fix not create memory profile file

- config/config.toml
- config/config_8902.toml
- config/config_8912.toml
- config/config_8922.toml
- config/src/tskv/storage_config.rs
- config/src/tskv/wal_config.rs
- coordinator/src/raft/manager.rs
- tskv/src/database.rs
- tskv/src/index/ts_index.rs
- tskv/src/kv_option.rs
- tskv/src/main.rs
- tskv/src/tsfamily/tseries_family.rs
- tskv/src/wal/mod.rs
- tskv/src/wal/reader.rs
- tskv/src/wal/wal_store.rs
- tskv/src/wal/writer.rs
> add config item index cache capacity and wal compress type

- common/models/src/meta_data.rs
- common/protos/proto/kv_service.proto
- common/protos/src/generated/protobuf_generated/kv_service.rs
- config/config.toml
- config/config_8902.toml
- config/config_8912.toml
- config/config_8922.toml
- config/src/tskv/global_config.rs
- coordinator/src/errors.rs
- coordinator/src/raft/manager.rs
- coordinator/src/service.rs
- main/src/rpc/tskv.rs
- meta/src/model/meta_admin.rs
- meta/src/model/meta_tenant.rs
> Pre create bucket

- coordinator/src/service.rs
fix two pr commit cause compile error
> fix compile error

- query_server/query/src/extension/analyse/transform_bottom_func_to_topk_node.rs
- query_server/query/src/extension/analyse/transform_topk_func_to_topk_node.rs
- query_server/query/src/extension/expr/expr_utils.rs
> fix selector function exprs deeply nested

- meta/src/model/meta_admin.rs
- query_server/query/src/dispatcher/persister.rs
- query_server/query/src/stream/watermark_tracker.rs
Fix the problem that streaming computing tasks fail to migrate when nodes fail
> fix: streaming computing tasks fail to migrate when nodes fail

- common/models/src/schema/database_schema.rs
- common/models/src/sql/mod.rs
- config/src/meta/mod.rs
- config/src/tskv/meta_config.rs
- e2e_test/src/cluster_def.rs
- meta/config/config.toml
- meta/config/config_8901.toml
- meta/config/config_8911.toml
- meta/config/config_8921.toml
- meta/config/config_8931.toml
- meta/src/service/init.rs
- meta/src/service/server.rs
- run_cluster.sh
1. modify run_cluster.sh, change from 3+2 to 3+3
2. add system db replica meta config, recommend replica 3
> refactor: add system db replica config

- config/config.toml
- config/config_8902.toml
- config/config_8912.toml
- config/config_8922.toml
> fix pre create bucket spell error

- common/models/src/schema/tskv_table_schema.rs
- coordinator/src/service.rs
- tskv/src/compaction/compact.rs
> fix: data lose when compaction

- main/src/http/mod.rs
- meta/src/model/meta_tenant.rs
- meta/src/store/command.rs
- meta/src/store/storage.rs
- tskv/src/error.rs
issue [Typo] collection of typos #2247
> modify typos

- common/http_protocol/src/header.rs
- e2e_test/src/independent/https_api_tests.rs
- e2e_test/src/reliant/http_api_tests.rs
- main/src/http/result_format.rs
- query_server/sqllogicaltests/src/instance.rs
> fix issue 2279

- query_server/query/src/metadata/mod.rs
- query_server/query/src/sql/parser.rs
- query_server/query/src/sql/planner.rs
- query_server/spi/src/query/ast.rs
- query_server/sqllogicaltests/cases/dql/file_query.slt
- tskv/src/compaction/compact.rs
- tskv/src/compaction/flush.rs
- tskv/src/compaction/job.rs
- tskv/src/compaction/picker.rs
- tskv/src/database.rs
- tskv/src/mem_cache/memcache.rs
- tskv/src/reader/iterator.rs
- tskv/src/reader/memcache_reader.rs
- tskv/src/reader/mod.rs
- tskv/src/reader/utils.rs
- tskv/src/summary.rs
- tskv/src/tsfamily/tseries_family.rs
- tskv/src/tsm/reader.rs
- tskv/src/tsm/tombstone.rs
- tskv/src/tsm/writer.rs
- tskv/src/version_set.rs
> Fix read data

- .gitlab-ci.yml
> ci: change tsbs test data

- meta/src/model/meta_admin.rs
- meta/src/model/meta_tenant.rs
> check privileges without meta

- common/protocol_parser/src/lib.rs
- common/protocol_parser/src/line_protocol/parser.rs
> impl new line protocol parser

- tskv/src/compaction/check.rs
- tskv/src/compaction/compact.rs
- tskv/src/compaction/flush.rs
- tskv/src/compaction/job.rs
- tskv/src/compaction/mod.rs
- tskv/src/database.rs
- tskv/src/engine_mock.rs
- tskv/src/kv_option.rs
- tskv/src/kvcore.rs
- tskv/src/lib.rs
- tskv/src/mem_cache/memcache.rs
- tskv/src/summary.rs
- tskv/src/tsfamily/tseries_family.rs
- tskv/src/tsfamily/version.rs
- tskv/src/version_set.rs
> chore: compaction vnode parallel

- common/models/src/schema/tskv_table_schema.rs
> refactor: add fields_ids and remove serialize columns index

- query_server/query/src/sql/parser.rs
- query_server/sqllogicaltests/cases/dcl/role.slt
- query_server/sqllogicaltests/cases/dcl/tenant.slt
- query_server/sqllogicaltests/cases/dcl/user.slt
- query_server/sqllogicaltests/cases/ddl/create_database.slt
- query_server/sqllogicaltests/cases/ddl/create_table.slt
> keyword is forbidden to contain slashes

- common/protocol_parser/src/json_protocol/parser.rs
- main/src/opentelemetry/otlp_to_jaeger.rs
> fix:Jaeger’s tag filtering

- e2e_test/src/independent/client_tests.rs
- e2e_test/src/independent/flush_tests.rs
- e2e_test/src/independent/replica_test.rs
- query_server/query/src/data_source/batch/tskv.rs
- query_server/query/src/extension/analyse/transform_exact_count_to_count.rs
- query_server/query/src/extension/expr/aggregate_function/exact_count_agg.rs
- query_server/query/src/extension/expr/aggregate_function/mod.rs
- query_server/query/src/extension/logical/optimizer_rule/push_down_aggregation.rs
- query_server/sqllogicaltests/cases/data_tests/data_ttl.slt
- query_server/sqllogicaltests/cases/function/common/count.slt
- tskv/src/reader/iterator.rs
- tskv/src/reader/pushdown_agg_reader.rs
> feat: pushdown count(field) and add exact_count func

- query_server/query/src/sql/parser.rs
Fixed the issue where a database and table could be created with empty names but lacked proper functionality.
> fix:database and table could be created with empty name

- query_server/query/src/extension/analyse/add_time_for_tsgenfunc.rs
- query_server/query/src/extension/analyse/mod.rs
- query_server/query/src/extension/analyse/transform_exact_count_to_count.rs
- query_server/query/src/sql/analyzer.rs
Related #.https://github.com/cnosdb/cnosdb/issues/2275
> fix: TimestampRepair func filter result lack time col

- common/models/src/column_data_ref.rs
- common/models/src/lib.rs
- common/models/src/mutable_batch.rs
- common/protocol_parser/src/lines_convert.rs
- tskv/src/database.rs
- tskv/src/mem_cache/row_data.rs
- tskv/src/tsm/mutable_column_ref.rs
- tskv/src/tsm/page.rs
> change mutable_batch with ref && improve point to row_data

- meta/src/store/command.rs
> fix: userinfo change not sync to data

- tskv/src/compaction/flush.rs
- tskv/src/compaction/job.rs
- tskv/src/compaction/mod.rs
- tskv/src/mem_cache/memcache.rs
- tskv/src/tsfamily/tseries_family.rs
- tskv/src/vnode_store.rs
> implement concurrency flush in one vnode

- e2e_test/src/reliant/prom.rs
- query_server/query/src/prom/remote_server.rs
> fix:prom remote read api unable to query upper case table name problem

- query_server/query/src/data_source/batch/tskv.rs
- query_server/sqllogicaltests/cases/data_tests/data_ttl.slt
> fix:count(*) empty table come to nothing

- common/http_protocol/src/parameter.rs
> fix: "api/v1/sql" and "api/vi/write" lack default parameter

- Cargo.lock
- query_server/query/src/data_source/batch/tskv.rs
- query_server/query/src/execution/query.rs
- query_server/query/src/execution/stream/mod.rs
- query_server/query/src/extension/logical/optimizer_rule/rewrite_tag_scan.rs
- query_server/query/src/sql/logical/optimizer.rs
- query_server/query/src/sql/optimizer.rs
- query_server/query/src/sql/planner.rs
- query_server/spi/src/query/logical_planner.rs
- query_server/spi/src/query/optimizer.rs
- query_server/sqllogicaltests/cases/dql/show_series.slt
- query_server/sqllogicaltests/cases/function/common/count.slt
> refactor: "select tag" no dedup, "show series" and "show tag values dedup

- e2e_test/src/independent/client_tests.rs
- query_server/query/src/extension/analyse/transform_exact_count_to_count.rs
> fix: exact_count empty table come to nothing

- common/models/src/predicate/domain.rs
- common/utils/src/bitset.rs
- tskv/src/compaction/compact.rs
- tskv/src/reader/mod.rs
- tskv/src/tsfamily/column_file.rs
- tskv/src/tsm/reader.rs
> Compaction bugs

- tskv/src/tsm/tombstone.rs
> Perf: Use rwlock in tombstone

- tskv/src/tsfamily/version.rs
> fix: compaction set wrong seq no

- tskv/src/kvcore.rs
> feature: add schedule compaction for vnode

- e2e_test/src/utils.rs
- query_server/query/src/prom/remote_server.rs
- query_server/query/src/prom/time_series/writer.rs
reduce function calls and string copying
> perf: improve remote read performance

- Cargo.lock
- query_server/sqllogicaltests/cases/sqlancer/select.slt
> fix: count nested failed

- tskv/src/database.rs
> fix: extra added table size

- query_server/query/src/extension/analyse/transform_count_gen_time_col.rs
> fix: "transform_count_gen_time_col" rule not apply to external table

- query_server/query/src/extension/physical/plan_node/state_save.rs
> fix: streaming computing cannot filter processed data

- tskv/src/tsfamily/super_version.rs
> fix: delete series case data inconsistency

- Cargo.lock
- common/models/Cargo.toml
- common/models/src/auth/auth_cache.rs
- common/models/src/auth/mod.rs
- main/src/flight_sql/mod.rs
- main/src/http/http_service.rs
- main/src/http/mod.rs
- main/src/server.rs
- query_server/query/src/dispatcher/manager.rs
- query_server/query/src/execution/ddl/alter_user.rs
- query_server/query/src/execution/ddl/drop_global_object.rs
- query_server/query/src/execution/ddl/grant_revoke.rs
- query_server/query/src/instance.rs
- query_server/spi/src/query/execution.rs
> fix: when ALTER/DROP USER or REVOKE, remove auth cache

- tskv/src/tsm/codec/boolean.rs
- tskv/src/tsm/codec/float.rs
- tskv/src/tsm/codec/instance.rs
- tskv/src/tsm/codec/integer.rs
- tskv/src/tsm/codec/mod.rs
- tskv/src/tsm/codec/simple8b.rs
- tskv/src/tsm/codec/string.rs
- tskv/src/tsm/codec/timestamp.rs
- tskv/src/tsm/codec/unsigned.rs
> Simple codec error define

- Cargo.lock
- main/src/main.rs
- meta/src/service/server.rs
- meta/src/service/single.rs
Related #.https://github.com/cnosdb/cnosdb/issues/2105
https://github.com/cnosdb/cnosdb/issues/2341
> perf:log add config &&fix:datafusion

- tskv/src/reader/iterator.rs
- tskv/src/reader/mod.rs
> chore: check tsm overlap when chunk merge

- common/utils/src/bitset.rs
- tskv/src/reader/page.rs
- tskv/src/tsm/page.rs
- tskv/src/tsm/reader.rs
> Simple column file reader code

- common/models/src/schema/database_schema.rs
- config/src/tskv/storage_config.rs
https://github.com/cnosdb/cnosdb/issues/2335
Related #.
> remove unnecessary const DEFAULT_*

- .github/workflows/github_mirror_to_gitlab.yml
- .gitlab-ci.yml
- benchmark/benchmark.sh
> test: add auto perf test and send to dingding

- .github/workflows/github_mirror_to_gitlab_pr.yml
> test: modify commit_id from 7 to 8

- tskv/src/reader/iterator.rs
- tskv/src/tsm/page.rs
- tskv/src/tsm/reader.rs
- tskv/src/tsm/tombstone.rs
> perf: reduce memory copy and calculations

- .github/workflows/github_mirror_to_gitlab.yml
> test: hide dingding token

- tskv/src/file_system/file/async_file.rs
- tskv/src/file_system/file/mod.rs
- tskv/src/mem_cache/memcache.rs
- tskv/src/mem_cache/series_data.rs
- tskv/src/tsfamily/column_file.rs
- tskv/src/tsfamily/super_version.rs
- tskv/src/tsfamily/tseries_family.rs
- tskv/src/tsfamily/version.rs
- tskv/src/tsm/chunk.rs
- tskv/src/tsm/reader.rs
- tskv/src/tsm/writer.rs
- tskv/src/vnode_store.rs
> fix: update tag case inconsistency

- query_server/sqllogicaltests/cases/dcl/dcl_tenant.slt
> test: add sqllogicaltests for ALTER TENANT SET USER and ALTER TENANT REMOVE USER

- common/models/src/predicate/domain.rs
Updated the Marker struct's serialization logic to store the ScalarValue as a protobuf-encoded byte array, improving interoperability and storage efficiency. Added unit tests to ensure correct serialization and deserialization.
#2393 
Related #.
[//]: # (There is …
> Refactor Marker serialization to use protobuf byte arrays

- common/utils/src/duration.rs
- config/src/meta/mod.rs
- config/src/tskv/mod.rs
- e2e_test/src/independent/restart_tests.rs
- query_server/query/src/execution/ddl/drop_global_object.rs
- query_server/spi/src/query/execution.rs
- query_server/sqllogicaltests/cases/dcl/dcl_tenant.slt
Related #.https://github.com/cnosdb/cnosdb/issues/2379
> perf: add drop tenant tips

- tskv/src/reader/column_group/mod.rs
- tskv/src/tsm/reader.rs
> Perf: Read adjacent pages at one time to reduce I/O count

- tskv/src/tsfamily/column_file.rs
- tskv/src/tsfamily/super_version.rs
> perf: optimize ColumnFile::add_tombstone by grouping series and columns for batch processing

- Cargo.lock
- Cargo.toml
> update openraft to v0.9.17

- tskv/src/compaction/compact/compact_test.rs
- tskv/src/compaction/compact/delta_compact_test.rs
- tskv/src/tsfamily/column_file.rs
- tskv/src/tsfamily/super_version.rs
- tskv/src/tsm/tombstone.rs
> fix: remove add tomb range open file

- .github/workflows/github_mirror_to_gitlab.yml
- .github/workflows/github_mirror_to_gitlab_ontime.yml
- .github/workflows/github_mirror_to_gitlab_pr.yml
- Cargo.lock
- Cargo.toml
- e2e_test/src/independent/client_tests.rs
- query_server/query/src/data_source/batch/tskv.rs
- query_server/query/src/extension/analyse/transform_exact_count_to_count.rs
- query_server/query/src/extension/logical/optimizer_rule/push_down_aggregation.rs
- query_server/sqllogicaltests/cases/function/common/count.slt
> fix: modify exact_count logical plan

- common/models/src/predicate/transformation.rs
- query_server/query/src/execution/dml/delete_from_table.rs
- query_server/sqllogicaltests/cases/data_type/type_conversion/double.slt
- query_server/sqllogicaltests/cases/ddl/delete_table_with_precision.slt
> fix: delete series convert ts

- common/trace/src/global_tracing.rs
- config/config.toml
- config/src/tskv/trace.rs
> feature: add trace log config

- tskv/src/vnode_store.rs
- tskv/src/wal/wal_store.rs
> fix: wal error never block sever start

- Cargo.lock
- common/models/Cargo.toml
- common/models/src/auth/auth_cache.rs
- common/models/src/auth/user.rs
- main/src/flight_sql/mod.rs
- main/src/http/http_service.rs
- main/src/server.rs
- query_server/query/src/dispatcher/manager.rs
- query_server/query/src/execution/ddl/alter_tenant.rs
- query_server/query/src/execution/ddl/alter_user.rs
- query_server/query/src/execution/ddl/drop_global_object.rs
- query_server/query/src/execution/ddl/drop_tenant_object.rs
- query_server/query/src/instance.rs
- query_server/spi/src/query/dispatcher.rs
- query_server/spi/src/query/execution.rs
> refactor: optimize auth cache implementation

- Cargo.lock
- tskv/Cargo.toml
- tskv/src/index/cache.rs
- tskv/src/index/engine.rs
- tskv/src/index/engine2.rs
- tskv/src/index/mod.rs
- tskv/src/index/ts_index.rs
> feature: index engine change to lmdb

- tskv/src/compaction/job.rs
- tskv/src/kvcore.rs
> perf: clear tsm reader cache when vnode became cold

- client/src/ctx.rs
- query_server/sqllogicaltests/cases/dml/insert/insert_select.slt
- query_server/sqllogicaltests/cases/dml/insert/insert_values.slt
Related #.https://github.com/cnosdb/cnosdb/issues/2407
> fix:connect database doesn't fail as expected

- config/src/meta/mod.rs
- e2e_test/src/utils/cnosdb/meta_node.rs
- main/src/main.rs
- main/src/server.rs
- meta/src/bin/main.rs
- tskv/src/kvcore.rs
> perf:Modify unwrap to return result

- .github/workflows/community-tag_docker_build_and_push.yml
> fix: switch to nightly toolchain for memcheck build
